### ISSUE TITLE
State of the inclusion candidates for Ansible 4

### ISSUE THREAD

**Issue by tadeboro** [ansible-community/community-topics#10]
This is a short overview of the inclusion candidates. Feel free to update the issue if I made a mistake or add a comment below if you would like to discuss something.

## Ready for inclusion

 1. [dellemc.enterprise_sonic](https://github.com/ansible-collections/ansible-inclusion/discussions/14)
 2. [hpe.nimble](https://github.com/ansible-collections/ansible-inclusion/discussions/13)
 3. [netapp.azure](https://github.com/ansible-collections/ansible-inclusion/discussions/17)
 4. [netapp.cloudmanager](https://github.com/ansible-collections/ansible-inclusion/discussions/16)

## Almost ready

 1. [netapp.um_info](https://github.com/ansible-collections/ansible-inclusion/discussions/18) - we need to decide if the `_info` module renaming can be delayed a bit

## Not ready

 1. [equinix.metal](https://github.com/ansible-collections/ansible-inclusion/discussions/15) - missing release policy documentation, CI does not run against ansible-core-2.11
 2. [infoblox.nios_modules](https://github.com/ansible-collections/ansible-inclusion/discussions/11) - failed to apply some fixes that are already part of community.general, there is a general lack of maintenance.
 3. [cisco.dnac](https://github.com/ansible-collections/ansible-inclusion/discussions/20) - content does not follow standard development practices.

**Comment by Andersson007** [comment]
+1 to Dell at least

**Comment by felixfontein** [comment]
From my POV, `dellemc.enterprise_sonic`, `hpe.nimble` and `netapp.azure` are ready. `netapp.cloudmanager` is basically also ready, a small detail has been fixed in the repository already and needs to be released (which I think will happen soon).

About `netapp.um_info`: there are a couple of modules named `na_um_list_<object>` which should be `_info` modules. (See discussion here: https://github.com/ansible-collections/ansible-inclusion/discussions/18#discussioncomment-646786)

**Comment by tadeboro** [comment]
I went through the reviews and updated the summary accordingly.

**Comment by tadeboro** [comment]
dellemc.enterprise_sonic accepted. Votes: `+1: 8 | 0: 0 | -1: 0`

**Comment by tadeboro** [comment]
hpe.nimble accepted. Votes: `+1: 8 | 0: 0 | -1: 0` (and `+1: 2` from community members).

**Comment by tadeboro** [comment]
netapp.azure accepted. Votes: `+1: 8 | 0: 0 | -1: 0` (and `+1: 2` from community members).

**Comment by tadeboro** [comment]
netapp.cloudmanager accepted. Votes: `+1: 8 | 0: 0 | -1: 0` (and `+1: 2` from community members).

**Comment by vielmetti** [comment]
@tadeboro Thanks for the detailed work here. I have an interest in getting the Equinix Metal work sorted out here (cc @mrmrcoleman) - if you could go into more detail about the deficiencies that you found, we should be able to adjust or schedule that work.

**Comment by tadeboro** [comment]
netapp.um_info accepted. Votes: `+1:  | 0: 3 | -1: 0` (and `+1: 1 | 0: 1` from community members). We expect the modules to be renamed to `_info` so the new names will be available in Ansible 4.1.0. This means this has to be in a minor release by 2021-06-08.

**Comment by tadeboro** [comment]
equinix.metal not accepted. Votes: `+1: 0 | 0: 1 | -1: 7` (and `0: 1 | -1: 1` from community members).

**Comment by tadeboro** [comment]
infoblox.nios_modules not accepted. Votes: `+1: 0 | 0: 1 | -1: 7` (and `-1: 2` from community members).

**Comment by tadeboro** [comment]
cisco.dnac not accepted. Votes: `+1: 0 | 0: 1 | -1: 7` (and `-1: 1` from community members).

**Comment by felixfontein** [comment]
The collections we decided to add were added here: https://github.com/ansible-community/ansible-build-data/pull/66

**Comment by tadeboro** [comment]
Thank you all for helping with the process!

**Comment by felixfontein** [comment]
@tadeboro thanks for all your reviewing and organizing!
