### ISSUE TITLE
[Default inclusion date 19th May 2022] cisco.dnac collection inclusion

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#101]
### Summary

Inclusion discussion https://github.com/ansible-collections/ansible-inclusion/discussions/20

The first review contained several must-fix items. I've conducted the second review from scratch and all the things have been fixed.

- According to the [Community collection inclusion workflow](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#collection-inclusion-requests-workflow), I'm going to set up a date (+1 week) when the inclusion decision will be considered made.
- This time period can be used to raise concerns.
- If no objections are raised up to the established date, the inclusion request is considered successfully resolved.

The default date of inclusion will be **19th of May 2022** if no critical concerns will be raised.

**Comment by felixfontein** [comment]
I did a cursory check, it seems to be ok.
