### ISSUE TITLE
Use the Discussions Poll feature for votes

### ISSUE THREAD

**Issue by briantist** [ansible-community/community-topics#104]
### Summary

I'd like to discuss the possibility of using the Polls feature in GitHub Discussions for votes instead of voting with "+1" messages.

Here's a sample poll I made:
- https://github.com/ansible-community/community-topics/discussions/103

### Voting with replies
* New notification on every vote leads to a lot of chatter and notifications
* Difficult to count

### Voting with discussions polls
* Much more streamlined process
* Votes are counted automatically
* No notification spam

Right now the biggest problem I see is that there doesn't seem to be a way to tell who voted on which option, which means distinguishing SC votes from Community votes might not be possible.. that could be a showstopper.. or maybe we can come up with workarounds? 

### Additional Information

I typed this up quickly, there's probably lots more to think about, just wanting to get the discussion (😏) started.

**Comment by felixfontein** [comment]
Two things we need:
1. Find out who voted for what.
2. Avoid allowing folks to change their votes once the vote is over.

**Comment by mariolenz** [comment]
> 1. Find out who voted for what.

Yes, I think this would be necessary. Or, alternatively, be able to allow only SC members to vote?

> 2. Avoid allowing folks to change their votes once the vote is over.

I should expect that nobody can change their vote once the poll is closed. This would make sense, wouldn't it? But I don't know, however we could easily test this.

**Comment by samccann** [comment]
Allowing only SC members to vote seems... restrictive. While their votes are the ones that count, it's helpful to see if the rest of the community leans the same way so to speak. But if there were a way to restrict the voting to SC members but have 'some other way' to capture the thoughts of the community as well, that might work.

**Comment by briantist** [comment]
I thought about something dumb like "just add additional poll options" like duplicating each one, an SC version and a community version, but it's ugly, and if there's no way to know who voted for what, then we can't even tell it was followed anyway. 

Separate polls are another idea along the same lines, easier to count and see vote comparisons, but requires two polls per vote, and still has the same problem if we can't see who voted :-/

**Comment by Andersson007** [comment]
i remember @briantist suggested a great idea for the news-for-maintainers repo to discuss the announcement issues in linked discussions, so that people can subscribe to issues only and don't get notifications about things happening in discussions. Can we apply the same here? In other words:
1) when a poll is open, we create a dedicated discussion putting the link in the open vote announcement
2) folks will vote with +1 as we do now in issues but in the discussions and not interested folks will not get notifications

Any thoughts?

**Comment by briantist** [comment]
> i remember @briantist suggested a great idea for the news-for-maintainers repo to discuss the announcement issues in linked discussions, so that people can subscribe to issues only and don't get notifications about things happening in discussions. 

Thanks, I do have to credit @ssbarnea for the idea of using discussions polls (this proposal) though.

> Can we apply the same here? In other words:
> 
> 1. when a poll is open, we create a dedicated discussion putting the link in the open vote announcement
> 2. folks will vote with +1 as we do now in issues but in the discussions and not interested folks will not get notifications
> 
> Any thoughts?

I think the only advantage is (automatic) removal of notifications, but we can do that now by unsubscribing from the vote issues.

The reason I don't unsubscribe after voting, is because I worry I will miss future messages (other than votes), like the vote results and such. In a way, it's better with issues in that we are subscribed by default, we can get initial notification of a vote, cast a vote, then unsubscribe if we want.. 

I guess if we are already getting notified on the original discussion issue, and there's a link to the vote posted there (whether that link goes to a new issue or a discussion), then that would satisfy the initial notification... if we made it a habit to post results, and other important things in the _original_ issue so that people get notified, it could be an improvement to use a discussion so that notifications are opt-in there...

But it still leaves us with the issue of vote counting.

**Comment by Andersson007** [comment]
We discussed it briefly in the meeting, let's maybe try it out once and see?
A person who will open next vote will:
1) create a dedicated discussion
2) linked it with the topic
3) ask folks to vote in the discussion
4) in the same comment, they'll say that they can subscribe only to issues to not get vote notifications

Let's try it? We'll get rid of one of the issues (main imo). If something goes wrong, we can at least turn back to the previous way at any moment.

**Comment by Andersson007** [comment]
- I've created an [experimental vote](https://github.com/ansible-community/community-topics/issues/97#issuecomment-1139314542) (but with real consequences), please vote in the [discussion](https://github.com/ansible-community/community-topics/discussions/106).
- I've created a [feature request](https://github.com/github/feedback/discussions/17367) in GH feedback repo, if you have something to add, please do.

thanks

**Comment by russoz** [comment]
> I found a GitHub bot that makes voting easier: https://github.com/cncf/gitvote - you can see it in action here: [cncf/sandbox#7 (comment)](https://github.com/cncf/sandbox/issues/7#issuecomment-1448542045) to [cncf/sandbox#7 (comment)](https://github.com/cncf/sandbox/issues/7#issuecomment-1458528110) Maybe this could be of interest for us as well.

This looks excellent to me.

**Comment by Andersson007** [comment]
> I found a GitHub bot that makes voting easier: https://github.com/cncf/gitvote - you can see it in action here: [cncf/sandbox#7 (comment)](https://github.com/cncf/sandbox/issues/7#issuecomment-1448542045) to [cncf/sandbox#7 (comment)](https://github.com/cncf/sandbox/issues/7#issuecomment-1458528110) Maybe this could be of interest for us as well.

+1 from me to try.
So how will we proceed?
I don't think we should vote on trying this. We could try to conduct a test vote "on switching to this tool":)
Are there any volunteers to lead the initiative?

**Comment by mariolenz** [comment]
Since we've moved votes and discussions to the Ansible forum (#279) I think we should close this.

@Andersson007 @briantist @felixfontein @russoz @samccann Feel free to re-open this issue if you think I've been wrong closing this issue.
