### ISSUE TITLE
[Vote ended on 2022-06-21] Collection inclusion requirements: only sanity tests run must be required for the release commit to publish the collection on Galaxy

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#108]
### Summary

Relates to https://github.com/ansible-collections/ansible-inclusion/discussions/44#discussioncomment-2889787.

See [the PR](https://github.com/ansible-collections/overview/pull/206) containing the suggested wording change.

As `integration/unit` tests are optional anyway and it can be expensive to run them against release commits, i suggest making their run optional.

imo it feels a bit strange if we, as now,
- in one statement of the [requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#ci-testing) make only sanity tests mandatory
- in the other statement require to run all available tests against release commits

This can lead to situations, like in @resmo 's [case](https://github.com/ansible-collections/ansible-inclusion/discussions/44#discussioncomment-2889787.), when the requirements will force him to remove the integration and unit tests to formally satisfy the requirements.
I would recommend running all the tests but would keep only sanity run mandatory as only their presence in collections is mandatory.

Also i don't see a requirement for collections that the publishing process must be automated, so maintainers can publish the collections even manually if they like.

**Comment by Andersson007** [comment]
The vote is open and will end on June 21, 2022.

Please vote in the [discussion](https://github.com/ansible-community/community-topics/discussions/110) with +1/-1 on merging [the PR](https://github.com/ansible-collections/overview/pull/206).

**Comment by Andersson007** [comment]
Vote has ended.
SC 8 voted +1, Community 0 votes

Could anyone from SC confirm the result?

**Comment by felixfontein** [comment]
I can confirm, 8 x +1 from steering committee persons (Andersson007, russoz, felixfontein, gundalow, mariolenz, briantist, jamescassell, acozine), no other votes.

**Comment by Andersson007** [comment]
@felixfontein thanks for the confirmation!
I've just merged the PR, thanks everyone!
