### ISSUE TITLE
Extend valid licenses for module_utils and modules: allow Apache 2.0 licensed code

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#109]
### Summary

https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#licensing specifies that all modules code must be licensed under [GPL-3.0-or-later](https://www.gnu.org/licenses/gpl-3.0-standalone.html), and all module_utils code must be licensed under [GPL-3.0-or-later](https://www.gnu.org/licenses/gpl-3.0-standalone.html) or [BSD-2-clause](https://opensource.org/licenses/BSD-2-Clause).

I propose to also allow [Apache-2.0](https://opensource.org/licenses/Apache-2.0) licensed code for both modules and module utils.

(Background: to address https://github.com/ansible-collections/community.docker/issues/364 it will be helpful to at least copy *some* code from Docker SDK for Python, or potentially vendor the whole Docker SDK for Python (and modify it). Having to rewrite all the Unix socket, streaming, etc. handling code from scratch isn't fun and feels like a huge waste of developer resources.)

**Comment by mariolenz** [comment]
Instead of adding the Apache 2 license as a valid licensing option (which might have implications we don't see yet) would it be possible to change the license to GPL 3 when copying some code from Docker SDK? Would this be legal?

And I think modules / module_utils under the Apache 2 license can't use GPL 3 licensed code from ansible-core:

```
merely linking to it is considered by the GPLv3 authors to create a derivative work
```

[APACHE LICENSE V2.0 AND GPL COMPATIBILITY](https://www.apache.org/licenses/GPL-compatibility.html)

Just asking, IANAL :shrug:

**Comment by felixfontein** [comment]
> Instead of adding the Apache 2 license as a valid licensing option (which might have implications we don't see yet)

I don't think it should be a problem, ansible-core itself for example contains Apache licensed code (`lib/ansible/module_utils/distro/_distro.py`). As long as you avoid the pitfalls you also mention, of course ;-)

We basically didn't allow it so far since this needs approval from RH legal, and such approvals can take a long time. (That's also why I want to start this process now so that it will hopefully be over once we actually really need this ;-) ) The collection requirements document has some links to lists of acceptable licenses both for Fedora and Debian, and Apache 2.0 is fine for both of them (as long as you don't combine it with GPL v2).

> would it be possible to change the license to GPL 3 when copying some code from Docker SDK? Would this be legal?

I don't think this would be legal. You cannot simply relicence other people's code. (But IANAL...)

> And I think modules / module_utils under the Apache 2 license can't use GPL 3 licensed code from ansible-core:

That's true, *but* there is no GPL 3 licensed code from ansible-core that *modules* can link to (AFAIK). Everything in ansilbe-core's module_utils is BSD licensed (except some third-party stuff like the `_distro.py` from above).

Plugins, on the other hand, are a different story. (And that's also why I didn't include plugin_utils in the above list, since code in there can link against ansible-core parts that are GPL licensed. In fact the only reason to put something in plugin_utils instead of module_utils is that the code can link to non-module_utils stuff from ansible-core, or from other collections.)

**Comment by mariolenz** [comment]
> We basically didn't allow it so far since this needs approval from RH legal, and such approvals can take a long time. (That's also why I want to start this process now so that it will hopefully be over once we actually really need this ;-) )

I don't have anything against Apache 2.0, I'm just afraid we would overlook some legal pitfalls. But if RH legal will have a look at this, anyway, I'm fine with adding Apache 2.0 as a valid licensing option if they approve.

> That's true, _but_ there is no GPL 3 licensed code from ansible-core that _modules_ can link to (AFAIK). Everything in ansilbe-core's module_utils is BSD licensed (except some third-party stuff like the `_distro.py` from above).

Is this documented somewhere? Looking at the [ansible-core repo](https://github.com/ansible/ansible), it says it licensed under GPL 3. It would be helpful to see that everything in module_utils is BSD licensed without having to look at every file individually.

> Plugins, on the other hand, are a different story. (And that's also why I didn't include plugin_utils in the above list, since code in there can link against ansible-core parts that are GPL licensed. In fact the only reason to put something in plugin_utils instead of module_utils is that the code can link to non-module_utils stuff from ansible-core, or from other collections.)

:+1:

**Comment by felixfontein** [comment]
> > That's true, _but_ there is no GPL 3 licensed code from ansible-core that _modules_ can link to (AFAIK). Everything in ansilbe-core's module_utils is BSD licensed (except some third-party stuff like the `_distro.py` from above).
> 
> Is this documented somewhere? Looking at the [ansible-core repo](https://github.com/ansible/ansible), it says it licensed under GPL 3. It would be helpful to see that everything in module_utils is BSD licensed without having to look at every file individually.

Not really, I'd say. There's https://docs.ansible.com/ansible/devel/dev_guide/developing_module_utilities.html#standard-module-utilities, but that's more a left-over from the past when *everything* was in ansible/ansible. At least grepping for `GPL` in lib/ansible/module_utils finds no matches.

**Comment by briantist** [comment]
I'm no expert on licenses but I think it's good to get the conversation started and to allow this if there are no blockers to doing so.

**Comment by mariolenz** [comment]
> > Is this documented somewhere? Looking at the [ansible-core repo](https://github.com/ansible/ansible), it says it licensed under GPL 3. It would be helpful to see that everything in module_utils is BSD licensed without having to look at every file individually.
> 
> Not really, I'd say. There's https://docs.ansible.com/ansible/devel/dev_guide/developing_module_utilities.html#standard-module-utilities, but that's more a left-over from the past when _everything_ was in ansible/ansible. At least grepping for `GPL` in lib/ansible/module_utils finds no matches.

@samccann You're working hard to improve the documentation, so maybe this would be interesting for you.

**Comment by Andersson007** [comment]
in the requirements we have (@felixfontein i saw you mentioned it but let me put it here):
>modules: | must be licensed with a free software license that is compatible with the GPL-3.0-or-later
>module_utils: | must be licensed with a free software license that is compatible with the GPL-3.0-or-later.

then
>Use [this table of licenses from the Fedora Project](https://fedoraproject.org/wiki/Licensing:Main#Software_License_List) to find which licenses are compatible with the GPLv3+. The license must be considered open source on both the Fedora License table and the [Debian Free Software Guidelines](https://wiki.debian.org/DFSGLicenses) to be allowed.

And i see Apache 2 license listed there.

Doesn't it automatically mean that it's allowed? IIRC we already included a collection licensed differently, didn't we? And we've recently added the PSF license to some collections

**Comment by felixfontein** [comment]
> IIRC we already included a collection licensed differently, didn't we?

I hope not :) Do you remember which one that could be?

> And we've recently added the PSF license to some collections

That's actually a violation of our rules, which I guess we should amend by relaxing the rules.

**Comment by Andersson007** [comment]
@felixfontein I'll try to recall/find. So for what we have the following then?

>Use [this table of licenses from the Fedora Project](https://fedoraproject.org/wiki/Licensing:Main#Software_License_List) to find which licenses are compatible with the GPLv3+. The license must be considered open source on both the Fedora License table and the [Debian Free Software Guidelines](https://wiki.debian.org/DFSGLicenses) to be allowed.

**Comment by felixfontein** [comment]
@Andersson007 that's the groundwork we'll need to extend the list of allowed licenses. The original idea was to use that as the rule, but getting that approved by RH legal is probably even more complicated. (Probably compiling a table out of that and getting it approved is feasible.)

**Comment by Andersson007** [comment]
> @Andersson007 that's the groundwork we'll need to extend the list of allowed licenses. The original idea was to use that as the rule, but getting that approved by RH legal is probably even more complicated. (Probably compiling a table out of that and getting it approved is feasible.)

@felixfontein to me personally this part of the requirements looks like everything is already decided:)

**Comment by felixfontein** [comment]
@Andersson007 if that applies to more people, then the requirement is badly worded and should be improved, because that is explicitly **not** what it should say.

**Comment by Andersson007** [comment]
@Andersson007 yes, let's change it then.

OK, if someone extends the topic with a set of licenses that would be nice to see approved, i would try to contact Legal myself.

**Comment by felixfontein** [comment]
@mariolenz it means that the modules / module_utils must have a license that allows them to be included in a GPLv3+ package (Ansible), and (for module_utils) that allows them to be used by GPLv3+ licensed code (for example plugins in the collection, or other collections depending on this one).

**Comment by felixfontein** [comment]
Actually we already allowed this, see #2 and https://github.com/ansible-collections/overview/pull/164. Sorry for the noise!
