### ISSUE TITLE
Changelog: New collection versions against last GA or against latest version?

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#113]
### Summary

The Ansible 6.0.0 changelog compares the included collections to [Ansible 5.0.0](https://github.com/ansible-community/ansible-build-data/blob/main/6/CHANGELOG-v6.rst#included-collections). Wouldn't it be better to compare against the latest 5.x (5.9) release?

**Comment by felixfontein** [comment]
The 6.0.0 changelog actually starts with 6.0.0a1, which was released on 2022-04-12. At that point 5.6.0 was the latest Ansible 5 release. One 6.0.0 is released all 6.0.0 pre-release entries are collapsed together into one 6.0.0 entry.

So if we would want to base the changelog on a later 5.x.0, we should pick 5.6.0 if we don't want to lose sanity with the changelog during the prereleases :) But then it would be hard to explain to users why the 6.0.0 changelog is based on 5.6.0, and not 5.0.0 or 5.9.0.

The way the Ansible changelog works is the same as it has been working with Ansible 2.9 and some versions before it. ansible-core is still using this model. I don't know for how long it has been using this model, and why this model was chosen.

Another thing: the ancestor for the changelog is also the ancestor for the porting guide. So if you want to upgrade say from Ansible 4.0.0 to Ansible 6.0.0, you don't have to read the 4.1.0, 4.2.0, ..., 4.9.0, 5.0.0, 5.1.0, ..., 5.9.0 porting guides and finally the 6.0.0 porting guide, but only the 5.0.0 and the 6.0.0 porting guides.

**Comment by mariolenz** [comment]
The thing is: Nobody will update from 5.0.0 to 6.0.0 (I hope).

As an example, if people look at the changelog they might think there's a new version of the `check_point.mgmt` collection. But if they update from a reasonably current version, there's no new `check_point.mgmt` version at all. It's 2.3.0 in Ansible 6.0.0, and it has been 2.3.0 in Ansible 5 since 5.5.0.

**Comment by felixfontein** [comment]
> The thing is: Nobody will update from 5.0.0 to 6.0.0 (I hope).

That's very likely not true. Especially if you use OS packages with a stable distro like Debian, you are upgrading a few major versions at once when a new Debian major version comes out.

**Comment by felixfontein** [comment]
One thing that came up during the discussion: Ansible 5.9.0 for example had community.dns 2.2.0, while 6.0.0 only has community.dns 2.1.1 (due to feature freeze).

Also the changelog of ansible-core, community.general and community.network follows the same way the current Ansible changelog does, so it's not really possible to show a proper Ansible 5.9.0 to 6.0.0 changelog for these components. (The collections can adjust the way their changelog works, at least to some extend; ansible-core might decide not to do that though.)

**Comment by mariolenz** [comment]
It looks like there are far more problems doing this than it might solve. Therefore, I'll close this for now and remove the `discussion_topic` label.

If anyone thinks we should discuss this further, feel free to open it again or open a new one.
