### ISSUE TITLE
[Vote ended on 2022-07-20] Ansible 7 Roadmap Planning

### ISSUE THREAD

**Issue by Ompragash** [ansible-community/community-topics#115]
### Summary

Created https://github.com/ansible/ansible/pull/78125 for **_Ansible 7 Roadmap_** that follows the same schedule pattern as  Ansible 6 and the _alpha, beta, rc1 & GA_ release dates for Ansible 7 are based on the [ansible-core 2.14 release schedule](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_14.html) accordingly.

**Comment by felixfontein** [comment]
My proposal would be
```.rst
:2022-11-07: Ansible-core-2.14.0 released.
:2022-11-07: Last day for collections to make backwards incompatible releases that will be accepted into Ansible-7. This includes adding new collections to Ansible 7.0.0; from now on new collections have to wait for 7.1.0 or later.
:2022-11-08: Create the ansible-build-data directory and files for Ansible-8.
:2022-11-08: Ansible-7.0.0 beta1 -- feature freeze [1]_ (weekly beta releases; collection owners and interested users should test for bugs).
:2022-11-15: Ansible-7.0.0 rc1 [2]_ [3]_ (weekly release candidates as needed; test and alert us to any blocker bugs).  Blocker bugs will slip release.
:2022-11-29: Ansible-7.0.0 release.
:2022-12-06: Release of ansible-core 2.14.1.
:2022-12-20: Release of Ansible-7.1.0 (bugfix + compatible features: every three weeks.)
```

**Comment by acozine** [comment]
Thanksgiving in the US is 2022-11-24, so most US folks will be out at least 2 days the week before the proposed 7.0.0 release. Is that okay?

**Comment by felixfontein** [comment]
(see https://github.com/ansible/ansible/commit/75bc6305650607c550f002aa06dfdbc399efe758)

**Comment by mariolenz** [comment]
> that was never intended, that week delay only happened because ansible-core on short notice moved their GA to one week earlier long after we finalized our schedule.

Ah, yes. Now that you mention it, I remember. So we don't have a changel to the Ansible 7 roadmap, we had one to to Ansible 6. In that case, your proposal looks OK to me.

**Comment by felixfontein** [comment]
We discussed in today's meeting that Thanksgiving probably won't have much of an impact, and that we like shrinking the period to two weeks or extending it to four weeks is also not a good option. (Moving everything, including the ansible-core 2.14 GA, one week earlier would move the release date into the Thanksgiving week, which isn't much better as well.) So let's vote on the current proposal.

**Comment by felixfontein** [comment]
@ansible-community/steering-committee I created a vote on [this proposal](https://github.com/ansible-community/community-topics/issues/115#issuecomment-1164771954) in https://github.com/ansible-community/community-topics/discussions/118, as discussed in today's meeting. Please check out the proposal and vote on it by writing a comment with `+1` or `-1` into the discussion :-)

**Comment by felixfontein** [comment]
@russoz @cidrblock @briantist @thaumos @gundalow @ssbarnea please do not forget to vote in https://github.com/ansible-community/community-topics/discussions/118. Thanks!

**Comment by felixfontein** [comment]
I counted 9 x +1 from SC (felixfontein acozine markuman mariolenz Andersson007 jamescassell ssbarnea briantist cidrblock) and 2 x +1 from community (Ompragash cybette). There were no other kind of votes.

**Comment by mariolenz** [comment]
@felixfontein I confirm, 9 x +1 from SC members, 2 x +1 from the community and no -1 at all.

**Comment by felixfontein** [comment]
Great, in that case the proposal
```.rst
:2022-11-07: Ansible-core-2.14.0 released.
:2022-11-07: Last day for collections to make backwards incompatible releases that will be accepted into Ansible-7. This includes adding new collections to Ansible 7.0.0; from now on new collections have to wait for 7.1.0 or later.
:2022-11-08: Create the ansible-build-data directory and files for Ansible-8.
:2022-11-08: Ansible-7.0.0 beta1 -- feature freeze [1]_ (weekly beta releases; collection owners and interested users should test for bugs).
:2022-11-15: Ansible-7.0.0 rc1 [2]_ [3]_ (weekly release candidates as needed; test and alert us to any blocker bugs).  Blocker bugs will slip release.
:2022-11-29: Ansible-7.0.0 release.
:2022-12-06: Release of ansible-core 2.14.1.
:2022-12-20: Release of Ansible-7.1.0 (bugfix + compatible features: every three weeks.)
```
has been accepted!

**Comment by felixfontein** [comment]
@Ompragash I created a suggestion for the proposal: https://github.com/ansible/ansible/pull/78125/files#r925931805

**Comment by samccann** [comment]
Roadmap published - https://docs.ansible.com/ansible/devel/roadmap/COLLECTIONS_7.html
