### ISSUE TITLE
Include purestorage.fusion in the ansible package (no vote's needed, will get included by default on 2022-07-06 if no objections) 

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#117]
### Summary

**No vote is needed**

Include purestorage.fusion in the ansible package as there are 2 SC reviews and approvals.

See the inclusion [discussion](https://github.com/ansible-collections/ansible-inclusion/discussions/48).

Will get included by default on **2022-07-06** (See [WF](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#collection-inclusion-requests-workflow)).
If you have some major concerns about the collection, please raise them ASAP.

**Comment by felixfontein** [comment]
CC @samccann I did a quick docs build on this collection, it resulted in no Sphinx warnings :tada:

**Comment by Andersson007** [comment]
Included https://github.com/ansible-community/ansible-build-data/pull/141, thanks everyone!
