### ISSUE TITLE
[Vote ended on 2022-08-22] Remove servicenow.servicenow in Ansible 7

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#124]
### Summary

The `servicenow.servicenow` collection has been [deprecated](https://github.com/ServiceNowITOM/servicenow-ansible#readme).

I think we should remove it in Ansible ~~8~~ 7.

ServiceNowITOM/servicenow-ansible#69
ansible-community/ansible-build-data#144
#44

**Comment by mariolenz** [comment]
Since `servicenow.servicenow` is officially deprecated, do we really have to wait until Ansible 8 to remove it? I mean, it's not a question of us _considering_ this collection unmaintained and give it a chance to be maintained again... they're telling people not to use it any more.

Personally, I'd aim to remove it from Ansible 7. That is, if it doesn't cause any dependency problems in Ansible 6. In that case, I'd remove it even sooner.

**Comment by felixfontein** [comment]
Discussed today:
1. Create PR that announces deprecation in Ansible 6 changelog with removal in Ansible 7
2. Create vote discussion on the PR.

To simplify such actions in the future:
3. Create PR for https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst to add a procedure which allows to mark collections as deprecated and for removal that have been somehow marked as deprecated by its maintainers, without the SC having to vote on it.

**Comment by mariolenz** [comment]
> 1. Create PR that announces deprecation in Ansible 6 changelog with removal in Ansible 7
> 2. Create vote discussion on the PR.

@felixfontein I've just opened ansible-community/ansible-build-data#156, but I'm not sure what you mean with a `vote discussion`.  Do you mean just a vote, or should I open a discussion to talk about this PR first? If I should open a discussion first, I could change the title of this discussion from `Remove servicenow.servicenow in Ansible 8` to `Remove servicenow.servicenow` and recycle it.

**Comment by felixfontein** [comment]
@mariolenz I think we can use this issue as the voting issue (votes always consist out of a GitHub discussion and an GitHub issue), but the voting (GH) discussion still needs to be created. I think we should start the vote now (with a runtime of one week) so we can merge the announcement by beginning of next week (so it's included in the next Ansible 6.x release).

**Comment by mariolenz** [comment]
> I think we should start the vote now (with a runtime of one week) so we can merge the announcement by beginning of next week (so it's included in the next Ansible 6.x release).

@felixfontein I've created #127, if this looks OK to you I would announce it on Bullhorn.

**Comment by mariolenz** [comment]
I counted votes: 7 x +1 from SC (mariolenz felixfontein Andersson007 jamescassell acozine russoz briantist), 4 x +1 from the community (oraNod gotmax23 vbotka cybette)

**Comment by Andersson007** [comment]
> I counted votes: 7 x +1 from SC (mariolenz felixfontein Andersson007 jamescassell acozine russoz briantist), 4 x +1 from the community (oraNod gotmax23 vbotka cybette)

I counted the same numbers:
Community 4x +1
SC 7x +1
Nobody is against

**Comment by mariolenz** [comment]
In that case the proposal has been accepted and we will announce to remove it from Ansible 7.

**Comment by mariolenz** [comment]
resolved_by ansible-community/ansible-build-data#156
