### ISSUE TITLE
Deprecate community.general's nios modules/plugins

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#13]
Since another chance to move the nios content from community.general to infoblox.nios_modules passed, and it is annoying for both users and maintainers that there are two copies of them around, I suggest we deprecate the nios content in community.general (for removal in community.general 5.0.0, i.e. in a year) where the deprecation message says to use the corresponding content from infoblox.nios_modules instead. If infoblox.nios_modules is included in Ansible before the removal happens, we can still replace the plugins with redirects, but if not, at least the users know where to find undeprecated versions of them.

The drawback (if infoblox.nios_modules is not eventually included in Ansible) is that the short names will be 'burned'.

**Comment by felixfontein** [comment]
Today's decision: deprecate the content.

If infoblox.nios_modules gets added to Ansible for Ansible 4 or 5, we can still replace the deprecations with redirects. If not, there will be tombstones.

**Comment by felixfontein** [comment]
We voted for deprecating the nios content from community.general (removal c.g 5.0.0) today. I will create a PR for that in c.g and close this once it is merged.

**Comment by felixfontein** [comment]
This has been implemented in ansible-collections/community.general#2458.

**Comment by gundalow** [comment]
I've made Ansible Partner Engineering aware of this.
Also comment added to https://github.com/ansible-collections/ansible-inclusion/discussions/11#discussioncomment-736961
