### ISSUE TITLE
Failed to resolve hostname inventory_hostname (Temporary failure in name resolution)

### ISSUE THREAD

**Issue by ahmad-rz** [ansible-community/community-topics#135]
### Summary

Hi,
I'm trying to run an ansible playbook just includes "show ip address" for cisco device and have issue with below errors.
Note: I can ssh to any device directly from cli and don't have any issue but this just happened when using ansible.

``
[WARNING]: ['connection local support for this module is deprecated and will be removed in version 2.14,
use connection ansible.netcommon.network_cli']
fatal: [172.22.15.21]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "ssh connection failed: ssh connect failed: Failed to resolve hostname inventory_hostname (Temporary failure in name resolution)"}
``

**Ansible.cfg file:**

``
[defaults]
inventory = ./hosts
host_key_checking = false ``

**Output of host file:**

```
[routers]
172.22.15.21 ansible_user=my_username ansible_password=my_password
```

**Playbook file:**
``
- name: first play
  hosts: routers
  gather_facts: false
  connection: local
  tasks:
   - name: first task
     ios_command:
         commands:
           - show ip int br
     register: var1
   - name: second task
     debug:
       var: var

``

**Comment by felixfontein** [comment]
This repository is **not** meant for support questions.

For questions on Ansible usage, please use the [mailing list](https://groups.google.com/g/ansible-project) or the [#users:ansible.com matrix room](https://matrix.to/#/#users:ansible.com). See [the communications page in the community docs](https://docs.ansible.com/ansible/latest/community/communication.html#communicating-with-the-ansible-community) for more information.
