### ISSUE TITLE
[Vote ended on 2022-10-11] Unmaintained collection: mellanox.onyx

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#136]
### Summary

The [mellanox.onyx](https://github.com/ansible-collections/mellanox.onyx) collection looks unmaintained / abandoned, it has:

* had only few commits the past 6 months about trivial stuff
* all by @Andersson007 to fix tests
* no release on Galaxy since version 1.0.0 2 years ago
* no CI run for 4 months
* no reaction on ansible-collections/mellanox.onyx#25

**Comment by Andersson007** [comment]
let's proceed

**Comment by gundalow** [comment]
@samerd Looks like the `mellanox.onyx` collection is going to be removed from the `ansible` package. See discussion in https://github.com/ansible-community/community-topics/issues/136

Vote is happening in https://github.com/ansible-community/community-topics/discussions/144

**Comment by mariolenz** [comment]
In that case the proposal has been accepted and we will announce to remove the collection from Ansible 8.

Thanks all!

**Comment by mariolenz** [comment]
@gundalow [suggested](https://github.com/ansible-community/community-topics/discussions/144#discussioncomment-3858794):

> * README.md updated to clearly state (at the top) that this is maintained
> * A release pushed to Galaxy based off the last release with just the updated README.md (no other CI, etc fixes)
> * Any open issues in the repo get a notice saying that the collection is unmaintained and will be removed
> 
> This should likely be added to our procedures for removing collections that we have `write` to

Although I guess the first point should read "is UNmaintained".

But since the collection _is_ unmaintained, I can't update the README.md because the CI fails: ansible-collections/mellanox.onyx#28 :cry:

**Comment by gotmax23** [comment]
> But since the collection _is_ unmaintained, I can't update the README.md because the CI fails: [ansible-collections/mellanox.onyx#28](https://github.com/ansible-collections/mellanox.onyx/pull/28) cry

The repository prevents merging pull requests if CI fails?

**Comment by mariolenz** [comment]
> > But since the collection _is_ unmaintained, I can't update the README.md because the CI fails: [ansible-collections/mellanox.onyx#28](https://github.com/ansible-collections/mellanox.onyx/pull/28) cry
> 
> The repository prevents merging pull requests if CI fails?

Well, yes... that's the idea, isn't it? You don't want to have code that fails the CI. While sometimes the tests are wrong, in most cases the code is buggy. You don't want to merge buggy code, do you?

**Comment by gundalow** [comment]
I can force merge the PR even if CI fails

**Comment by gundalow** [comment]
I've merged https://github.com/ansible-collections/mellanox.onyx/pull/28

**Comment by gotmax23** [comment]
> > > But since the collection _is_ unmaintained, I can't update the README.md because the CI fails: [ansible-collections/mellanox.onyx#28](https://github.com/ansible-collections/mellanox.onyx/pull/28) cry
> > 
> > 
> > The repository prevents merging pull requests if CI fails?
> 
> Well, yes... that's the idea, isn't it? You don't want to have code that fails the CI. While sometimes the tests are wrong, in most cases the code is buggy. You don't want to merge buggy code, do you?

Yes, I agree that's a good practice that we should follow. I was just clarifying.

**Comment by mariolenz** [comment]
> * Any open issues in the repo get a notice saying that the collection is unmaintained and will be removed

I've added this comment to all open issues / PRs of the collection:

> This collection is currently unmaintained, so nobody will work on your PR. See ansible-community/community-topics#136 for more information.
> 
> If you're interested in mainting this collection yourself, please read the [maintainer guidelines](https://docs.ansible.com/ansible/devel/community/maintainers.html) and let us know if you want to take over on [Matrix: #community:ansible.com](https://matrix.to/#/#community:ansible.com) or on `irc.libera.chat: #ansible-community`.

**Comment by gotmax23** [comment]
Implemented in https://github.com/ansible-community/ansible-build-data/commit/27aa007111eb8e46274c60bbe1fc3897f44b7341

**Comment by suhl79** [comment]
I'm not sure if this is the right place to ask this question, but does anybody have any information if NVIDIA is planning to work and release their own version of the ansible module for ONYX switches as they purchased Mellanox?

**Comment by Andersson007** [comment]
@suhl79 hello, i would suggest contacting the vendor directly, i don't think anyone here knows the answer.
