### ISSUE TITLE
Include vultr.cloud in the ansible package (no vote's needed, will get included by default on 2022-09-13 if no objections)

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#137]
### Summary

**No vote is needed**

Include vultr.cloud in the ansible package as there are 2 SC reviews and approvals.

See the [inclusion discussion](https://github.com/ansible-collections/ansible-inclusion/discussions/44).

Will get included by default on **2022-09-13** (See [WF](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#collection-inclusion-requests-workflow)).
If you have some major concerns about the collection, please raise them ASAP.

**Comment by felixfontein** [comment]
+1 for me

**Comment by felixfontein** [comment]
It's 2022-09-13 now, so I created https://github.com/ansible-community/ansible-build-data/pull/159 to implement this.

**Comment by Andersson007** [comment]
Merged, thanks everyone!
