### ISSUE TITLE
Inclusion requirement - editor configs, and the meaning of "unnecessary"

### ISSUE THREAD

**Issue by briantist** [ansible-community/community-topics#138]
### Summary

This came up during an [inclusion review](https://github.com/ansible-collections/ansible-inclusion/discussions/51) ([more discussion here](https://github.com/lowlydba/lowlydba.sqlserver/pull/122#discussion_r962187288)), but I think regardless of that specific situation we should clarify the requirements.

---

The [inclusion checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md) has:

> collection repository should not contain any unnecessary files like, for example, temporary files created by development tools. Temporary files MUST be added to .gitignore.

The [long form](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#collection-infrastructure) uses this text (with SHOULD and not MUST):

> SHOULD NOT contain any unnecessary files like, for example, temporary files created by development tools.

---

So there's a few questions here:
1. What exactly is meant by "unnecessary"? It's rather subjective since we can remove a whole lot files that are useful but not necessary for the collection to be used.
1. The example given focuses on temporary files, which I agree are not appropriate to be committed. We can probably make that a MUST (and temporary files are not limited to those created by editors).
1. Is it ok to add editor configs? This could be a `.vscode/` directory, or an [`.editorconfig` file](https://editorconfig.org/), or any number of others.
   1. Should this be a blanket allow/disallow?
   1. Should we allow only unobtrusive settings (which we will have to define the meaning of)?

**Comment by felixfontein** [comment]
I don't think we should have rules on / about editor/IDE configs, assuming they are rather small. These are not temporary files, and as long as they are small and concentrated in one location they should be OK IMO (if the maintainers want to have them in source control, that is - if they don't want to, there's no need to have them).

About SHOULD vs. MUST: if we change this to MUST, we have to be explicit on what we don't want to have in there. I'm not sure we want to get lost in that level of detail.

About unnecessary: this is intentionally vague (at least as I see it), since if we force everything that's not useful to **users** (as opposed to developers / packagers / ...) of the collection to be excluded, we can easily get into trouble with licensing. Also I'm not sure whether we have a problem here that needs being addressed. The last obvious example of such files I saw was including tarballs of previous releases into the current release (recursively, i.e. the collection size was growing exponentially over releases because of this), which should be obvious enough as something you shouldn't do without having an explicit rule for it.

**Comment by gotmax23** [comment]
FWIW, I'm fine with editor configs in repositories as long as they don't mess things up for other developers. However, I'd very much like them to be excluded from the built collection artifacts.

**Comment by gundalow** [comment]
I wonder if it this comes back to having different files in the Git repo (available for maintainers) vs installed (as small as possible).

Either way, as you said "unnecessary files" isn't that clear.

**Comment by Andersson007** [comment]
@briantist thanks for bringing this up!

OK, if IDE settings files are located in separate dirs, it seems fine to me.
Anyway, we should change a corresponding statement in at least collection_checklist in [overview](https://github.com/ansible-collections/overview) as one part of it contradicts with the other:
`collection repository should not contain any unnecessary files like, for example, temporary files created by development tools. Temporary files MUST be added to .gitignore.`. I would just remove `, for example, temporary files created by development tools`

**Comment by Andersson007** [comment]
@briantist would you like to submit a PR with your vision? then we could discuss, polish and vote on it

**Comment by briantist** [comment]
Thanks and sorry for the delays, PR is up:
- https://github.com/ansible-collections/overview/pull/215

**Comment by briantist** [comment]
@ssbarnea re: https://github.com/ansible-community/community-topics/discussions/146#discussioncomment-3812618
> DevTools team will be very happy to quickly implement a test in ansible-lint for that, we only need a relatively stable list of banned files, so we do not endup having to patch it every other day. Openstack has one for editor config as they already have a policy to not allow such files to be tracked by git.

You may have interpreted the change the opposite of its intention. We are _not_ excluding editor files, and are changing the wording to clarify that editor configs are not considered temporary files, and that there is no specific restriction to committing them (there is also no explicit allowance, we do have latitude to maybe say that some specific editor config should not be included in a collection, it's case-by-case).

As I looked over what was linked, I realize that my original PR title, `Inclusion: Update wording of temporary files to exclude editor files` was confusing. While I meant "excluding editor files (from being counted as temporary files)", without full context the title sounds like "excluding editor files (from collections)".

I have since updated the title and hope that helps clear things up.

**Comment by gotmax23** [comment]
> @briantist I am concerned about what should go into the packaged collection, not what the author decided to keep on git. I only mentioned the gitignore because the subject was somehow related. I do not see any use for test files, temp, editor config when we create the archive, and that is what we want to check.

I agree. These files should not be included in built collections. They cause issues downstream and clutter user systems. There's another community-topics ticket about this https://github.com/ansible-community/community-topics/issues/126.

**Comment by briantist** [comment]
I see thanks, imo, the discussion about what should or shouldn't go into a packaged collection (built artifact), is a completely separate discussion. It's a fine discussion to have, it's just not related to this at all. The repository already contains files we don't want in the archive; which files to include/exclude and how to do it is worth talking about, but is not related to this scoped discussion about the "temporary files" criterion and whether editor configs count toward that.

As @gotmax23 helpfully pointed out, there is already a discussion for that topic:
- https://github.com/ansible-community/community-topics/issues/126

**Comment by gotmax23** [comment]
> imo, the discussion about what should or shouldn't go into a packaged collection (built artifact), is a completely separate discussion.

I agree. I voted `+1` even though this may result in more unwanted files to collection artifacts, because the two things are orthogonal. Not allowing collection artifacts in repositories at all is the wrong solution to that problem.

**Comment by mariolenz** [comment]
> The vote is in:
> 
> * [[Vote ends on 2022-10-12] Clarify inclusion requirements on temp files and editor configs #146](https://github.com/ansible-community/community-topics/discussions/146)
> 
> All votes are "+1": I count 9 SC votes, and 1 non-SC vote
> 
> Would another SC member like to confirm?

I'm not quite with you, I count 8 x +1 from SC (Andersson007 gotmax23 ssbarnea briantist felixfontein russoz acozine mariolenz) and 2 x +1 from community (lowlydba cybette).

It's still a majority, though.

**Comment by Andersson007** [comment]
@briantist I've merged the PR and the issue got closed automatically. Is it fine or we should open it and discuss anything else related?

**Comment by briantist** [comment]
@Andersson007 I'm fine with keeping it closed, I don't think we lock closed issues here so folks could still comment if they have anything and we could reopen then

**Comment by briantist** [comment]
> > The vote is in:
> > 
> > * [[Vote ends on 2022-10-12] Clarify inclusion requirements on temp files and editor configs #146](https://github.com/ansible-community/community-topics/discussions/146)
> > 
> > All votes are "+1": I count 9 SC votes, and 1 non-SC vote
> > Would another SC member like to confirm?
> 
> I'm not quite with you, I count 8 x +1 from SC (Andersson007 gotmax23 ssbarnea briantist felixfontein russoz acozine mariolenz) and 2 x +1 from community (lowlydba cybette).
> 
> It's still a majority, though.

Ah, I mistakenly counted cybette as a SC member, I guess it's her ansible-community membership that gives her maintainer privileges on the repo. Thank you!
