### ISSUE TITLE
Collection requirements and checklist: add clarifications about info / facts modules

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#14]
Collection requirements and checklist: add clarifications about info / facts modules submitted for inclusion

https://github.com/ansible-collections/overview/pull/169

In essence:
- info / facts modules in collections must be named as `<something>_info / <something>_facts`
- modules do not allow to query information using special `state` option values
- info / facts modules must support `check_mode`

**Comment by felixfontein** [comment]
Has been merged.
