### ISSUE TITLE
Include lowlydba.sqlserver collection in the ansible package (no vote's needed, will get included by default on 2022-10-19 if no objections)

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#149]
### Summary

**No vote is needed**

Include `lowlydba.sqlserver` in the ansible package as there are 2 SC reviews and approvals.

See the [inclusion discussion](https://github.com/ansible-collections/ansible-inclusion/discussions/51).

Will get included by default on **2022-10-19** (See [WF](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#collection-inclusion-requests-workflow)).
If you have some major concerns about the collection, please raise them ASAP.

**Comment by briantist** [comment]
@Andersson007 the inclusion date (2022-08-19) is in the past.

**Comment by Andersson007** [comment]
> @Andersson007 the inclusion date (2022-08-19) is in the past.

@briantist oops, fixed, thanks:)

**Comment by Andersson007** [comment]
Created a PR https://github.com/ansible-community/ansible-build-data/pull/172
