### ISSUE TITLE
[Vote ended on 2022-11-08] Collection Removal Policy: add a paragraph about Collection Requirements violations

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#150]
### Summary

It was discussed in the [community meeting](https://meetbot.fedoraproject.org/ansible-community/2022-10-12/ansible_community_meeting.2022-10-12-18.00.log.html) that we should explicitly include Collection Requirements violations as a reason to remove collections from the package.

Relates to https://github.com/ansible-community/community-topics/issues/148

I created a PR https://github.com/ansible-collections/overview/pull/217 to discuss, polish, merge/reject. Please take a look and comment.

**Comment by maxamillion** [comment]
+1 - I think having advertised clarity here will be beneficial

**Comment by Andersson007** [comment]
> +1 - I think having advertised clarity here will be beneficial

Noticed that I didn't put the vote discussion link here
Here it is https://github.com/ansible-community/community-topics/discussions/158

Thanks:)

**Comment by Andersson007** [comment]
I've counted the vote:
- 7 SC +1 (the quorum is reached)
- 1 community +1

Could anyone please confirm the count?

**Comment by markuman** [comment]
> I've counted the vote:
> 
>     * 7 SC +1 (the quorum is reached)
> 
>     * 1 community +1
> 
> 
> Could anyone please confirm the count?

I've counted the same numbers.

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/overview/pull/217, thanks everyone!

**Comment by gotmax23** [comment]
How should we handle non-compliant collection that we already filed issues against (e.g. the collections that don't tag releases, the ones with failing sanity tests)? Would it make sense to go through those issues and leave comments saying that collections which don't fix the violations in four weeks from now will be subject to removal?

**Comment by Andersson007** [comment]
> How should we handle non-compliant collection that we already filed issues against (e.g. the collections that don't tag releases, the ones with failing sanity tests)? Would it make sense to go through those issues and leave comments saying that collections which don't fix the violations in four weeks from now will be subject to removal?

IMO we should
