### ISSUE TITLE
Document how to run tests with Ansible pre-releases

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#156]
### Summary

Relates to https://github.com/ansible/ansible/issues/72226

Copied from the issue:
```
We are publishing more Ansible RCs than ever before.
Let's capitalize on this and document how we expect Ansible collection maintainers
to install Ansible pre-releases in CI systems and why they might want to do so.
```
See the [full](https://github.com/ansible/ansible/issues/72226) description.

Ideas?

**Comment by felixfontein** [comment]
Is this about **ansible-core** pre-releases, or **Ansible** pre-releases? I would guess the former. In that case, almost all collection CIs I know already test against them, since they use the `stable-2.x` branches instead of installing `ansible-core` from PyPi.

**Comment by Andersson007** [comment]
> Is this about **ansible-core** pre-releases, or **Ansible** pre-releases? I would guess the former. In that case, almost all collection CIs I know already test against them, since they use the `stable-2.x` branches instead of installing `ansible-core` from PyPi.

I asked the same in the issue. and replied the same about **ansible-core**:)
Does it make any sense to test a collection against RC of **Ansible** on the collection's side (or is it possible in general?).

**Comment by gotmax23** [comment]
Ansible (community package) is just a collection of collections so IMO it would only make sense for collections with dependencies on other collections to do this.

**Comment by Andersson007** [comment]
Does anyone know if there's any documentation related to setting up CI (using GHA or AZP)?
I failed to find that in the [collection testing doc page]( https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_testing.html)
Should we add a paragraph describing the GHA and AZP options in detail (including referencing to https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml) to the [doc page](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_testing.html) or maybe there's a better place? (maybe another doc or create a new separate doc?)
Ideas?
IMO it's an important topic which doesn't seem covered but should be

**Comment by felixfontein** [comment]
@Andersson007 the collection template (https://github.com/ansible-collections/collection_template) contains a workflow or GHA. I don't think there is a good template for AZP based CI, probably also because that's kind of special. I'm not sure whether any but a few special collections use that.

Regarding docs, it's probably best to link to the collection template as an example for GHA.

**Comment by mariolenz** [comment]
@Andersson007 Please close this issue if done, or open a new forum topic and then close the issue with a pointer to the new discussion: [Community-topics: Archiving the repo](https://forum.ansible.com/t/4990/8)
