### ISSUE TITLE
What to do with inventory and vault scripts in community.general?

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#16]
During the big content migration from ansible/ansible, quite a few inventory and vault scripts were moved to community.general; see https://github.com/ansible-collections/community.general/tree/main/scripts/inventory and https://github.com/ansible-collections/community.general/tree/main/scripts/vault.

Since inventory and vault scripts are not 1st or even 2nd class citizens of collections, are not related to code in the collection (the only exception being the infoblox script, but the content it uses is now deprecated), have no tests (only sanity tests run on them), and in case of inventory scripts are even discouraged in favor of inventory plugins (which are 1st class citizens of collections), I want to propose the idea to move them to a separate repository (which is not a collection repository).

In most cases, it seems that users download or copy these scripts to where they use them anyway, instead of running them from community.general directly, so IMO there's no reason they should be part of community.general. The only advantage of having them in a collection that's included in Ansible is that if you install Ansible, they are around somewhere in your filesystem (but you have to find them first before you can use them :) ).

What do you think?

**Comment by gundalow** [comment]
Thanks for raising this.

I think there are a few different things we can do here
1. For every inventory script that was in ansible per-ansible-base https://github.com/ansible/ansible/tree/pre-ansible-base/contrib/inventory search for docs pointing to them, including Blogs, docsite, generally. Contact author to point to the plugin version
2. Review the docsite which talks about inventory/vault script/plugins and add big red warning to move to plugins
3. Is this worth a blog post/Reddit stating old-name -> new name?

**Comment by jamescassell** [comment]
IIRC, the benefit of an an inventory script vs plugin is that the script can have any license whereas the plugin must be GPL. Shouldn't affect stuff in c.g, though.

**Comment by felixfontein** [comment]
Decisions from today's meeting:
1. We will move the scripts to https://github.com/ansible-community/contrib-scripts
2. The decision whether the scripts will ship with Ansible 5+ or not will be made later.

**Comment by Akasurde** [comment]
Please **DO NOT** include the following - 

- `vmware.py` is deprecated and has a counterpart `vmware_vm_inventory.py` in community.vmware.
- `ec2.py` is deprecated and has a counterpart `aws_ec2.py` in amazon.aws.
- `infoblox.py` is deprecated and has a counterpart `nios_inventory.py` in infoblox.nios_modules.

**Comment by felixfontein** [comment]
We begin with moving all scripts. Cleanup can come later, but right now the scripts are mentioned by the docsite, so leaving them out will break links.

I added all scripts to https://github.com/ansible-community/contrib-scripts and created https://github.com/ansible-collections/community.general/pull/2696 to remove the scripts from community.general. Next step is to update documentation links.

**Comment by felixfontein** [comment]
@Akasurde only infoblox.py is part of community.general, I don't know where the others live.

**Comment by felixfontein** [comment]
Removal announcement in https://github.com/ansible-collections/community.general/pull/2697.
