### ISSUE TITLE
[associated vote ended on 2023-01-24] Unmaintained collection: community.google

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#160]
### Summary

The [community.google](https://github.com/ansible-collections/community.google) collection looks unmaintained / abandoned to me:

- **the CI has been failing since [Oct 08, 2021](https://github.com/ansible-collections/community.google/actions/runs/1319170565)**
- No reaction on ansible-collections/community.google#18, ansible-collections/community.google#19 and ansible-collections/community.google#20
- no new release since 2 years

**Comment by felixfontein** [comment]
The whole process was written in mind with also community.google, I wonder why we forgot to actually start the process for this earlier :)

**Comment by felixfontein** [comment]
I think we waited long enough and can start voting on this :)

**Comment by mariolenz** [comment]
> I think we waited long enough and can start voting on this :)

I'll create a vote later, and also one for #171

**Comment by mariolenz** [comment]
Vote happens in #181

**Comment by mariolenz** [comment]
I counted votes:
8 x +1 from SC (mariolenz felixfontein russoz Andersson007 markuman acozine gotmax23 briantist)
4 x +1 from community (oraNod maxamillion samccann tima)

Can someone from the Steering Committee confirm?

**Comment by felixfontein** [comment]
I can confirm these numbers.

**Comment by mariolenz** [comment]
In that case the proposal has been accepted and we will announce to remove the collection from Ansible 9.

I will create a PR for ansible-build-data and an announcement for Bullhorn later this day.

Thanks all!

**Comment by mariolenz** [comment]
Closing in favor of https://github.com/ansible-community/ansible-build-data/issues/198.

**Comment by felixfontein** [comment]
Re-opening as Ansible 9.0.0 isn't in feature freeze.

**Comment by felixfontein** [comment]
Ansible 9.0.0 is in feature freeze.
