### ISSUE TITLE
Allow uploading collection "source distributions" to Galaxy

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/community-topics#161]
### Summary

Currently, collection artifacts are built with `ansible-galaxy collection build` and uploaded to Galaxy. While it's possible to exclude files from collection artifacts (`build_ignore` and `manifest`), most collections do not use these and include every single file, whether that's tests, CI configuration, dotfiles, or virtual environments that were in the collection author's dirty git checkout. We have approval from legal to start removing these development files, and we'd like to do so to make collection artifacts smaller and less crufty. However, removing development files has larger ramifications for the Ansible package. For instance, once we remove tests from a collection's Galaxy artifact, they're removed from the Ansible package sdist and we loose the ability to easily run tests for all the collections in the package[^1].

Multiple people have suggested adding support for building and uploading separate collection "source distributions" to Galaxy. As @webknjaz put it, this would mirror the PyPI wheel/sdist split. By having separate source distributions, we could safely remove these development files from Galaxy artifacts without compromising the ability for the Ansible package and other consumers to download the full source. In addition to extra development files not needed at runtime, a collection source distribution would include the galaxy.yml that can be used to rebuild the collection in place of the MANIFEST.json and FILES.json in built collection artifacts.

I'm opening this ticket so the SC can discuss this idea and get input from the community and the Core and Galaxy teams. I know this proposal is non-trivial to implement, but I think it's the best long term solution to this problem.

In the meantime, I'm still planning to add support to antsibull for downloading extra source files from collections' Git repositories as we discussed in the last Community meeting.

[^1]: `antsibull-build` creates the Ansible distribution by downloading and unpackaging collection artifacts from Galaxy.

**Comment by felixfontein** [comment]
Something to note is that currently for quite a few collections, it is not possible to obtain galaxy.yml from the git repo, since parts of it (mostly the version) are only filled in during the build process (for example by Zuul). I hope that no collection currently included in Ansible does even more complex transformations as part of the build process.

**Comment by webknjaz** [comment]
I suppose that an "sdist" collection would have a `galaxy.yml` with the transformations already applied and building a "runtime-only" slim collection out of it would be possible without Git.

**Comment by webknjaz** [comment]
One thing to consider is that the tooling will likely not want to download an artifact in order to determine its type by inspecting the contents for the presence of `galaxy.yml`. Of course, it could pre-fetch the beginning of the archive, just enough to check the file listing as pip does, but still, it's probably not the first thing it should do. The filename will probably need something like an `.src` fragment in the name.

**Comment by felixfontein** [comment]
I would expect the "sdist" to be what the collection looks like directly before `ansible-galaxy collection build` is called, minus files that really don't belong there (the hard part is defining what that exactly means). We want tests and documentation sources etc., but we really do not want stuff like https://github.com/CiscoDevNet/ansible-ucs/tree/master/releases in it.

**Comment by gotmax23** [comment]
> minus files that really don't belong there (the hard part is defining what that exactly means)

`.gitignore` and `.git` should be excluded for sure.

**Comment by Andersson007** [comment]
>For instance, once we remove tests from a collection's Galaxy artifact, they're removed from the Ansible package sdist and we loose the ability to easily run tests for all the collections in the package[1](https://github.com/ansible-community/community-topics/issues/161#user-content-fn-1-31844a3c184842bbdaef9fc24336f850).

The collection requirements currently require only sanity tests to pass and there are no plans to expand the list with unit or integration tests.
Therefore, we need to be able to run only sanity tests, right?
For that, IIRC, we need only ignore-*.txt files.
If I'm correct, wouldn't it be more straightforward to fetch just those files from corresponding repos?

**Comment by mariolenz** [comment]
This issue looks stale. Let's close it and, if you want to discuss this further, open a topic in the [forum](https://forum.ansible.com).

**Comment by felixfontein** [comment]
I've created https://forum.ansible.com/t/allow-uploading-collection-source-distributions-to-galaxy/5735 on the Forum to continue this IMO rather important discussion.
