### ISSUE TITLE
[associated vote ended on 2023-01-16] Unmaintained collection: community.fortios 

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#162]
### Summary

The [community.fortios](https://github.com/ansible-collections/community.fortios) collection looks unmaintained / abandoned to me:

* the last CI run seems to be [10 months old](https://github.com/ansible-collections/community.fortios/actions/runs/1716527273)
* it didn't test against ansible-core > 2.12
* No reaction on ansible-collections/community.fortios#16 or ansible-collections/community.fortios#17
* No release since 1.0.0 nearly 2 years ago

**Comment by felixfontein** [comment]
The only commits in the repo that were not from my side or from the community team were history left-overs from community.network that got copied over when preserving the history.

The only ever interaction with someone else on the repository was https://github.com/ansible-collections/community.fortios/issues/5. While no user interaction can also mean that everything is working fine, I would still consider this collection dead until someone at least mentions that they are using the collection.

**Comment by mariolenz** [comment]
> While no user interaction can also mean that everything is working fine, I would still consider this collection dead until someone at least mentions that they are using the collection.

Maybe someone will do once we've officially deprecated the collection.

**Comment by gotmax23** [comment]
Yeah, this collection doesn't show any signs of life.

**Comment by mariolenz** [comment]
I counted votes:
7 x +1 from SC (felixfontein russoz gotmax23 Andersson007 ssbarnea mariolenz markuman)
2 x +1 from community (maxamillion anweshadas)

Can someone from the Steering Committee confirm?

**Comment by russoz** [comment]
I can confirm the votes from #179 :
7 x +1 from SC (felixfontein russoz gotmax23 Andersson007 ssbarnea mariolenz markuman)
2 x +1 from community (maxamillion anweshadas)

**Comment by mariolenz** [comment]
In that case the proposal has been accepted and we will announce to remove the collection from Ansible 9.

Thanks all!

**Comment by mariolenz** [comment]
Closing in favor of https://github.com/ansible-community/ansible-build-data/issues/196.

**Comment by felixfontein** [comment]
Re-opening as Ansible 9.0.0 isn't in feature freeze.

**Comment by felixfontein** [comment]
Ansible 9.0.0 is in feature freeze.
