### ISSUE TITLE
Include dellemc.unity collection in the ansible package (no vote's needed, will get included by default on 2022-12-16 if no objections)

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#163]
### Summary

IMPORTANT: check the collection version on galaxy is hire than 1.4.1 before creating a PR in ansible-build-data

**No vote is needed**

Include `dellemc.unity` in the ansible package as there are several reviews and approvals.

See the [inclusion discussion](https://github.com/ansible-collections/ansible-inclusion/discussions/32).

Will get included by default on **2022-12-16** (See [WF](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#collection-inclusion-requests-workflow)).
If you have some major concerns about the collection, please raise them ASAP.

**Comment by felixfontein** [comment]
@Andersson007 @mariolenz thanks!
