### ISSUE TITLE
Ansible Community Galaxy next steps

### ISSUE THREAD

**Issue by gundalow** [ansible-community/community-topics#17]
This is a place for non-Reddit users to provide feedback and ask questions on the proposal of moving Community Galaxy (galaxy.ansible.com) to the GalaxyNG codebase.

If you have any feedback on the survey, please leave it here.

* For details see [Reddit post](https://www.reddit.com/r/ansible/comments/na4end/ansible_community_galaxy_next_steps_help_needed/)
* [Survey](https://www.surveymonkey.co.uk/r/2V7ZVK8) Estimated 2 mins to complete

- [X] Initial [Reddit post](https://www.reddit.com/r/ansible/comments/na4end/ansible_community_galaxy_next_steps_help_needed/)
- [X] Draft survey
- [X] Survey [on Reddit](https://www.reddit.com/r/ansible/comments/npvk8f/ansible_galaxyng_roadmap_survey/) 
- [X] Survey on https://galaxy.ansible.com/
- [x] Survey on docs.ansible.com https://github.com/ansible/ansible/pull/74889

**Comment by ghjm** [comment]
Does the new plan preserve the ability to do `ansible-galaxy collection install git+https://github.com/wherever/whatever`?  Or to have `git+` or `type: git` references in a `collections/requirements.yml` used from Tower/AWX?  Will this remain fully supported in the paid product?

**Comment by felixfontein** [comment]
@ghjm the `ansible-galaxy` CLI tool is part of ansible-core and not affected by this change. This issue/discussion is only about https://galaxy.ansible.com/. So both features will remain fully supported in both the open-source version and the paid product (or well, if they ever change or will be removed, that will not be totally unrelated to this discussion :) ).

**Comment by geerlingguy** [comment]
For me the two major show-stoppers that have to be supported are:

  1. `6.3 As a Consumer I can install Role from Galaxy server (ansible-galaxy role install)`: We can't break people's existing playbooks.
  2. `6.4 As an Author I can initiate a Role import from GitHub into Galaxy server (ansible-galaxy role import)`: If a maintained role needs to update something (to fix a bug or for security hotfixes), we should be able to allow that. This would also mean for the thousands of roles that are auto-importing through CI like GitHub Actions, those jobs wouldn't break.

Everything else makes things easier, but the two above are the two that—if not implemented—would probably result in many rants and ragequits. At least from me ;)

**Comment by felixfontein** [comment]
Keeping URLs (https://galaxy.ansible.com/foo/bar) working from current galaxy is also important. I think it's enough to have redirects for all existing content though, and it's not necessary to add similar redirects for new content (after migration).

**Comment by geerlingguy** [comment]
As an example, ideally if I visit https://galaxy.ansible.com/geerlingguy/apache, I would like to still end up on a `geerlingguy.apache` role page.

This could get tricky with regard to collections also being at the root (e.g. is `/geerlingguy/apache` referring to a collection or role?), but maybe there could be logic that checks if there's a collection, if so, go to /collections/geerlingguy/apache, and if not and there's a role, go to /roles/geerlingguy/apache, else 404... something like that). That also brings up issues in terms of how we'd handle migrating from a role to a collection in the same namespace though.

**Comment by gundalow** [comment]
Survey is live https://www.surveymonkey.co.uk/r/2V7ZVK8 Estimated 2 mins to complete
