### ISSUE TITLE
[Vote ended 2022-12-12] Ansible 7 release schedule for holidays

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#170]
### Summary

Since the ansible-core team announced [they will skip the Dec 26/Jan 2 window](https://groups.google.com/g/ansible-devel/c/IQ7VPnw9yS8) due to the holiday season and the next releases will be at the end of January 2023, I suggest to do the same for the community package.

There is now a vote in https://github.com/ansible-community/community-topics/discussions/169 whether to postpone the release or not.

CC @rooftopcellist @anweshadas @Ompragash

**Comment by mariolenz** [comment]
I counted votes:
7 x +1 from SC (mariolenz russoz felixfontein gotmax23 acozine markuman Andersson007)
3 x +1 from community (rooftopcellist oraNod cybette)

**Comment by gotmax23** [comment]
I guess this can be closed. The next ansible-core release will be on 30 January so the next ansible release will be on 31 January. @rooftopcellist, @anweshadas, @Ompragash can you confirm?

**Comment by mariolenz** [comment]
> I can confirm @mariolenz's count

In that case the proposal has been accepted and we will postpone Ansible 7.2.0 until end of January / early February.

I think we should announce this somewhere, maybe on [Ansible Announcements](https://groups.google.com/g/ansible-announce) and / or [Ansible Project](https://groups.google.com/g/ansible-project). Could someone please do this? I suggest something like:

> Ansible Community Holiday Release Schedule Update
> 
> Due to the upcoming holiday season, we will follow the [lead of the ansible-core team](https://groups.google.com/g/ansible-announce/c/KQLshLNLiP0) and will skip the next Ansible release window.
> 
> We will wait for the ansible-core 2.14.2 release, which should happen at the end of January, and will release Ansible 7.2.0 one or two days later.

**Comment by cybette** [comment]
@mariolenz I can do it. Thanks for the suggested message!

**Comment by mariolenz** [comment]
> I guess this issue can be closed. 

Now that it's announced on both [ansible-announce](https://groups.google.com/g/ansible-announce/c/r2MvrvOIcpQ) and [ansible-project](https://groups.google.com/g/ansible-project/c/JkWaWNO6OuY), I think we should close it.
