### ISSUE TITLE
[associated vote ended on 2023-01-26] ansible PyPI description

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/community-topics#173]
### Summary

The ansible PyPI description is missing information about what the ansible package actually is and how it differs from ansible-core.

I've opened a PR (https://github.com/ansible-community/antsibull/pull/474) to enhance it. I'm interested in what you all think of the PR and if you think any other parts can be improved. Ultimately, I'd like to start a vote on this.

**Comment by felixfontein** [comment]
While Ansible 2.9 was still around this was somehow problematic since the description kind of had to match both. Now that Ansible 2.9 is EOL, I think it's OK to adjust it :)

**Comment by felixfontein** [comment]
I've started a vote on merging https://github.com/ansible-community/antsibull/pull/474 as-is, as discussed in today's community meeting: https://github.com/ansible-community/community-topics/discussions/186

**Comment by mariolenz** [comment]
I counted votes:
7 x +1 from SC (felixfontein mariolenz acozine gotmax23 briantist markuman Andersson007)
6 x +1 from community (Landrash Warkdev oraNod lucab85 tima sammccan)

Can someone from the Steering Committee confirm?

**Comment by Andersson007** [comment]
I counted the same numbers as @mariolenz

Nice to see community (non Steering Committee) folks voting!
@Landrash @Warkdev @oraNod @lucab85 @tima @maxamillion @samccann thank you much!
The [Committee](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html) is not limited by number of members, btw, so please go on!

**Comment by felixfontein** [comment]
I've merged https://github.com/ansible-community/antsibull/pull/474, so the first step is done.

Let's maybe keep this oper for a bit of time so that if someone wants to change more of that description, they can suggest/discuss it here.

**Comment by mariolenz** [comment]
> Let's maybe keep this oper for a bit of time so that if someone wants to change more of that description, they can suggest/discuss it here.

@felixfontein We've kept it open for a bit and nobody suggested / discussed any more changes here. Time to close?
