### ISSUE TITLE
[Vote ended on 2023-02-09] Ansible 8 Roadmap planning

### ISSUE THREAD

**Issue by acozine** [ansible-community/community-topics#176]
### Summary

Created https://github.com/ansible/ansible/pull/79598 for Ansible 8 Roadmap. The schedule is partly based on discussions in today's community meeting, but we didn't discuss each and every minor date. I filled out the ones we didn't discuss by following the same schedule pattern as Ansible 7, with reference to the [ansible-core 2.15 release schedule](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_15.html).

Corrections welcome on the ansible/ansible PR, discussion encouraged here.

**Comment by felixfontein** [comment]
We want to wait for feedback from the folks doing the releases in https://github.com/ansible/ansible/pull/79598, and once they say the roadmap looks good, we'll start a vote on it.

**Comment by samccann** [comment]
fwiw it may be another week before we can get that feedback.

**Comment by samccann** [comment]
Of course as soon as I post that last comment, I was proven wrong :-)  The Roadmap has approval from the person doing it so we can proceed with a vote.

**Comment by felixfontein** [comment]
I created a vote in #194 on the current version of the proposal, to end on 2023-02-09 (one day after the contributor summit).

**Comment by felixfontein** [comment]
@ansible-community/steering-committee please do not forget to vote on https://github.com/ansible-community/community-topics/discussions/194, the vote ends **today** and does not have enough SC votes!

**Comment by mariolenz** [comment]
I counted votes:

8 x +1 from SC (felixfontein mariolenz briantist Andersson007 ssbarnea markuman gotmax23 acozine)

2 x +1 from community (rooftopcellist cybette)

Can someone from the Steering Committee confirm?

**Comment by acozine** [comment]
@mariolenz confirmed - all votes were +1
8 from SC
2 from community

**Comment by samccann** [comment]
Roadmape published at https://docs.ansible.com/ansible/devel/roadmap/COLLECTIONS_8.html
