### ISSUE TITLE
Include dellemc.powerflex collection in the ansible package (no vote's needed, will get included by default on 2023-01-12 if no objections)

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#177]
### Summary

**No vote is needed**

Include `dellemc.powerflex` in the ansible package as there are several reviews and approvals.

See the [inclusion discussion](https://github.com/ansible-collections/ansible-inclusion/discussions/33).

Will get included by default on **2023-01-12** (See [WF](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#collection-inclusion-requests-workflow)).
If you have some major concerns about the collection, please raise them ASAP.

**Comment by felixfontein** [comment]
I think we should extend the deadline to at least January 10th, as that increases the chance that folks can take a look at this before the deadline is over.

**Comment by felixfontein** [comment]
(Also the next Ansible release is at the end of January, so this has no impact in which Ansible release it will be included.)

**Comment by mariolenz** [comment]
> I think we should extend the deadline to at least January 10th, as that increases the chance that folks can take a look at this before the deadline is over.
> (Also the next Ansible release is at the end of January, so this has no impact in which Ansible release it will be included.)

Good point, I'll change it.

**Comment by mariolenz** [comment]
Looks like we're agreed to add `dellemc.powerflex`. I've creates ansible-community/ansible-build-data#193 to do this.

**Comment by mariolenz** [comment]
Done in ansible-community/ansible-build-data#193, thanks everyone!
