### ISSUE TITLE
Central Location for Release Blockers

### ISSUE THREAD

**Issue by anweshadas** [ansible-community/community-topics#178]
### Summary

To have a single point of truth for Release blocker information.

We do not have any specific space for to keep track of the Ansible community release blockers. General practice is we do keep our eyes open for the release blockers in ansible-core, ask around in different platforms and individual contributors. It would be good to have a central location for release blockers. Where we would be able to see if there is any blocker for a particular release or not.  
It has been discussed in the Ansible community  working group meeting. And everyone agreed with the general idea. 

We have to decide on the following:

- Where to have the place holder? 
- Fix the definition of a release blockers.

**Comment by felixfontein** [comment]
As for where, I think the best place would be issues (with a special label) in ansible-build-data.

As for a definition, that's more complicated. For me it's more a "I know it when I see it" thing, which isn't a useful definition :) Two things I can think of out of my head are:
- "ansible-core release delayed";
- "an unexpected thing came up (with the new major ansible-core release) that breaks some collections severely, or affects too many of the collections" (this is again kind of "I know it when I see it").

**Comment by Andersson007** [comment]
- I support the idea of labeling + they probably should be added to a [milestone](https://github.com/ansible-community/ansible-build-data/milestones) for a corresponding release
- I'm not sure if we need a formal definition as we'll use the "I know it when I see it" approach anyway when seeing any blocker that doesn't fall under that definition. Or it should be very general like:
```
In the context of the Ansible Community package release workflow,
a release blocker is a situation which does not allow the package to be released.
It might come with a new ansible-core release and affect many of the included collections
or in any other way severe affect consistent work of the package.
Severity of the impact is determined by the Steering Committee in each particular case.
```

**Comment by Andersson007** [comment]
Created a [PR](https://github.com/ansible-community/ansible-build-data/pull/194), please folks take a look

**Comment by felixfontein** [comment]
https://github.com/ansible-community/ansible-build-data/pull/194 is merged, so we have a location and a first definition: https://github.com/ansible-community/ansible-build-data/#blockers

We can improve in particular the definition, so if someone has a concrete proposal... :)

**Comment by anweshadas** [comment]
Since https://github.com/ansible-community/ansible-build-data/pull/194  is merged and solve the initial set of issues closing the PR.
