### ISSUE TITLE
[Vote ended on 2023-01-26] Keep cyberark.pas in Ansible 9?

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#180]
### Summary

In December 2022, we voted to exclude cyberark.pas from Ansible 8 since it appeared unmaintained (#168). When we were counting the votes, someone from Cyberark reached out to us (https://github.com/ansible-community/community-topics/issues/168#issuecomment-1354792453) and promised that there will be more work. Then not much happened until the beginning of this year, but now there has been some progress (https://github.com/cyberark/ansible-security-automation-collection/commits/) and even two releases (https://github.com/cyberark/ansible-security-automation-collection/releases).

The next Ansible release (7.2.0) will happen at the end of this month, so we should discuss whether to continue the removal process (and anounce removal in the 7.2.0 Ansible changelog entry) or whether to stop the process and not remove the collection from Ansible 8.

Please write your comments here, if it looks that at least some of us are in favor of cancelling the removal I'll start a vote on it next week.

**Comment by szh** [comment]
CC @cyberark-bizdev @infamousjoeg @jtuttle

**Comment by infamousjoeg** [comment]
I'll look into getting those added tomorrow. Thanks for the comment!

**Comment by mariolenz** [comment]
It would be great to see cyberark/ansible-security-automation-collection#49 merged and sanity tests succeeding. But since it looks like @infamousjoeg is actively working on this, I tend to stop the removal process.

**Comment by infamousjoeg** [comment]
Sanity checks are passing as of release 1.0.17: https://github.com/cyberark/ansible-security-automation-collection/tree/1.0.17

**Comment by felixfontein** [comment]
As discussed at today's meeting I've started a vote on cancelling the removal process: https://github.com/ansible-community/community-topics/discussions/185

**Comment by mariolenz** [comment]
I counted votes:
7 x +1 from SC (felixfontein mariolenz russoz acozine briantist Andersson007 markuman)
5 x +1 from community (sammccann Warkdev szh hyclak oraNod)

Can someone from the Steering Committee confirm?

**Comment by Andersson007** [comment]
@mariolenz i counted the same numbers!

It's nice to see non-steering committee folks voting there!
If someone is interested in becoming a Committee member, there's [guide](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html).

**Comment by mariolenz** [comment]
> @mariolenz i counted the same numbers!
> 
> It's nice to see non-steering committee folks voting there! If someone is interested in becoming a Committee member, there's [guide](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html).

Then the vote has been accepted.

The collection hasn't been removed from ansible-build-data yet. So I'll close this issue because there's nothing to do except _not_ removing the collection.
