### ISSUE TITLE
Can we create a way to see all 'easyfix' issues across ansible collections and projects?

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-topics#187]
### Summary

This is part discussion, part - is it even possible??

So we have a lot of separate repositories now in Ansible. That makes it harder for new contributors to find an `easyfix` issue across oh 100+ repositories.

So first question - Do we want something like this? A way to 'view' all easyfix across all ansible projects (collections included)?

Second question - Anyone know of a way to do this short of looking at 100 repos for an `easyfix` label and then linking it to some new 'easyfix' github project board? :-)

Third question - Anyone up for creating this?

**Comment by gundalow** [comment]
https://github.com/search?q=user%3Aansible-collections+label%3Aeasyfix&type=Issues&ref=advsearch&l=&l=

**Comment by samccann** [comment]
oh wow.. that was fast!

This is probably something we can add regularly to the bullhorn.  The next question - should we separate collection 'easyfix' from everything else or just use the 2nd search listed above?

**Comment by gundalow** [comment]
I think splitting out by GitHub Org is good.
Brilliant idea to add to Bullhorn

**Comment by Andersson007** [comment]
it could be also `easy_fix` i think. maybe some other options

**Comment by samccann** [comment]
Notes from community WG meeting:
- +1 for adding to Bullhorn - one for ansible GH org and one for the collections GH org
- Also add to the contributor docs on docs.ansible.com

**Comment by samccann** [comment]
@Andersson007 good point!
I played a bit and we have 40 open issues with `easyfix` label (none with hyphen or dash).
We have 82 with `good first issue` label.  So the two searches I'll put in the bullhorn are:

https://github.com/search?q=user%3Aansible+user%3Aansible-community+label%3Aeasyfix%2C%22good+first+issue%22+state%3Aopen&type=Issues (92 across all non-collection projects)

and

https://github.com/search?q=user%3Aansible-collections+label%3Aeasyfix%2C%22good+first+issue%22+state%3Aopen&type=Issues (26 across all ansible-collections )

**Comment by Andersson007** [comment]
Added the refs to contributor docs https://github.com/ansible/ansible/pull/79830

I added the `docs` label to the refs in contributor_path.rst

**Comment by Andersson007** [comment]
Also we could add `docs` containing refs to `docs/docsite/rst/community/documentation_contributions.rst`

**Comment by samccann** [comment]
Thanks @Andersson007 ! Closing this issue as it's all been implemented. Thanks everyone for the help!
