### ISSUE TITLE
Add Matrix shields to READMEs across the Ansible community

### ISSUE THREAD

**Issue by acozine** [ansible-community/community-topics#190]
### Summary

To make it easy for newcomers to join the conversation, our repository READMEs should include badges for Matrix that serve as links to specific chat rooms.

See https://github.com/ansible-community/community-topics/pull/114/files for an example change.

Locations to add the Matrix shield:
- [x] README for [ansible-build-data](https://github.com/ansible-community/ansible-build-data)
- [x] README for [ansible-inclusion](https://github.com/ansible-collections/ansible-inclusion)
- [x] README for [news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers)
- [x] README for [ansible/community](https://github.com/ansible/community/)
- [x] README for antsibull projects
- [x] README for [community.postgresql](https://github.com/ansible-collections/community.postgresql/blob/main/README.md)
- [x] README for [community.mysql](https://github.com/ansible-collections/community.mysql/blob/main/README.md)
- [x] Add info about the shields to community docs on docs.ansible.com https://github.com/ansible/ansible/pull/80392
- [x] please add others here (no suggestions, so marked it as complete)

**Comment by samccann** [comment]
Should we put badges on the 'most logical place' for all our existing matrix rooms?

**Comment by Andersson007** [comment]
BTW the badge code can be simplified a bit:
```
[![](https://img.shields.io/matrix/mysql:ansible.com.svg?server_fqdn=ansible-accounts.ems.host&label=Discuss%20on%20Matrix%20at%20%23mysql:ansible.com&logo=matrix)](https://matrix.to/#/#mysql:ansible.com)
```
