### ISSUE TITLE
How to better coordinate cross-project discussions on our community-topics

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-topics#196]
### Summary

Kind of a meta issue, but most of the people creating community-topics are active in the community chat channels.  This means we may not get visibility from members of other projects impacted by the discussion.

This is a discussion to talk about ways of making that happen.

Some ideas already discussed in the WG meeting:

1. Create team/group aliases in this GH organization so we can selectively @ another group to bring the discussion to their attention.  Would need to create a document to list out how to ping each alias and guidelines on when to do that so it doesn't end up pinging a bunch of people all the time.
2. Controller/AWX and possibly core are considering using ansible/proposals for this sort of decision-making. How to we coordinate with that if it happens?
3. Sometimes it takes a PR to show what is meant in a proposal, but we should set clear expectations that the PR could be rejected.
4. However/wherever we create these proposals, we still need to:
    a: gain buyin from all the other ansible projects
    b: have a common approach to publicizing proposals (in bullhorn etc)
    c: determine a process and governance model - what do we do if 5 teams agree to a proposal and we have one holdout who rejects?

**Comment by Andersson007** [comment]
Maybe out of the topic.
I'm really not sure if it's a good idea to mix AWX/controller and core stuff in one place...
It seems that it's a kind of very different things (of different level i'd say).
Ansible stuff is only a subset of things that form AWX.
Should the questions related to,say, LDAP authentication or WebUI features implementation be mixed in one place with jinja stuff?

I think package-, core- and collection-related discussions suit one place as together core + collections form the Ansible package,i.e. form a complete self-sufficient entity.
People who use Ansible (as users or contributors) in most cases use these components but not necessarily AWX/controller and not necessarily interested in getting AWX stuff to their emails, filter stuff by labels each time or vote on questions they've no idea about).

Also I wonder if the idea of using ansible/proposals was discussed with the community?

**Comment by Andersson007** [comment]
cc @gundalow @GregSutcliffe  ^

**Comment by GregSutcliffe** [comment]
Thanks for raising this - I have thoughts but I'm just about to head out to FOSDEM, so it might be a few days before I write everything up. I'll make this a priority topic in my discussions over the next week and I'll sum up what I hear when I get back.

**Comment by samccann** [comment]
Closing this in favor of the more detail proposal at https://github.com/ansible-community/community-topics/issues/202
