### ISSUE TITLE
Newly submitted collection hpe.nimble uses Apache-2.0 license

### ISSUE THREAD

**Issue by Ompragash** [ansible-community/community-topics#2]
##### SUMMARY

Currently the newly submitted collection hpe.nimble for inclusion uses `Apache-2.0` license which MUST be changed to `GPL v3` as we only allow `GPLv3+` (and optionally BSD-2-clause for module_utils).

**Comment by abadger** [comment]
People were hesitant to allow more licenses without legal approval but also wanted to get this question resolved in time for collections with other licenses to be included for ansible-4.0.  In an attempt to move this forward, I'll make a proposal for next meeting that opens the door partially to other licenses (limited to GPLv3+ compatible licenses and modules).

**Comment by felixfontein** [comment]
(see link in https://meetbot.fedoraproject.org/ansible-community/2021-03-31/ansible_community_meeting.2021-03-31-18.00.html for the log of the discussion)

**Comment by abadger** [comment]
A new interim licensing guideline has been approved that allows GPLv3+ compatible licensing in module and module_utils code.  This should remove the blocker on hpe.nimble's licensing.

Thanks for bringing this issue up!

**Comment by felixfontein** [comment]
I've mentioned the result here: https://github.com/ansible-collections/ansible-inclusion/discussions/13#discussioncomment-581575

**Comment by tadeboro** [comment]
We can probably close this issue since the `hpe.nimble` collection maintainers changed the license of the documentation fragment: https://github.com/hpe-storage/nimble-ansible-modules/pull/39
