### ISSUE TITLE
[associated vote ended on 2023-03-21] Community Plans part 1 - DNS & Website

### ISSUE THREAD

**Issue by GregSutcliffe** [ansible-community/community-topics#201]
### Summary

This is the first discussion space for the community strategy for the year ahead. It's a larger topic than easily fits into a GitHub issue, so rather than summarise it badly here, I'd ask that you read the two posts we've created - [State of the Community 2023](https://ansible.github.io/community/posts/state_of_the_community_2023.html) and [Community Strategy 2023](https://ansible.github.io/community/posts/ansible_community_strategy_2023.html) - before discussing/voting.

---

As promised in the post conclusion, this is the first of two proposals, namely that the community should:
- Define & register a DNS zone for the community to use for all things relating the Ansible **project**
- Create a new website at the root of this zone to serve as a landing page, community voice, and signposting resource for the Ansible community

If approved, the next step would be to form a Working Group to implement both parts.

**Comment by mariolenz** [comment]
It makes perfect sense to me to have a seperate DNS domain as the "home" of the Ansible community. You've suggested `ansible.community` which sounds like a rather good idea.

This would make it easier to distinguish between Ansible-the-Red-Hat-product and Ansible-the-Community. Additionally, it might give the community more freedom on the content and tools hosted there. As you say: `ansible.com` is Red Hat’s product site.

>     * Create a new website at the root of this zone to serve as a landing page, community voice, and signposting resource for the Ansible community

I see a lot of discussions on what content should stay where it is and what content should, at least in the long run, move to the new website (for example [The Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn)). But those would be later steps. Let's start simple.

**Comment by GregSutcliffe** [comment]
Thanks for the positive feedback so far folks. The second recording from Contributor Summit is now up, so I've added to the top of the second post, but for those that have already read them (and are interested) you can find that [here (YouTube)](https://www.youtube.com/watch?v=ezaX-cHlN-g&list=PL0FmYCf7ocrY-uMXYlnbCI2jZz8rDM8zP&index=2]

**Comment by felixfontein** [comment]
:+1: for `ansible.community`.

**Comment by AndreasDavour** [comment]
ansible.community isn't as succinct as ansible.com but it does get the message across. 
![](https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png)

**Comment by chuckmilam** [comment]
I'm old enough to wince a little at these newfangled long TLDs.  However, I agree a good delineation between "Ansible, the Red Hat product" and "Ansible, the community" would be of benefit. 

Therefore, +1 for  `ansible.community`

**Comment by briantist** [comment]
+1 for `ansible.community`

**Comment by jillr** [comment]
+1 for `ansible.community`

**Comment by gotmax23** [comment]
Should we start a vote on this?

**Comment by mariolenz** [comment]
> Should we start a vote on this?

I think so. The reactions have been 100% positive here up until now, at least as far as I can see. Also, people seem to be fine with `ansible.community` (even if some people "wince a little at these newfangled long TLDs" :laughing:). So I suggest to vote on the DNS zone while we're at it, too.

My suggestion for a vote:

```
Register a DNS zone `ansible.community` for the community to use for all things relating the Ansible project. Create a new website at the root of this zone to serve as a landing page for the Ansible community.

Please vote with +1 to do this and -1 to keep things as they are (that is, keep using `ansible.com`).

Please don't use this vote for discussions, use #201 to do this.
```

@gotmax23 If you create a vote, feel free to improve this or to write up something completely new. It's just a suggestion ;-)

**Comment by GregSutcliffe** [comment]
I would agree this seems ready for a vote. It has only been just over a week, and I would normally like to give discussion longer (people can be on holiday, etc) - but given the feedback level so far, it seems uncontroversial to move forward. I can do that tomorrow if no one objects before then.

Thanks to all for the positive feedback - I'm excited :)

**Comment by apple4ever** [comment]
Separate domain for the community would be amazing. Teaching others new to Ansible how to get to it is hard with the current layout, so this would be a big help.

**Comment by GregSutcliffe** [comment]
I see a couple of new points on #208 but discussion lives here, so let me reply with my thinking on this:

> @ssbarnea -1 Im in favour of keeping ansible.com/community, or if there are real limitations using community.ansible.com subdomain instead. Extra domains can cause lots of problems and confusions as anyone can register similar domains.
> @BigPii Prefer community.ansible.com

To the first point, I really don't think a single page (ansible.com/community) gives us the flexibility we're looking for. It could be a landing page, but the hosting as it stands today really doesn't support that well, and *definitely* couldn't have community involvement (if my understanding is correct).

The point about domains causing confusion is valid, but I would argue it applies even for community.ansible.com - once you need people to find a new place, you have a marketing problem no matter what. We'll still need to get the right people to the right place no matter what URL we use. So we can decide between the options without too much concern here, as we have to solve this anyway (likely via redirects and clear links, in both directions)

Also, on the confusion theme, I'd add that a `.com` isn't really the right TLD for an upstream project, and "community.ansible.com" *really* confuses that message. It's an admittedly small point, but I think we should consider it.

To the "anyone can register domains" point - yes, that's true. But those people don't have control of the other places we exist (GitHub, Matrix, etc) which is why part of the proposal is a branding element. We use "Ansible Community" and links to the new DNS **everywhere**, as well as ensuring signposting from ansible.com, to give the new site it's legitimacy. There's a reason it's called the **web** not just a **list** :grin:

**Comment by mariolenz** [comment]
> Also, on the confusion theme, I'd add that a `.com` isn't really the right TLD for an upstream project

Why not? It's about "something with COMputers" so that fits, doesn't it? *SCNR*

**Comment by Landrash** [comment]
+1 for ansible.community

Seems like a good step in the right direction! :)

**Comment by acozine** [comment]
I'm struggling with this a bit. It would push community content off of the "main" domain and give up a lot of accumulated "reputation" (that's not the right word, but it's the only one I'm coming up with at the moment) with search engines - if we move community docs from docs.ansible.com to docs.ansible.community I think things will suddenly get a lot harder to find.

Is RH going to continue to use ansible.com? Last I heard (admittedly a while back) they wanted to move most content to the redhat.com domain. 

I'm fine with giving up www.ansible.com/community and adding that content to www.ansible.community, but moving everything doesn't seem smart unless it's absolutely necessary.

**Comment by samccann** [comment]
Do redirects help with the search reputation? We've done that for individual docs pages on docs.ansible.com, but those where going from docs.ansible.com/foo to docs.ansible.com/bar so to speak, not to a new domain.

**Comment by tima** [comment]
I see your point here about moving the docs domain to the proposed ansible.community.  Let me play devil's advocate here though.

The docs have already moved to a redhat.com domain for customers; however, customers don't realize that. (I can't speak for the marketing of the Ansible product going exclusively to a redhat.com -- I just don't know.) Not realizing that is understandable since docs.ansible.com is what comes up in Google searches and they are hosted under ansible.com with all of the other Red Hat Ansible product marketing and news. It is not very clear that what is on docs.ansible.com are community docs, not product docs since, afterall, it is a dot com domain. So they're are confused because things in the product they are using don't line up. Changing to a domain that says "community" right in the name goes a long way to clarifying this. 

So I think moving to a new domain, even at the expense of search engine reputation, can be really helpful in announcing "this is something really new you should check out."

**Comment by mariolenz** [comment]
@acozine 
> I'm struggling with this a bit. It would push community content off of the "main" domain and give up a lot of accumulated "reputation" (that's not the right word, but it's the only one I'm coming up with at the moment) with search engines - if we move community docs from docs.ansible.com to docs.ansible.community I think things will suddenly get a lot harder to find.

If docs.ansible.com/x/y/z redirects to docs.ansible.community/x/y/z (for example with a `301 Moved Permanently`), I think this won't be a problem. 

> Is RH going to continue to use ansible.com? Last I heard (admittedly a while back) they wanted to move most content to the redhat.com domain.

I don't know about this. Anyway, if this is the case it wouldn't be much difference between moving (some) stuff to redhat.com and moving it to ansible.community, would it?

**Comment by acozine** [comment]
Would docs.ansible.com disappear altogether? And be replaced by docs.ansible.community for upstream docs and somewhere on redhat.com for downstream/product docs? If so, then I'm a little less uneasy.

**Comment by mariolenz** [comment]
> Would docs.ansible.com disappear altogether? And be replaced by docs.ansible.community for upstream docs and somewhere on redhat.com for downstream/product docs? If so, then I'm a little less uneasy.

If we move the upstream docs to docs.ansible.community, we shouldn't really care where Red Hat moves their product docs to IMHO ;-)

**Comment by GregSutcliffe** [comment]
Thanks @acozine, you always give us a good perspective :)

For me this breaks into two parts. If redirects are a blocker, then it's part of "should we do a new site at all" - otherwise, it's implementation detail (a big detail, not wanting to minimize it).

To decide if it's a blocker, I have two thoughts - (1) it must be possible to do this in some sensible form, or you'd just never see companies rebranding due to the SEO hurt, and (2) even if it's not possible, it may be worth the cost (which is @tima's point). Taken together, my gut feel is that this is a solvable issue - even if we can't get it perfect, we can minimize the pain to a point that is acceptable.

Thus it becomes an implementation detail, and then I 100% agree this won't be a day-1 problem. I foresee docs.ansible.com being around for a long time for a bunch of reasons, and we are better served by starting with creating the things we **don't** have today (core static site, blog, etc) than by migrating things that do exist which we can link to for now.

**Comment by saito-hideki** [comment]
+1 for ansible.community :)

I think it would be nice if the ansible.community domain could become a portal for sharing the results of the comprehensive Ansible Project.
Also, it would be very beneficial to the users if the documentation of Ansible Community projects such as ansible-builder, ansible-runnner, etc. could also be provided in docs.ansible.community.

**Comment by mariolenz** [comment]
> The product docs moved some time ago.
> 
> https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3 https://console.redhat.com/ansible/automation-hub/repo/published/cloud/terraform/docs/

@tima This means the docs on `ansible.com` are already upstream and not Ansible-the-Red-Hat-product docs anymore, right?

**Comment by tima** [comment]
Mostly. On further review there are a few thing that *should* have moved, but have not made it. The intent is for all product docs to be in access.redhat.com and content available in automation hub. I'm going to see what can be done here to finish the job. Right now I would suggest that this effort not be too concerned about continuing to maintain this dual role at the expense of the needs of upstream (community) documentation and website.

**Comment by mariolenz** [comment]
I counted votes:

7 x +1 from SC (mariolenz gotmax23 Andersson007 felixfontein briantist markuman acozine)

1 x -1 from SC (ssbarnea)

12 x +1 from community (jillr chuckmilam tremble rooso AndreasDavour apple4ever cybette Landrash tima samccann saito-hideki chofstede)

1 x -1 from community (BigPii)

Can someone from the Steering Committee confirm?

**Comment by Andersson007** [comment]
counted the same numbers. So i confirm

**Comment by GregSutcliffe** [comment]
Thanks everyone! We'll get to work on creating the Working Group for this, stay tuned for details!

**Comment by felixfontein** [comment]
Awesome! Also thank you very much @wbentley15 and everyone else involved in this :)

**Comment by andreasscherbaum** [comment]
> we **are** going to get ansible.com back for the community

That is indeed a very good outcome!

**Comment by GregSutcliffe** [comment]
We've reached October, which was our original forecast for the switchover - sadly, that's not going to happen. The new site is largely complete, but the migration of content from the old site isn't finished yet. I'm told it should be done by the end of the year, which hopefully means this will be too - but certainly I'd expect to be switched over by FOSDEM (early February).

Hang in there folks, and prepare your blog post PRs ;)

**Comment by mariolenz** [comment]
@GregSutcliffe Is this something we should close, move to the forum or keep open?
