### ISSUE TITLE
Galaxy time out issues and failures to resolve a module or action.

### ISSUE THREAD

**Issue by konstruktoid** [ansible-community/community-topics#206]
### Summary

It seems Ansible Galaxy has gotten more and more unstable, and GitHub Actions sometimes requires a rerun due to read operation timeouts or failure to resolve a module or action.

Log examples:
https://github.com/ansible-community/molecule-plugins/actions/runs/3960622725/jobs/6785032673#step:6:177
https://github.com/ansible-community/molecule-plugins/actions/runs/4263114886/jobs/7453604089#step:6:187
https://github.com/konstruktoid/ansible-role-docker-rootless/actions/runs/4142801138/jobs/7163902114#step:4:16
https://github.com/konstruktoid/ansible-role-docker-rootless/actions/runs/4142782844/jobs/7163862286#step:4:16

Related: https://issues.redhat.com/browse/AAP-9595

**Comment by konstruktoid** [comment]
A cache when using GitHub actions would probably be beneficial to minimise the number of connections required when installing required collections.

**Comment by felixfontein** [comment]
Earlier discussions about this (in the Galaxy repository):
- https://github.com/ansible/galaxy/issues/2302
- https://github.com/ansible/galaxy/issues/3086

CC @jctanner

**Comment by dlouzan** [comment]
We have a bunch of molecule testing pipelines that pull the dependencies from galaxy when the pipeline starts, and the downloads and galaxy api access has been really flaky for the last week or so. More than 50% of our pipelines fail with download timeouts.

**Comment by apatard** [comment]
the problem is not only about a cache, but also to fill it. I've been seeing the issue with molecule-plugins and the failure rate is near to 100%

Moreover, if the cache solution is choosen, this would possibly mean updating all repos in the wild to use it. A "generic" solution would be nice imho.

tbh, I've even been wondering about sending a PR to clone git repos with ansible-galaxy instead of going through galaxy site but I fear it may end up being yet an other can of worms...

**Comment by zhan9san** [comment]
How about installing them from git repo?

https://galaxy.ansible.com/docs/using/installing.html#role-versions

**Comment by nejch** [comment]
> How about installing them from git repo?
> 
> https://galaxy.ansible.com/docs/using/installing.html#role-versions

@zhan9san does that really solve the problem of transitive dependencies in roles and collections though?

If the dependency has its own galaxy dependencies defined in `galaxy.yml` or `meta/main.yml`, it'll still have to talk to the Galaxy API I assume.

We've tried the `120` timeout and that helps but is still flaky. https://github.com/pycontribs/pia might help a it on the client side, but this won't be used by molecule etc any time soon I'd say.

**Comment by konstruktoid** [comment]
https://github.com/konstruktoid/ansible-role-docker-rootless/actions/runs/4377846073/jobs/7672885557
![image](https://user-images.githubusercontent.com/7956715/224278353-4ba417ec-e86b-4331-9c5c-1e00e5745702.png)

**Comment by nejch** [comment]
> As there is no ETA of galaxy timeout issue, if we are still waiting for that, the CI won' t work, which would make PR review hard.
> 
> To break the deadlock, we can put the in-direct and direct  dependencies into different files and both of them use github repo as the alternative, and then we can install them  in CI jobs.
> 
> Once the galaxy is back, we can revert them back.
> 
> I'm looking forward to your suggestions.
> 

I'm not sure you can prevent galaxy from trying to resolve indirect dependencies defined upstream.

In any case, I'm also not sure this would be a good workaround for our use case where we distribute a collection or role to end users but also depend on external dependencies ourselves, it would get a bit messy IMO.

**Comment by mariolenz** [comment]
There hasn't been any activity here for a year. If this is still an issue (which I don't think) or if the issue turns up again, please open a topic in the [forum](https://forum.ansible.com) and let's discuss it there.
