### ISSUE TITLE
[associated vote ended on 2023-03-30] Static site generator for the Ansible community web presence

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-topics#210]
### Summary

The Ansible community is requested to provide input on requirements and options for a static site generator that will create a new Ansible community site and Ansible community documentation navigation should the Ansible community be in favour of those efforts.

### Additional Information

Here is the initial list of requirements and things that would be nice to have. We can evaluate SSG options against this list:

Requirements:

- [ ] Ease of deployment (fast to build html, can put into gh action, low risk of breakage when upgrading)
- [ ] Custom landing page (ability to create landing page that is not "documentation layout")
- [ ] Base templates and themes for rapid prototyping
- [ ] Easily add custom css when required but low requirement for theme customization, built-in cross-browser compatibility and responsive design
- [ ] Write content in md or rst
- [ ] Button to edit pages directly
- [ ] Blog capabilities
- [ ] Basic search functionality
- [ ] Well maintained project with recent commits
- [ ] i18n (content renders correctly for everyone)
- [ ] Media support (embedding YouTube videos)

Nice to have:

- [ ] Python extensibility / integration
- [ ] Ability to extend templates and themes with Jinja

**Comment by oraNod** [comment]
Options for static site generators so far:

- https://getnikola.com/
- https://squidfunk.github.io/mkdocs-material/
- https://www.getlektor.com/
- https://hyde.github.io/
- https://getpelican.com/

**Comment by leogallego** [comment]
@oraNod is the "web ui for content generation" included in the "cms" concept? 
I would like to add that to the nice-to-have if possible!

**Comment by mariolenz** [comment]
I don't know _anything_ about static site generators... but doesn't [antsibull-docs](https://github.com/ansible-community/antsibull-docs) already use sphinx? If it fulfills the requirements (and maybe even the nice-to-haves) maybe that would be a reason to use it for the new Ansible community site?

Just an idea. As I've said, this isn't really my area of expertise.

**Comment by gotmax23** [comment]
Hugo is written in Go instead of Python, but it's also a good choice and has a strong community surrounding it.

**Comment by gotmax23** [comment]
I don't think mkdocs or Sphinx are good choices for a landing page. They're meant for documentation, and we already have a docsite.

**Comment by oraNod** [comment]
> 

@mariolenz Yes I think Sphinx is a pretty solid choice because it has a lot of mindshare/adoption already. I'm not 100% on how well it does general sites, even though I'm pretty sure it has that capability.

**Comment by oraNod** [comment]
> Hugo is written in Go instead of Python, but it's also a good choice and has a strong community surrounding it.

@gotmax23 I can add Hugo to the list. I don't think it will have the "mindshare" with the community though. For instance I didn't include Jekyll as an SSG option because Ruby just wouldn't be a popular choice.

**Comment by oraNod** [comment]
@mscherer Thank you so much for those valuable insights. I feel like there are a lot of things we can learn from the Fedora community here and you've raised a lot of points already that I'm not sure we've fully considered. Let me ask folks on the Ansible community team here but I think we should definitely meet with some of the Fedora folks about the experiences so we can bring those things over to this effort.

**Comment by ssbarnea** [comment]
@gotmax23 Take a look at Material landing page from https://squidfunk.github.io/mkdocs-material/ which does not really look as a "documentation landing" page. AFAIK, mkdocs-material can be used to also create custom landing pages.

**Comment by oraNod** [comment]
@gotmax23 Here is an assessment on Hugo. Would you mind taking a look and seeing if there are any points you disagree with?

Hugo is kind of the Ferrari of static site generators. It lets you build modern, SEO-friendly, and secure websites quickly and offers a lot of great features (like mermaidJS support). Hugo can build really great websites, like Manjaro Linux https://manjaro.org/ and LetsEncrypt https://letsencrypt.org/

On the other hand Hugo is written in Go and relies heavily on JavaScript. For the Ansible community site Hugo feels a bit like "outsider" technology that might present a barrier for engagement. Because the underlying tech stack is not the typical first choice for the Ansible community, Hugo would actually be a more complex option even though it offers a lot of flexibility and powerful tooling. That complexity could make it harder to change to a different static site generator after the community website starts to mature or for longer-term maintainability.

Requirements:

- [X] Ease of deployment - Hugo is super fast and easy to deploy https://gohugo.io/hosting-and-deployment/

- [X] Custom landing page (ability to create landing page that is not "documentation layout")

- [X] Base templates and themes for rapid prototyping - Base Go templates are available: https://gohugo.io/templates/homepage/ Loads of modern themes to choose from: https://themes.gohugo.io/ -- There's also the starter kits: https://gohugo.io/tools/starter-kits/

- [X] Easily add custom css when required but low requirement for theme customization, built-in cross-browser compatibility and responsive design

- [ ] Write content in md or rst - Hugo is MD only.

- [X] Button to edit pages directly 

- [X] Blog capabilities - Requires separate blogging tools such as https://buttercms.com/hugo-blog-engine/

- [X] Basic search functionality - Plenty of search toolsd https://gohugo.io/tools/search/

- [X] Well maintained project with recent commits - Hugo has been under active development since 2014. There is a sizeable community around Hugo. You can see a lot of the discussion here: https://discourse.gohugo.io/

- [X] i18n - "Polyglot is baked in" https://gohugo.io/content-management/multilingual/

- [X] Media support (embedding YouTube videos)

Nice to have:

- [ ] Python extensibility / integration
- [ ] Mindshare within the broader Ansible community
- [ ] Ability to extend templates and themes with Jinja - Hugo only uses Go templates.

**Comment by oraNod** [comment]
MkDocs seems like a mixed bag. MkDocs itself is simple and straightforward, although it does not seem to be under as much active dev as other options.

The real option under consideration here is the material theme for MkDocs. Even the Ansible community theme for MkDocs is based on the material theme. In this regard MkDocs feels like a constrained choice that might limit the ability to adapt and build different layouts. This is especially true considering the fact that, like Sphinx, MkDocs is intended more for documentation projects than full websites.

Requirements:

- [X] Ease of deployment - https://www.mkdocs.org/user-guide/deploying-your-docs/
- [X] Custom landing page (ability to create landing page that is not "documentation layout") - Possible to remove the TOC with https://github.com/squidfunk/mkdocs-material/issues/478#issuecomment-1422375863
- [X] Base templates and themes for rapid prototyping
- [ ] Easily add custom css when required but low requirement for theme customization, built-in cross-browser compatibility and responsive design

Easy to add custom styling: https://www.mkdocs.org/user-guide/customizing-your-theme/#using-the-docs_dir - For the material theme: https://squidfunk.github.io/mkdocs-material/customization/#additional-stylesheets

The Ansible community theme is built on the material theme and provides a good starting point but has a high overhead for customization, especially considering more complex formats and templates beyond a documentation project.

- [ ] Write content in md or rst - Supports MD only
- [X] Button to edit pages directly
- [X] Blog capabilities
- [X] Basic search functionality
- [ ] Well maintained project with recent commits

https://github.com/mkdocs/mkdocs - It looks like there are no commits since November. However the material theme has more active contributors than MkDocs itself: https://github.com/squidfunk/mkdocs-material

The Ansible community theme has one contributor at the moment (yay, Sorin!): https://github.com/ansible/mkdocs-ansible

- [X] i18n (content renders correctly for everyone) - Requires third-party plugin for site content but themes are https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/
- [X] Media support (embedding YouTube videos) - Can use the `video` tag directly in Markdown.

Nice to have:

- [X] Python extensibility / integration - MkDocs uses a Python stack
- [X] Mindshare within the broader Ansible community - Several Ansible projects already use MkDocs, including Dev Tools and Galaxy NG.
- [X] Ability to extend templates and themes with Jinja - MkDocs uses Jinja as the template engine

**Comment by oraNod** [comment]
Lektor offers the ability to model content and explicitly define the structure of the website. In this way it is convenient for separating content from layout.

Lektor makes it easy to get a site up and running quickly but the general lack of themes and basic default styles necessitates more UX work than other static site generators.

Requirements:

- [X] Ease of deployment - https://www.getlektor.com/docs/deployment/
- [X] Custom landing page (ability to create landing page that is not "documentation layout")
- [ ] Base templates and themes for rapid prototyping - Theme support is new and unstable: https://www.getlektor.com/docs/themes/ - There are not many themes available: https://github.com/lektor/lektor-themes
- [ ] Easily add custom css when required but low requirement for theme customization, built-in cross-browser compatibility and responsive design
- [X] Write content in md or rst
- [ ] Button to edit pages directly
- [X] Blog capabilities - https://www.getlektor.com/docs/guides/blog/
- [X] Basic search functionality - Google search plugin, granted that some other search engine might be preferable https://www.getlektor.com/plugins/lektor-google-search/
- [X] Well maintained project with recent commits - https://github.com/lektor/lektor
- [X] i18n (content renders correctly for everyone) - https://www.getlektor.com/plugins/lektor-i18n/
- [X] Media support (embedding YouTube videos)

Nice to have:

- [X] Python extensibility / integration - Written in Python and provides an API
- [X] Mindshare within the broader Ansible community - There is some awareness of Lektor but it is not widely used. However the familiarity of Python and Jinja would make it easy to adopt.
- [X] Ability to extend templates and themes with Jinja

**Comment by cybette** [comment]
I don't have a strong preference on any of the above, partly because I don't have experience with them. I have used Middleman, Jekyll, and Hyde (in addition to Wordpress and Hubspot which are not SSGs) and dislike all of them :sweat_smile: 

I might try out a couple of them over the weekend to get a feel, but I trust the other experts here to select one that's most suitable for the community's needs.

**Comment by webknjaz** [comment]
My personal preference is Lektor because I worked with it and it's heavily customizable. It was initially written by the creator of Jinja and Flask. It's a bit like a CMS really that generates content that can be served statically.

@oraNod 

> * [ ]  Base templates and themes for rapid prototyping - Theme support is new and unstable: https://www.getlektor.com/docs/themes/ - There are not many themes available: https://github.com/lektor/lektor-themes

I'm not sure what you mean by these but IMO for this type of task, we don't really need to rely on third-party themes and would need to make our own.

> * [ ]  Easily add custom css when required but low requirement for theme customization, built-in cross-browser compatibility and responsive design

There's plugins integrating stuff like webpack and scss — I imagine they take care of this. Although, I'd go for a CSS framework like Tailwind that effectively makes this requirement irrelevant.

> * [ ]  Button to edit pages directly

Not sure what you mean by this. In local dev mode, there's an edit button that takes you to the admin view. I think it works regardless of the theme...

> * [x]  Basic search functionality - Google search plugin, granted that some other search engine might be preferable https://www.getlektor.com/plugins/lektor-google-search/

Looks like there's also a plugin for static search at https://github.com/rlaverde/lektor-static-search.

**Comment by oraNod** [comment]
@webknjaz Thanks! I agree Lektor is a great choice and I really like several aspects of it, especially the models. However I've started to wonder if it's the right tool for getting the Ansible community site off the ground. If it turns out that is not the case I think we should keep evaluating Lektor with a view to switching over if that serves any particular longer-term needs better.

> I'm not sure what you mean by these but IMO for this type of task, we don't really need to rely on third-party themes and would need to make our own.

I agree to an extent but the community team has taken some lessons about ux from the prototype docsite. It's important that the initial effort have good ux from the very start. Until we get a bit more help with ux there is a need to be cautious and avoid too many design flaws.

**Comment by samccann** [comment]
@felixfontein - the bit about 'mindshare with the broader Ansible community' to me means - pick an SSG that multiple people in community would feel comfortable with and willing to assist in creating and maintaining the new website. This from the start is meant to be a community website for and by the Ansible community.

**Comment by samccann** [comment]
Coming at this as a novice and reading the discussion, seems Nikola and Lecktor both have that critical mindshare with community members and the important features we're looking for.

**Comment by samccann** [comment]
I ran an accessibility check on the lecktor and Nikola websites, just for fun. They both have similar number of identified issues and score overall... and both a better scores than Ansible.com today so.. taking that as win :-)

--and yep, realize our own website will have to take steps to be accessible, but thought it was an interesting datapoint anyway.

**Comment by gotmax23** [comment]
A vote was started in https://github.com/ansible-community/community-topics/discussions/216 about whether to move forward with Nikola as the static site generator for the first iteration.

**Comment by GregSutcliffe** [comment]
Coming in late to this one, but I have no bombshells to drop :)

A couple of general comments first
- @oraNod I wouldn't worry about "Discourse integration" or "analytics" too much. In both cases it's *highly* likely to be a JavaScript chunk that gets added to the appropriate part of the layout files, and I don't see any entry on this list that couldn't handle that. Here's [the block that handles comments on TheForeman's blog](https://github.com/theforeman/theforeman.org/blob/gh-pages/_layouts/post.html#L53-L62)
- @mscherer completely agree with focusing on one thing at a time - building the **new** thing has the priority, we can link to existing stuff for now and look at that later
- @samccann thanks for that - I'm with Mike Hoye (of Mozilla) on accessibility, we do it for a small group and it ends up benefiting many many more people (see the latter half of [this blog](https://exple.tive.org/blarg/2019/05/03/goals-and-constraints/) for examples). Let's make that a priority

As to the actual choice, reading through the comments, it seems like any of these could do the job, and we're down to personal preference. On that basis I *could* vote for Hugo (since I use that for my site) but I don't want to cause [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding), so I'll jump on the Nikola train so that we can get started actually building this thing. It gets plus-points because (as an ex-physicist myself) Tesla is a personal hero anyway :)

**Comment by samccann** [comment]
Thanks everyone! Closing this now as the nikola scaffolding is in place with https://github.com/ansible-community/community-website/pull/28
