### ISSUE TITLE
[Vote ends on 2023-03-30] Adopting Nikola as the static site generator for the first iteration of the Ansible community web presence

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-topics#214]
### Summary

This proposal is to adopt Nikola (https://getnikola.com/) as the static site generator to build and deploy the Ansible community website. After discussion and careful consideration the Ansible community team suggests that Nikola is the best choice for the initial launch and early development of the Ansible community website. 

This vote does not result in a permanent decision regarding the tooling. The Ansible community should continually assess needs and evaluate options. If we determine at a future stage that another SSG offers more options or better functionality then we should be able to replace the underlying SSG without much difficulty.

Please vote with +1 / -1 to indicate preference for using Nikola.

### Additional Information

Please refer to this topic for more discussion as well as details about the static site generators brought forward for consideration from the community: https://github.com/ansible-community/community-topics/issues/210

**Comment by cybette** [comment]
+1

**Comment by anweshadas** [comment]
+1
