### ISSUE TITLE
Enforce collection tagging policy as a release blocker

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/community-topics#218]
### Summary

Last year in https://github.com/ansible-community/community-topics/issues/148, we agreed that all collections must tag their releases in their git repository and clarified the [Repository management](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#repository-management) section of the Collection Requirements.

I also enabled support in antsibull to ensure that collections follow the policy with the `antsibull-build validate-tags` subcommand (https://github.com/ansible-community/antsibull/commit/b38fd8bd75690b44e20070ca50e1bc85503e07a8), include a yaml tag data file in ansible-build-data and the ansible sdist (https://github.com/ansible-community/antsibull/commit/5d39db6407f4318cacde41c7f3d879be9fe9f541), and finally added support to the `validate-tags` subcommand to ignore specific collections when reporting errors (https://github.com/ansible-community/antsibull/commit/015f935295c5ff08677ed8456af721265847258a).

Now that we have the last change which allows us to ignore certain collections such as cisco.nso that have been removed for not fixing this issue, I'd like to make improperly tagged collections a release blocker. Noncompliant collections would fail the release playbook, we'd have to pin them to the last release, and we'd have to file issues against the collections' respective repositories. What do other SC members and the release engineers (/cc @ansible-community/release-managers @rooftopcellist) think? I would document the new process in the ansible-build-data repository[^1], add a list of collections to ignore, and update the release playbook to fail on tag validation errors for new ansible versions.

[^1]: or wherever else this should be documented. In general, I'd like to clarify the documentation about the release process, especially with https://github.com/ansible-community/community-team/issues/160 being considered, but I disgress...

**Comment by gotmax23** [comment]
I've tagged this for the next meeting

**Comment by anweshadas** [comment]
+1 from me for the idea. But it would be good if we have some practical examples of pinning, flagging and opening issue  in the collection repo. A good  and up to date documentation hopefully will solve the majority of the problem in here.  Also we have to make sure the collection maintainers understands this step properly.

**Comment by gotmax23** [comment]
In the meeting, we discussed adding a rule to the Collection Requirements that collections MUST NOT require contributors to sign CLAs other than the DCO.

**Comment by acozine** [comment]
Agreed that we should have documentation of the entire release process. However, that may take some time to create.

As a temporary stop-gap, we could add documentation about the tagging policy discussed here to the docs at: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#collections-requirements.

**Comment by acozine** [comment]
Related? https://github.com/ansible-community/nightly-builds

**Comment by mariolenz** [comment]
I think we're already doing this (see ansible-community/ansible-build-data#365 for an example).

If there's more to discuss, please open a topic in the [forum](https://forum.ansible.com).
