### ISSUE TITLE
Why does mssql_script bury its results inside 3 lists?

### ISSUE THREAD

**Issue by greenseeker** [ansible-community/community-topics#219]
### Summary

If I run a query that returns a single column of a single record -- let's say 53 -- the result is...
```
[
        [
            [
                [
                    53
                ]
            ]
        ]
    ]
```

This means I have to use `output.query_results[0][0][0][0]` to refer to that value. Why all the nesting?

**Comment by felixfontein** [comment]
Please open an issue in the collection containing mssql_script (community.general): https://github.com/ansible-collections/community.general/
Thanks.
