### ISSUE TITLE
Deprecation and removal schedule for community.kubernetes

### ISSUE THREAD

**Issue by gravesm** [ansible-community/community-topics#22]
### Summary

The 2.0 release of community.kubernetes will contain only redirects to kubernetes.core 2.0 with the intention of ultimately retiring the community.kubernetes name. We would like to figure out a reasonable schedule for deprecating and removing community.kubernetes. See https://github.com/ansible-community/community-topics/issues/21#issuecomment-859899842 for some more information.

**Comment by tadeboro** [comment]
I think deprecation should happen at the same time as the content move. Having six months in between move and deprecation just sounds like an additional maintenance burden for very little benefit.

**Comment by felixfontein** [comment]
We agreed to:
1. add a deprecation changelog fragment to the next 4.x.0 release (@felixfontein);
2. release community.kubernetes 2.0.0 with deprecated redirects and include it in Ansible 5 (@gravesm);
3. remove community.kubernetes from Ansible 6 or later

**Comment by felixfontein** [comment]
PR for changelog entry: https://github.com/ansible-community/ansible-build-data/pull/68

**Comment by felixfontein** [comment]
FYI: I started a vote on removing community.kubernetes from Ansible 6 or 7 in #93.

**Comment by felixfontein** [comment]
Removal is being implemented in https://github.com/ansible-community/ansible-build-data/pull/116.
