### ISSUE TITLE
[associated vote ended on 2023-08-30] Consider requiring that collections don't require CLAs

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/community-topics#221]
### Summary

In the meeting, we discussed adding a rule to the Collection Requirements that collections included in the ansible package MUST NOT require contributors to sign CLAs other than the DCO. This would definitely apply to new collections. grafana.grafana is the only collection in the ansible package that I know has a CLA requirement. There may be others. I propose working with these collections drop their CLAs or switch to the DCO, but not removing them if they don't.

**Comment by felixfontein** [comment]
I am for requiruing new collections in Ansible to not require a CLA or something similar. I'm fine with an excemption for the DCO.

**Comment by samccann** [comment]
Seems like this means we have to start the deprecation process for community.grafana if it's slipping into the unmaintained status?

**Comment by samccann** [comment]
Agree. This CLA experience suggests we want to prevent this reoccurring in any future collections.

**Comment by samccann** [comment]
Some notes from the community WG meeting:

here is what's written in Red Hat's open source participation guidelines

> Red Hat-led projects do not use contributor license agreements (CLAs), copyright assignment, or other formal contributor agreements, apart from rare exceptions specifically approved by Red Hat Legal. We have learned from experience that these mechanisms can be a significant barrier to building communities around the projects we sponsor. However, we encourage all Red Hat-led projects to use the DCO.

We have at least two more collections with CLAs already.

Things to consider:
- what's the impact on Ansible package users if we exclude future collections with CLAs?
- what's the impact on contributors if we allow CLAs?  This goes deeper in the sense of what is the impact if a new to ansible contributor hits one of these CLAs and decides to not come back to Ansible projects at all because they assume all have CLAs?

**Comment by gotmax23** [comment]
https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license is exactly why I want us to have a requirements like this against CLAs. When I have a chance, I'll propose a Collection Requirements PR.

**Comment by gotmax23** [comment]
I've submitted https://github.com/ansible/ansible-documentation/pull/288.

**Comment by gotmax23** [comment]
Current collections that require CLAs:

- grafana.grafana
- netapp_eseries.santricity

I guess we can add an explicit "this doesn't apply to existing collections" provision.

**Comment by gotmax23** [comment]
Please vote in https://github.com/ansible-community/community-topics/discussions/269.

**Comment by gotmax23** [comment]
I can confirm that count. Thanks @mariolenz for tallying the votes and thanks everyone who participated!
