### ISSUE TITLE
[Associated vote ended on 2023-06-07] Ansible 9 roadmap planning

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-topics#222]
### Summary

The core 2.16 dates are available so it's time to plan the dates for the Ansible 9 roadmap. See [this issue ](https://github.com/ansible/ansible/issues/80481)for some background.

**Comment by felixfontein** [comment]
Since we don't have a roadmap for Ansible 9 yet, I think this should stay open.

**Comment by samccann** [comment]
We're also proposing to include the proposed [collection removals](https://github.com/ansible-community/ansible-build-data/milestone/3) in the roadmap.

**Comment by felixfontein** [comment]
I created a proposal at https://github.com/ansible/ansible/pull/80851.

**Comment by felixfontein** [comment]
@anweshadas please take a look at the proposal.

Everyone: please also take a look. If there are no requests for changes in, say, a week, I'll create a vote for this.

**Comment by felixfontein** [comment]
I've added some formulation improvements to the PR. If nobody objects, I'll start a formal vote on accepting the proposal beginning of next week.

**Comment by mariolenz** [comment]
@felixfontein I don't really object, but what do you think about [my comment](https://github.com/ansible/ansible/pull/80851#discussion_r1207000214) to make clear that we consider new collections as a new feature?

Apart from this, your proposal LGTM :-)

**Comment by felixfontein** [comment]
There is now an **active vote** until June 7th, 2023, in #233. Please vote there by writing a comment with `+1` or `-1`!

**Comment by mariolenz** [comment]
> There is now an **active vote** until June 7th, 2023, in #233. Please vote there by writing a comment with `+1` or `-1`!

I counted votes:

7 x +1 from SC (felixfontein Andersson007 acozine mariolenz markuman russoz briantist)
3 x +1 from community (samccann leogallego cybette)

Can someone from the Steering Committee confirm?

**Comment by felixfontein** [comment]
I can confirm the numbers (7x +1 from SC, 3x +1 from community). So this has been accepted! I'll mark the PR as ready.
