### ISSUE TITLE
[associated vote ended on 2023-05-26] Unmaintained collection: netapp.aws

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#223]
### Summary

The [netapp.aws](https://github.com/ansible-collections/netapp.aws) collection looks unmaintained / abandoned, it has:

* no new commits since September 2022
* no release on Galaxy since version 21.7.0 over one year ago
* last CI run has been [5 months ago](https://github.com/ansible-collections/netapp.aws/actions/runs/3454099299)
* no testing with 2.14
* no reaction on ansible-collections/netapp.aws#7

**Comment by mariolenz** [comment]
I counted votes:

7 x +1 from SC (mariolenz ssbarnea gotmax23 felixfontein russoz Andersson007 markuman)
3 x +1 from community (cybette maxamillion jillr)

Can someone from the Steering Committee confirm?

**Comment by felixfontein** [comment]
This collection had a new release in September, but that release wasn't tagged (https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-1732932405). There has been no reaction so far in the corresponding issue in the repository either (https://github.com/ansible-collections/netapp.aws/issues/8).

**Comment by mariolenz** [comment]
IIRC we've kept issues like this one about collection removal from version X open until X has been released. However, since we've moved discussions to the [forum](https://forum.ansible.com) and the collection has been removed from 10.0.0.a1, I think we should close this even if 10.0.0 hasn't been released yet.

If someone wants to discuss cancelling the removal / re-adding of the collection, please open a topic in the forum.
