### ISSUE TITLE
[Associated vote ended on 2023-06-20] Unmaintained collection: gluster.gluster

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#225]
### Summary

The [gluster.gluster](https://github.com/gluster/gluster-ansible-collection) collection looks unmaintained / abandoned, it has:

* no new commits since September 2021
* no release on Galaxy since version 1.0.2 two years ago
* no CI runs, at least not using [GitHub action](https://github.com/gluster/gluster-ansible-collection/actions)
* no reaction on gluster/gluster-ansible-collection#30

**Comment by mariolenz** [comment]
I counted votes:

7 x +1 from SC (mariolenz gotmax23 felixfontein markuman briantist russoz Andersson007)
1 x +1 from community (cybette)

Can someone from the @ansible-community/steering-committee confirm?

**Comment by Andersson007** [comment]
@mariolenz counted same numbers

**Comment by mariolenz** [comment]
In that case the proposal has been accepted and we will announce to remove the collection from Ansible 10.

Thanks all!

I've created PR ansible-community/ansible-build-data#248 and added ansible-community/ansible-build-data#249 to the milestone for 10.

I'll create an announcement for Bullhorn later.

**Comment by mariolenz** [comment]
IIRC we've kept issues like this one about collection removal from version X open until X has been released. However, since we've moved discussions to the [forum](https://forum.ansible.com) and the collection has been removed from 10.0.0.a1, I think we should close this even if 10.0.0 hasn't been released yet.

If someone wants to discuss cancelling the removal / re-adding of the collection, please open a topic in the forum.
