### ISSUE TITLE
Upload and verify Ansible release key in keys.openpgp.org 

### ISSUE THREAD

**Issue by anweshadas** [ansible-community/community-topics#227]
### Summary

We need to verify our Ansible Release key to https://keys.openpgp.org  so that our users can actually download the public key and verify the signature. 

1. Whoever has access to  this [email address](ansible-gha@redhat.com) can do this.
2. Update docs with the steps.

**Comment by Ompragash** [comment]
Not sure if you have seen this public URL https://releases.ansible.com/keys/ but we can upload the public Ansi-Keys here to verify the signature

**Comment by felixfontein** [comment]
There's also https://blog.pypi.org/posts/2023-05-23-removing-pgp/.

**Comment by anweshadas** [comment]
Thank you @felixfontein. I am removing the signing steps from the release process.

**Comment by anweshadas** [comment]
Thank you @felixfontein for pointing it out. I am removing the signing steps from the release process. I am closing the issue.
