### ISSUE TITLE
Need suggestions on commonly used flags for Ansible CLI commands

### ISSUE THREAD

**Issue by BhattacharjeeSutapa** [ansible-community/community-topics#232]
### Summary

We're trying to create a cheatsheet of commonly used flags on each of the Ansible CLI commands. 

Please list the flags that you commonly use when running the Ansible cli commands, or a sample command as how you use it. The documentation team will select the most widely used flags and publish them in the form of a cheatsheet. We need your help for the following commands:

- [ ] `ansible-galaxy`
- [ ] `ansible`
- [ ] `ansible-inventory`
- [ ] `ansible-doc`
- [ ] `ansible-config`
- [ ] `ansible-vault`

### Additional Information
See this [ansible-playbook cheatsheet](https://docs.ansible.com/ansible/latest/command_guide/cheatsheet.html#ansible-playbook) for an idea of what we're looking for.

**Comment by samccann** [comment]
Relates to this docs issue if anyone is looking for background details - https://github.com/ansible/ansible/issues/75509 and thanks!
