### ISSUE TITLE
[Associated vote ended on 2023-07-18] Unmaintained collection: netapp.azure

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#234]
### Summary

The [netapp.azure](https://github.com/ansible-collections/netapp.azure) collection looks unmaintained / abandoned, it has:

- no new commits since September 2022
- no release on Galaxy since version 21.10.01 1 1/2 year ago
- no reaction on ansible-collections/netapp.azure#6
- no reaction on ansible-collections/netapp.azure#7

Additionally, when I run `ansible-test sanity` it seems to fail with the following errors:

```
ERROR: Found 1 pylint issue(s) which need to be resolved:
ERROR: tests/unit/compat/builtins.py:29:4: unused-import: Unused import __builtin__
```

and

```
ERROR: Found 16 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/azure_rm_netapp_account.py:0:0: parameter-type-not-in-doc: Argument 'thumbprint' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/azure_rm_netapp_account.py:0:0: parameter-type-not-in-doc: Argument 'x509_certificate_path' in argument_spec defines type as 'path' but documentation doesn't define type
ERROR: plugins/modules/azure_rm_netapp_account.py:0:0: undocumented-parameter: Argument 'thumbprint' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/azure_rm_netapp_account.py:0:0: undocumented-parameter: Argument 'x509_certificate_path' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/azure_rm_netapp_capacity_pool.py:0:0: parameter-type-not-in-doc: Argument 'thumbprint' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/azure_rm_netapp_capacity_pool.py:0:0: parameter-type-not-in-doc: Argument 'x509_certificate_path' in argument_spec defines type as 'path' but documentation doesn't define type
ERROR: plugins/modules/azure_rm_netapp_capacity_pool.py:0:0: undocumented-parameter: Argument 'thumbprint' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/azure_rm_netapp_capacity_pool.py:0:0: undocumented-parameter: Argument 'x509_certificate_path' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/azure_rm_netapp_snapshot.py:0:0: parameter-type-not-in-doc: Argument 'thumbprint' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/azure_rm_netapp_snapshot.py:0:0: parameter-type-not-in-doc: Argument 'x509_certificate_path' in argument_spec defines type as 'path' but documentation doesn't define type
ERROR: plugins/modules/azure_rm_netapp_snapshot.py:0:0: undocumented-parameter: Argument 'thumbprint' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/azure_rm_netapp_snapshot.py:0:0: undocumented-parameter: Argument 'x509_certificate_path' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/azure_rm_netapp_volume.py:0:0: parameter-type-not-in-doc: Argument 'thumbprint' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/azure_rm_netapp_volume.py:0:0: parameter-type-not-in-doc: Argument 'x509_certificate_path' in argument_spec defines type as 'path' but documentation doesn't define type
ERROR: plugins/modules/azure_rm_netapp_volume.py:0:0: undocumented-parameter: Argument 'thumbprint' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/azure_rm_netapp_volume.py:0:0: undocumented-parameter: Argument 'x509_certificate_path' is listed in the argument_spec, but not documented in the module documentation
```

**Comment by mariolenz** [comment]
[The Bullhorn issue #105](https://mailchi.mp/redhat/the-bullhorn-104) 2023-06-03

**Comment by mariolenz** [comment]
Vote happens in #249

**Comment by mariolenz** [comment]
@ansible-community/steering-committee Please vote on #249 if you haven't done yet. It's the last day and there are still not enough votes from the steering committee.

**Comment by gotmax23** [comment]
I see +8/0/0 (@mariolenz, @felixfontein, @russoz, @briantist, me, @Andersson007, @gundalow, @acozine) from the SC and +1/0/0 from the community (@cybette). Can another @ansible-community/steering-committee member please confirm?

**Comment by mariolenz** [comment]
ansible-community/ansible-build-data#271

**Comment by felixfontein** [comment]
This collection had a new release in September, but that release wasn't tagged (https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-1732932405). There has been no reaction so far in the corresponding issue in the repository either (https://github.com/ansible-collections/netapp.azure/issues/8).

**Comment by carchi8py** [comment]
Sorry i missed the first ping fixed the release in github

**Comment by carchi8py** [comment]
@felixfontein can we update the user for Netapp. @lonico is no longer at Netapp and should be removed. And i was on vacation most of Oct so just getting to see these now. Can we add my counter parts in case I'm out again for a month and they can respond.
@suhasbshekar
@wenjun666
@chuyich

**Comment by felixfontein** [comment]
@carchi8py for which of the netapp collections should they be added?

**Comment by carchi8py** [comment]
netapp.aws
netapp.um_info
netapp.cloudmanager
netapp.azure
netapp.ontap

**Comment by felixfontein** [comment]
I created #313 to update the maintainers list for these collections.

**Comment by mariolenz** [comment]
IIRC we've kept issues like this one about collection removal from version X open until X has been released. However, since we've moved discussions to the [forum](https://forum.ansible.com) and the collection has been removed from 10.0.0.a1, I think we should close this even if 10.0.0 hasn't been released yet.

If someone wants to discuss cancelling the removal / re-adding of the collection, please open a topic in the forum.
