### ISSUE TITLE
[Associated vote ended on 2023-08-01] Unmaintained collection: netapp.elementsw

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#235]
### Summary

The [netapp.elementsw](https://github.com/ansible-collections/netapp.elementsw) collection looks unmaintained / abandoned, it has:

- no new commits since September 2022
- no release on Galaxy since version 21.7.0 1 1/2 year ago
- no reaction on ansible-collections/netapp.elementsw#10
- no reaction on ansible-collections/netapp.elementsw#12

Additionally, when I run `ansible-test sanity` it seems to fail with the following errors:

```
ERROR: Found 3 pylint issue(s) which need to be resolved:
ERROR: plugins/modules/na_elementsw_cluster_config.py:220:75: used-before-assignment: Using variable 'encryption_state' before assignment
ERROR: tests/unit/compat/builtins.py:29:4: unused-import: Unused import __builtin__
ERROR: tests/unit/plugins/modules/test_na_elementsw_vlan.py:9:0: unused-import: Unused Mock imported from ansible_collections.netapp.elementsw.tests.unit.compat.mock
```

**Comment by mariolenz** [comment]
[The Bullhorn issue #105](https://mailchi.mp/redhat/the-bullhorn-105) 2023-06-11

**Comment by mariolenz** [comment]
Vote happens in #250

**Comment by mariolenz** [comment]
I counted votes:

7 x +1 from SC (mariolenz felixfontein russoz Andersson007 briantist gotmax23 markuman)

Can someone from the @ansible-community/steering-committee confirm?

**Comment by felixfontein** [comment]
I confirm the counts by @mariolenz: seven +1 votes from SC members, and no other votes (no -1, no non-SC).

**Comment by mariolenz** [comment]
In that case the proposal has been accepted and we will announce to remove the collection from Ansible 10.

Thanks all!

**Comment by mariolenz** [comment]
IIRC we've kept issues like this one about collection removal from version X open until X has been released. However, since we've moved discussions to the [forum](https://forum.ansible.com) and the collection has been removed from 10.0.0.a1, I think we should close this even if 10.0.0 hasn't been released yet.

If someone wants to discuss cancelling the removal / re-adding of the collection, please open a topic in the forum.
