### ISSUE TITLE
Setting guidelines for awesome ansible's curated list of interesting tools

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-topics#242]
### Summary

Since https://github.com/ansible-community/community-topics/issues/220 decided we would push most new tools etc to the awesome ansible repo, I noticed that repo has a [discussion from last year](https://github.com/ansible-community/awesome-ansible/issues/65) on what sort of tools should be added. 

Copying the proposed set of guidelines here for review before we finalize them:

**The submitted Project/Tool:**

1.     should be more than 30 days old.
2.     should be actively maintained.
3.     should be compatible with the latest supported Ansible version.

**Tutorials, Videos, Courses, Blog Posts and Opinions:**

1.     should use/follow modern Ansible paradigms.
2.     should not teach things that are deprecated in the latest supported Ansible version.

All PRs to that repo should include a technical reviewer to ensure the tool at least looks useful/interesting.

**Comment by samccann** [comment]
note - if we go with these guidelines it means someone technical would have to review the tool/blog/video to be sure it qualifies.

**Comment by felixfontein** [comment]
I like these proposed guidelines. They sound very reasonable, also to what I as a user would expect.

I guess one question is how often should the existing entries be revisited - since these things do change over time (being maintained, being compatible with the latest Ansible release, etc.).

**Comment by samccann** [comment]
We could start a process of reviewing them either once a year, or once after every major Ansible package release. I say after the package release because  that gives the tool owners time to review/update after the core release that happens about a month earlier.  
But that does mean volunteers with the technical chops to go and do that review... and there are a lot of tools

**Comment by KeyboardInterrupt** [comment]
Hello! As mentioned in the linked discussion, I'm currently picking up the slack and I would like to address the lingering issues concerning the Awesome List.

It would bring me much joy if fellow community members could join in and contribute to the list – I moved it into the ansible.community group precisely for that purpose :)

Looking ahead, it would be ideal to have some members, besides myself, step up as maintainers. This way, we can keep the list up to date even if I'm unavailable for any reason.

If there are currently no takers for that role, I believe presenting each incoming MR either in the relevant Matrix rooms or discussing them in the working group meetings would be the next best thing to ensure additional eyes on the merge requests.

What's the optimal, preferably asynchronous method to highlight a new MR to the community's attention?

^C

**Comment by samccann** [comment]
Sorry for the repeat mentions in a few related Awesome Ansible issues today, but I'll add it here as well. The best place would be https://forum.ansible.com/tags/c/project/7/community. It's async and will hopefully get more eyes on it.

**Comment by samccann** [comment]
This discussion is now happening as part of a general discussion on the forum so closing this topic here. See https://forum.ansible.com/t/table-stakes-for-including-projects-on-the-ecosystem-page/4341/11 to continue.
