### ISSUE TITLE
[Associated vote ended on 2023-08-09] Unmaintained collection: netapp.um_info

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#244]
### Summary

The [netapp.um_info](https://github.com/ansible-collections/netapp.um_info) collection looks unmaintained / abandoned, it has:

- no new commits since September 2022
- no release on Galaxy since version 21.8.0 nearly 2 year ago
- no reaction on ansible-collections/netapp.um_info#8
- no reaction on ansible-collections/netapp.um_info#9

Additionally, when I run `ansible-test sanity` it seems to fail with the following errors:

```
ERROR: Found 4 pylint issue(s) which need to be resolved:
ERROR: tests/unit/compat/builtins.py:29:4: unused-import: Unused import __builtin__
ERROR: tests/unit/plugins/module_utils/test_netapp.py:9:0: unused-import: Unused import os.path
ERROR: tests/unit/plugins/module_utils/test_netapp.py:11:0: unused-import: Unused import tempfile
ERROR: tests/unit/plugins/module_utils/test_netapp.py:18:0: unused-import: Unused COLLECTION_VERSION imported from ansible_collections.netapp.um_info.plugins.module_utils.netapp
```

and

```
ERROR: Found 5 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/na_um_aggregates_info.py:0:0: doc-default-does-not-match-spec: Argument 'feature_flags' in argument_spec defines default as ({}) but documentation defines default as (None)
ERROR: plugins/modules/na_um_clusters_info.py:0:0: doc-default-does-not-match-spec: Argument 'feature_flags' in argument_spec defines default as ({}) but documentation defines default as (None)
ERROR: plugins/modules/na_um_nodes_info.py:0:0: doc-default-does-not-match-spec: Argument 'feature_flags' in argument_spec defines default as ({}) but documentation defines default as (None)
ERROR: plugins/modules/na_um_svms_info.py:0:0: doc-default-does-not-match-spec: Argument 'feature_flags' in argument_spec defines default as ({}) but documentation defines default as (None)
ERROR: plugins/modules/na_um_volumes_info.py:0:0: doc-default-does-not-match-spec: Argument 'feature_flags' in argument_spec defines default as ({}) but documentation defines default as (None)
```

**Comment by mariolenz** [comment]
[The Bullhorn issue #106](https://mailchi.mp/redhat/the-bullhorn-106) 2023-06-23

**Comment by mariolenz** [comment]
@ansible-community/steering-committee Vote happens in #261

**Comment by mariolenz** [comment]
I counted votes:

7 x +1 from SC (mariolenz felixfontein russoz gotmax23 briantist markuman Andersson007), no -1 from SC and 1 explicit "no vote" from SC (thaumos)

no votes from community

Can someone from the @ansible-community/steering-committee confirm?

**Comment by russoz** [comment]
I can confirm the 7 ayes and one no-vote from SC, no votes from community.

**Comment by mariolenz** [comment]
In that case the proposal has been accepted and we will announce to remove the collection from Ansible 10.

Thanks all!

**Comment by felixfontein** [comment]
This collection had a new release in September, but that release wasn't tagged (https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-1732932405). There has been no reaction so far in the corresponding issue in the repository either (https://github.com/ansible-collections/netapp.um_info/issues/10).

**Comment by mariolenz** [comment]
IIRC we've kept issues like this one about collection removal from version X open until X has been released. However, since we've moved discussions to the [forum](https://forum.ansible.com) and the collection has been removed from 10.0.0.a1, I think we should close this even if 10.0.0 hasn't been released yet.

If someone wants to discuss cancelling the removal / re-adding of the collection, please open a topic in the forum.
