### ISSUE TITLE
Deprecated collection: community.sap

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#247]
### Summary

`community.sap` is deprecated: ansible-collections/community.sap#25

Actually, this has been already discussed in #98. There's also ansible-community/ansible-build-data#126 that announced to replace the content in `community.sap` with deprecated redirects to `community.sap_libs` in Ansible 7.

However, it looks like we didn't do this and `community.sap` is still part of the community package. I'd like to get rid of this collection ASAP. ~~I don't think we really want to replace the content in `community.sap` with deprecated redirects to `community.sap_libs` in 8.x, so do it in 9.0.0 and plan the removal for 10.0.0?~~ We should simply remove from the collection package (9?).

**Comment by felixfontein** [comment]
For 8.x.0 it's too late anyway, we no longer accept new major releases of collections.

CC @rainerleber

**Comment by mariolenz** [comment]
Maybe we should just announce the removal from Ansible 10 (because it's deprecated and therefor _officially_ unmaintained) instead of spending time to implement "deprecated redirects to community.sap_libs" magic.

What do you think?

**Comment by mariolenz** [comment]
@ansible-community/steering-committee members What do you think we should do about this? It doesn't look like anyone is working on implementing those announced (deprecated) redirects.

But the collection _is_ officially deprecated / unmaintained. Personally, I think we should get rid of it ASAP (Ansible 9?) even without any redirects.

What's your opinion?

**Comment by gundalow** [comment]
If the collection still works, then people could be using it and we need to be careful not to break it.
The only time (I'm aware of) that we've removed plugins without deprecation is when the underlying API has changed and the plugins didn't work at all.

**Comment by rainerleber** [comment]
Sorry for ghosting, I had too much to work on :-( removing is good to me and deprecating as well. up to you

**Comment by mariolenz** [comment]
@gundalow 

> If the collection still works, then people could be using it and we need to be careful not to break it.

I'm not sure if I understand you... do you really think it's a good idea to keep a collection in the community package that is _officially deprecated_? We've removed a lot of collections that weren't, but where we voted on that those collections _look_ unmaintained.

> The only time (I'm aware of) that we've removed plugins without deprecation is when the underlying API has changed and the plugins didn't work at all.

I'm not sure what you mean "without deprecation". As far as I can see, `community.sap` has already been [deprecated in 5.9](https://github.com/ansible-community/ansible-build-data/blob/09f78cebc37caeaa1cae6d4fb8de8eb9cb3cf9f9/5/CHANGELOG-v5.rst#L625) and should have been remove in 7. The problem is, or even the two problems: Nobody has implemented those redirects and `community.sap` hasn't been removed from Ansible 7.

I would suggest to vote on announcing the removal from Ansible in Ansible 9, especially looking at the last comment from @rainerleber.

cc @felixfontein

**Comment by rainerleber** [comment]
@felixfontein pr is open: https://github.com/ansible-collections/community.sap/pull/29
is this the right way ?

**Comment by rainerleber** [comment]
All Done from my side

**Comment by mariolenz** [comment]
Now that `community.sap` 2.0.0 implementing the redirects has been released, let's get rid of the collection: ansible-community/ansible-build-data#262

Thanks all!

**Comment by mariolenz** [comment]
IIRC we've kept issues like this one about collection removal from version X open until X has been released. However, since we've moved discussions to the [forum](https://forum.ansible.com) and the collection has been removed from 10.0.0.a1, I think we should close this even if 10.0.0 hasn't been released yet.

If someone wants to discuss cancelling the removal / re-adding of the collection, please open a topic in the forum.
