### ISSUE TITLE
Having only single release in one day

### ISSUE THREAD

**Issue by anweshadas** [ansible-community/community-topics#248]
### Summary

Doing two releases in one day has been quite difficult. It would nice if we can decide on having only one release in one day.

**Comment by felixfontein** [comment]
I created a PR to update the roadmaps according to what we discussed at today's community meeting: https://github.com/ansible/ansible-documentation/pull/39

The basic idea is that if two releases happen in the same week, the current stable release train has precedence, and the other release (either prerelease of the next release train, or regular release of the previous release train) will be delayed by one day.

**Comment by felixfontein** [comment]
The proposal has been accepted by multiple folks, so if you are interested in this topic please check it out. If nobody objects or has further amendments/requests/..., we'll probably merge it next week on Wednesday around the time for the community meeting.

**Comment by gotmax23** [comment]
https://github.com/ansible/ansible-documentation/pull/39 has been merged, so I'll close this issue. Thanks @anweshadas for bringing this up and @felixfontein for putting up the PR.
