### ISSUE TITLE
[Associated vote ended on 2023-08-30] Update Python requirements for collections included in Ansible

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#251]
### Summary

The current Ansbile inclusion requirements have a session on Python requirements (https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#python-requirements) that's somewhat outdated. Python 2.7 and 3.5/3.6/3.7/3.8 are no longer supported on the controller for recent ansible-core releases, and Python 2.6 is no longer supported on the target for recent ansible-core releases. Python 3.5 support will also be dropped on the target side soon.

We should update these, and in particular try to rephrase these conditions so we don't mention explicit Python versions that have to be updated regularly. There is already a proposal - see https://github.com/ansible/ansible-documentation/pull/68 by the core team - which we should discuss, and possibly amend.

**Comment by felixfontein** [comment]
(A useful link is https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#support-life, which shows which Python versions are supported by which ansible-core versions. This is the link the reference in the PR points to.)

**Comment by mariolenz** [comment]
This might be relevant, at least in the future: ansible-collections/news-for-maintainers#54

**Comment by felixfontein** [comment]
How about:

1. Python content in a collection MUST support all Python versions that are supported on the controller side by at least one ansible-core version supported by the collection. The only exception are Python versions not supported by libraries the Python content depends on. Other exceptions need to be approved on a case-by-case basis by the Steering Committee.
2. Python content in a collection SHOULD support all Python versions that are supported on the target side by at least one ansible-core version supported by the collection.

**Comment by felixfontein** [comment]
As discussed in today's community meeting: I'll convert the above post into a PR during the next days, then we can word-smith it, and start a vote once everyone's happy with the wording.

**Comment by felixfontein** [comment]
I tried writing this up in https://github.com/ansible/ansible-documentation/pull/281.

**Comment by felixfontein** [comment]
There is now an active vote for this in https://github.com/ansible-community/community-topics/discussions/268.

**Comment by felixfontein** [comment]
@ansible-community/steering-committee please do not forget about this vote. So far only four SC members voted, and the two-weeks voting period ends tomorrow.

**Comment by felixfontein** [comment]
@acozine @cidrblock @briantist @thaumos @jamescassell @gundalow @ssbarnea the vote currently doesn't reach quorum (which is 7; so far only 6 SC members voted). Since the vote is supposed to end today, it would be great if you could take a look and also vote.

**Comment by felixfontein** [comment]
I counted votes:
- 8 x +1 from SC members (felixfontein gotmax23 markuman russoz Andersson007 mariolenz acozine cidrblock)
- 4 x +1 from community members (aretrosen spyrexd sean-m-sullivan leogallego)

Could another SC member please also count the votes? Thanks :)

**Comment by felixfontein** [comment]
@mariolenz thanks for counting, and everyone else thanks for participating!

**Comment by felixfontein** [comment]
I'm keeping this topic open for a bit so we can discuss improvents to the wording, that came up during the review of https://github.com/ansible/ansible-documentation/pull/281 when the vote was already running.

**Comment by felixfontein** [comment]
Closing since nobody started working on this. If this happens, we can re-open (or create a new issue).
