### ISSUE TITLE
Collection requirements: Fedora license table no longer has the GPL license compatibility data.

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#252]
### Summary

There's a requirement in [Collection requirements](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#collection-licensing-requirements) for included collections to have GPLv3+ compatible license.

As was [spotted](https://github.com/ansible/ansible-documentation/pull/105#issuecomment-1634512275) by @gotmax23 , [Fedora license table](https://docs.fedoraproject.org/en-US/legal/allowed-licenses/) we refer to no longer has the GPL license compatibility data. As we can see in [the post](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/REOA32J76AY7O2AKLJK5ZRX6CHVAAKW2/), Fedora folks decided not to maintain that information.

What we should do?

I see the following options on the top of my head:
1. To use only the [second table](https://wiki.debian.org/DFSGLicenses) (Debian) we refer to.
2. We'll find another table somewhere. Option?
3. [This one I would avoid if possible] We'll maintain our own list of compatible licenses. We can start with compatible licenses we know and then ask our legal each time when a new one appear
4. [I like this one] Restrict the licenses we already have not allowing collections licensed differently to get in. I.e. "The accepted licenses are GPLv3+, Apache 2, etc. we have included at the moment", that's it
5. _Your option here_

I think this is a pretty urgent question

**Comment by felixfontein** [comment]
Hmm, I remember @gotmax23 mentioning this last year, when that change was made. I'm no longer sure whether we discussed it at some meeting or in some community topic, but apparently we never came to a conclusion.

The table by Debian is a lot less easy to read than the original Fedora table was (it was in proper tabular form, with a column "GPL compatible" or something like that).

I kind of like 4, with the appendum that we can allow more licenses, but with some review process (which probably involves asking legal, if it isn't a clear case from the Debian list).

**Comment by Andersson007** [comment]
I found the following licenses in the package (I'm not 100% sure though if there are any other):
- GPL v3+
- Apache 2.0
- PSF 2.0
- MIT

Could anyone else re-check and confirm?
Then I could raise a PR proceeding with option 4 which we could vote on.

**Comment by Andersson007** [comment]
Created a PR https://github.com/ansible/ansible-documentation/pull/141 , please take a look to polish it and then we'll open a vote
Thanks

**Comment by Andersson007** [comment]
> Hi team, just in case, if we are looking for a GPL compatible list other than the Debian one, then the FSF/GNU has a very nice list, with a small summary for each alternative license:
> 
> * [GPL-Compatible Free Software Licenses](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses)

I'm personally OK with using what @leogallego 's suggesting and change the PR provided that SC is OK with using the link instead of Fedora's one

**Comment by felixfontein** [comment]
I think using the FSF/GNU link instead of Fedora is a good idea. Then we don't have to maintain an explicit list - we already did that in the beginning and got rid of it; see https://github.com/ansible-collections/overview/pull/164#issuecomment-815166828 for that decision and change to the requirements.

**Comment by Andersson007** [comment]
@leogallego thanks for the suggestion! As there's a wide support, I replaced the Fedora table linkj with the gnu.org one in the PR
Folks PTAL

**Comment by Andersson007** [comment]
Opened a vote https://github.com/ansible-community/community-topics/discussions/260, please vote

**Comment by felixfontein** [comment]
@gotmax23 in the vote you wrote:

> I'd prefer to get rid of the Debian list entirely

can you elaborate on that?

**Comment by gotmax23** [comment]
> @gotmax23 in the vote you wrote:
> 
> > I'd prefer to get rid of the Debian list entirely
> 
> can you elaborate on that?

> The Fedora list provides a nice table, is more comprehensive, and reflects the opinion of Red Hat legal, which we need to follow.

was comparing the Fedora list to the Debian list. I think the Fedora list makes the Debian list redundant. I think it is unreasonable to expect developers to check three different webpages to make sure a license is approved.

**Comment by felixfontein** [comment]
I think it's totally fine. Using a new license should only happen seldomly after enough checking, so asking to check three lists is as fine as asking to check two lists from my POV.

I don't want to drop the Debian list, I trust the Debian project and think it's better to only accept licenses that they also approve of.

**Comment by Andersson007** [comment]
vote count:
- SC:
  - 6  (Andersson007, mariolenz, russoz, felixfontein, briantist, acozine): +1
  - 1 (gotmax23): -1
- Community:
  - 1 (leogallego): +1

Could anyone from SC make the second count?

**Comment by mariolenz** [comment]
I confirm the count from @Andersson007: six +1 from SC, one -1 from SC and one +1 from the community.

**Comment by Andersson007** [comment]
merged the PR, thanks everyone!
