### ISSUE TITLE
[Associated vote ended on 2023-08-29] Unmaintained collection: ngine_io.exoscale

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#255]
### Summary

The [ngine_io.exoscale](https://github.com/ngine-io/ansible-collection-exoscale) collection looks unmaintained / abandoned, it has:

- no new commits since December ~~2021~~ 2022
- no release on Galaxy since version 1.0.0 nearly 3 years ago
- no reaction on ngine-io/ansible-collection-exoscale#15
- no reaction on ngine-io/ansible-collection-exoscale#16
- no answer in ngine-io/ansible-collection-exoscale#17

**Comment by mariolenz** [comment]
[The Bullhorn issue #109](https://mailchi.mp/redhat/the-bullhorn-109) 2023-07-14

**Comment by mariolenz** [comment]
> I fixed the sanity check in the meanwhile.

Great, thanks @resmo!

Do you think you could also release a new version? I see you've worked on this collection quite a lot, but everything you've done over the last three years is kind of lost to the users. The latest version they can get is still 1.0.0 from three years ago :-(

**Comment by resmo** [comment]
Released v1.1.0

**Comment by mariolenz** [comment]
> Released v1.1.0

Thanks @resmo! I've changed my vote to -1 (keep it) because of the new release.

@ansible-community/steering-committee Now that there's a [new ngine_io.exoscale release](https://github.com/ngine-io/ansible-collection-exoscale/releases/tag/v1.1.0), you might want to reconsider your vote on #266.

**Comment by mariolenz** [comment]
I counted votes:

2 x +1 from SC (markuman briantist), 6 x -1 from SC (mariolenz Andersson007 felixfontein gotmax23 jamescassell acozine), 1 x undecided (0) from SC (russoz)

1 x undecided (+/-1) from community (resmo (the collection maintainer)), no other votes from community

Can someone from the @ansible-community/steering-committee confirm?

**Comment by Andersson007** [comment]
I confirm the count by @mariolenz , thanks everyone!

**Comment by mariolenz** [comment]
In that case the proposal has been rejected and we will keep the collection in the community package.

Thanks all!

**Comment by briantist** [comment]
sorry, seems I missed the chance to reverse my vote

**Comment by mariolenz** [comment]
> sorry, seems I missed the chance to reverse my vote

No problem. Changing your vote wouldn't have made any difference to the overall outcome, anyway. So if you're happy with keeping the collection, everything's fine :-)
