### ISSUE TITLE
Ansible Community Package Release via Github Actions

### ISSUE THREAD

**Issue by anweshadas** [ansible-community/community-topics#256]
## Initial PR(s)

- https://github.com/ansible-community/ansible-build-data/pull/265
- https://github.com/ansible/ansible-documentation/pull/121

## Discussion over Hackmd 

- https://hackmd.io/rGoXrLCEQ_KGqTsZZtyAeA?view

**Comment by gotmax23** [comment]
Let's keep discussion about the proposal overall in this issue and discussion about the code in https://github.com/ansible-community/ansible-build-data/pull/265. HackMD comments get really difficult to follow.
