### ISSUE TITLE
[Associated vote ended on 2023-08-02] Remove ngine_io.vultr from Ansible community package

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#257]
### Summary

The [ngine_io.vultr](https://github.com/ngine-io/ansible-collection-vultr) collection has been archived, so it's not maintained any more. I suggest to remove it from the community package.

As far as I understand, this collection is based on the Vultr v1 API which will be shut down after August 14th. This looks it won't be of any use after this date. Therefor, I suggest to deprecate it in Ansible 8.something and remove it from Ansible 9.

Or do you think we should keep it in 9 and remove it from 10? As I've said, it looks like it wouldn't be of any use after mid-August. I tend to remove it from 9.

What do you think?

cc @resmo

**Comment by resmo** [comment]
I would deprecate sooner than later, as the API will not be available anymore.

There is already a successor collection vultr.cloud which covers the functionality (but have might not have compatible syntax).

**Comment by gotmax23** [comment]
Yeah, as a special exception, I think we should fast track the removal process for this collection and remove it in Ansible 9.

**Comment by felixfontein** [comment]
+1 for that. For things that are broken (and that cannot easily be fixed, and in particular where the maintainers agree on this) there's no need to add extra waiting cycles.

**Comment by mariolenz** [comment]
@ansible-community/steering-committee Vote happens in #259

**Comment by mariolenz** [comment]
@ansible-community/steering-committee Please remember to vote on #259 if you haven't done yet!

**Comment by mariolenz** [comment]
I counted votes:

7 x +1 from SC (mariolenz gotmax23 felixfontein russoz Andersson007 briantist markuman), no -1 from SC and 1 explicit "no vote" from SC (thaumos)

1 x +1 from community (resmo), no other votes from community

Can someone from the @ansible-community/steering-committee confirm?

**Comment by felixfontein** [comment]
I can confirm these numbers. Special note is that the +1 community vote was from the maintainer of this collection. So we can definitely remove it.

**Comment by mariolenz** [comment]
I have created ansible-community/ansible-build-data#277 and will prepare a Bullhorn announcement soon.

**Comment by mariolenz** [comment]
The collection has been removed from Ansible 9, so I guess we should close this.
