### ISSUE TITLE
Move shared ansible glue python core to a standalone python package

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/community-topics#26]
### Summary

There is a growing bit of Ansible related code inside [ansiblelint.prerun](https://github.com/ansible-community/ansible-lint/blob/master/src/ansiblelint/prerun.py) which is shared with molecule and other projects. 

While we considered moving this code to [ansible-runner](https://github.com/ansible/ansible-runner), @felixfontein and @tadeboro argued against such a move for a few reasons:

* not a community driven project, so making changes to it may be considerably harder
* it would bring some dependencies that we may no find any need for, at the moment. Examples `pexpect` and `python-daemon`.

This is why the current proposal is to create yet another small python library that would host the shared code, now hosted inside ansiblelint.

Once done we can also remove the dependency between molecule and ansible-lint.

At this moment the only thing preventing us from doing this change is agreeing on how to name that library. Please suggest only one name per comment and make **use of thumbs up/down to vote on your preferred option**. Lets see how easy we would address one of the most challenging activities in computer science.... naming.

**Comment by ssbarnea** [comment]
`ansible-compat` mainly because that is its main goal: to provided an API that hides differences between various ansible versions.

**Comment by felixfontein** [comment]
It seems that a repository already exists: https://github.com/ansible-community/ansible-compat

@ssbarnea is the name already fixed, or still up to discussion? I.e. should we talk about it at tomorrow's meeting or not?

**Comment by ssbarnea** [comment]
I already created it but we can still change it if others have a better idea. Until we manage to move the sahred code release and swap deps we can still change the name.

**Comment by acozine** [comment]
other possible names:
ansible-bridge
ansible-dynasty
ansible-glue

**Comment by felixfontein** [comment]
ansiglue

**Comment by acozine** [comment]
ansible-dynasty

**Comment by acozine** [comment]
wrapsible

**Comment by Andersson007** [comment]
`agnostic` ( thanks @felixfontein )

**Comment by Andersson007** [comment]
`ansilink`

**Comment by Andersson007** [comment]
compatebull :)

**Comment by abadger** [comment]
I don't want to bikeshed and I'm totally fine with ansible-compat or any other name proposed here so far but since felixfontein mentioned this in the meeting:

> 48:51 <felixfontein> it's probably a good idea to have a `ansi*` or `antsi*` name, so it's clearer that the package belongs there (and is not a random other dependency that's easier to miss if you don't notice the ansible puns)

I'll throw an option out there:

I can make antsibull a namespace package and we can then have other tools and libraries install inside of that.  That way the compat code doesn't have to depend on anything in antsibull (or vice versa) but they can benefit from a common name prefix and filesystem location.

**Comment by ssbarnea** [comment]
ansibliss?

BTW, thanks to everyone making suggestions here, it was a real joy to read the thread this morning.

Note on on namespacing it is a nightmare for packaging point of view. I love the idea of namespacing in general but one place where I think it never worked well was python packaging system, with a huge number of problems that are not directly visible. I was hopping that these would be sorted during the last decade but this did not happen. 

The suggestion to keep the package/module name starting with at least "an" makes perfect sense.

**Comment by felixfontein** [comment]
Right now, there haven't been many votes. The only name with three :+1: is `ansignostic`, everything else has two :+1:.

@ssbarnea how should we proceed?

**Comment by ssbarnea** [comment]
Leave it as it is, I need to focus on making the code ready for use. We can go later at this ticket if we need.

**Comment by cidrblock** [comment]
+1 for ansible-runner as the target for this code, as it will handle the EE vs local/venv work

**Comment by felixfontein** [comment]
@cidrblock is ansible-runner ok with dropping the extra requirements (pexpect, python-daemon)?

**Comment by ssbarnea** [comment]
While it would be noce not to add those two extra deps, which are not really needed for our tools, these are not really big deal as they are pure python deps.

**Comment by ssbarnea** [comment]
This glue is https://github.com/ansible/ansible-compat
