### ISSUE TITLE
[Associated vote ended on 2023-08-22] Deprecated collection: community.azure

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#263]
### Summary

[community.azure](https://github.com/ansible-collections/community.azure) is deprecated: ansible-collections/community.azure#26

I think we should remove it from the community package. But I'm not sure if we should remove it from Ansible 9 or keep it there and remove it from Ansible 10.

I would prefer Ansible 9 since it's officially unmaintained and archived, especially since the alternative or successor or whatever ([azure.azcollection](https://github.com/ansible-collections/azure)) is already part of Ansible 8 as far as I can see.

**Comment by felixfontein** [comment]
It has been a list of redirect redirects to azure.azcollection anyway for a year, so I'm fine with removal from Ansible 9. Since the collection is pretty tiny it doesn't matter too much if it stays a bit longer as well, though.

**Comment by mariolenz** [comment]
> It has been a list of redirect redirects to azure.azcollection anyway for a year, so I'm fine with removal from Ansible 9. Since the collection is pretty tiny it doesn't matter too much if it stays a bit longer as well, though.

Good point. Especially since the collection announced that it's deprecated / unmaintained, but we didn't in the community package (yet).

I guess it won't hurt to keep it in Ansible 9, so let's vote on removing it from Ansible 10: #264

**Comment by mariolenz** [comment]
I counted votes:

7 x +1 from SC (mariolenz gotmax23 felixfontein briantist russoz Andersson007 markuman), no -1 from SC

3 x +1 from community (maxamillion leogallego cybette), no -1 from community

Can someone from the @ansible-community/steering-committee confirm?

**Comment by Andersson007** [comment]
@mariolenz i checked and confirm the count

**Comment by mariolenz** [comment]
IIRC we've kept issues like this one about collection removal from version X open until X has been released. However, since we've moved discussions to the [forum](https://forum.ansible.com) and the collection has been removed from 10.0.0.a1, I think we should close this even if 10.0.0 hasn't been released yet.

If someone wants to discuss cancelling the removal / re-adding of the collection, please open a topic in the forum.
