### ISSUE TITLE
What should we do with unresponsive module maintainers?

### ISSUE THREAD

**Issue by aminvakil** [ansible-community/community-topics#27]
### Summary

I'm not sure if there is already a policy for removing unresponsive maintainers of modules or not, but here is an example:
https://github.com/ansible-collections/community.general/pull/1334#issuecomment-830695026
which maintainers have not responded to mentioning them for almost 7 months.

Although I don't know if there is any value in removing maintainer's id from `.github/BOTMETA.yml` if they are not responsive and what would be appropriate response in this situation.

**Comment by felixfontein** [comment]
There isn't a policy, but I would suggest the following: If we notice a maintainer is no longer active, create a PR where we remove them, and ping them there. Keep the PR open for some time (let's say 1-2 months, sometimes people are just on a longer vacation so they might not respond quickly), and if they don't respond, merge. We can mention in the PR that in case they want to become active again, they should please tell us and it will be easy to re-add them. (And of course we should thank them for their service :) )

**Comment by Andersson007** [comment]
The idea sounds sensible - it would be more obvious that a module is orphaned if there's no entry in BOTMETA.
- However AFAIK the bot will ping people who listed in `authors` field anyway.
- Also if there are, say, 5 folks listed and in a month after constant pinging them all only one responded, should we remove the other 4 at once?

This also should be considered.
If we have a concrete wording for the exclusion issue here (say, in the description), it would be easier to discuss and make a decision on the spot in the initial hearings:)

**Comment by aminvakil** [comment]
Surely we can't know if a maintainer reads issues/PRs or interested unless they've been mentioned directly by PR author or one of collection maintainers, so whatever goes by are after direct mention, but I think what @felixfontein and @Andersson007 already mentioned in community working group last week is a suitable approach:

1. After a month of not responding in PR, open a PR thanking them for helping maintaining module, and removing them from `.github/BOTMETA.yml`, (leave them as author of module of course, if they don't WANT to get notified can ask collection maintainers to add them to `ignore`).
2. Instantly email them (from what address?) (with what template?) to email which has been mentioned on their github profile AND their git commits both.
3. Merge remove PR after two months.

Overall this gives them 3 months at least from mentioning them on PR in github.

**Comment by Andersson007** [comment]
Suggestion: Can we state something like `Maintainers of the collections can specify criteria of maintainer unresponsiveness, whether exclude unresponsive maintainers or not, specify the exclusion process, and make decisions on any other related questions themselves`?
I'd be happy with any other wording implying that `this topic is the business of collection maintainers`.

Let's decide and close the issue?

**Comment by Andersson007** [comment]
As there have been no signs of activity here for the last couple of years, I suggest proceeding with leaving this questions up to maintainers of corresponding community sub-projects.
I'm closing the topic.
Feel free to speak up or re-open if you think we should continue the discussion.
Thanks everyone!
