### ISSUE TITLE
Deprecate unmaintained community.kubevirt in favor of kubevirt.core but there are nuances.

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#270]
### Summary

Hi everyone,
We need you opinion on the following matter.

Related discussion is https://github.com/ansible-collections/community.kubevirt/pull/45.

The gist is that:
- [community.kubevirt](https://github.com/ansible-collections/community.kubevirt) is broken with the latest versions of Ansible. It was excluded from the package and there have been no signs of interest from the community to start maintaining it
- we were contacted by a maintainer of the [kubevirt.core](https://github.com/kubevirt/kubevirt.core) collection which is aimed to be a replacement for that old unmaintained one. They are asking us whether the old one can be deprecated on Galaxy (not in the repo but there's a tag on Galaxy saying that a collection is deprecated)
- **the issue** is that the new one contains only one module instead of 6 in the original one. I raised @felixfontein 's and mine concerns in the [issue](https://github.com/ansible-collections/community.kubevirt/pull/45).
- the maintainer arguments are reflected in the [comment](https://github.com/ansible-collections/community.kubevirt/pull/45#issuecomment-1682373491).

What do you think is more appropriate in this case:
- Option 1: We add only a note to README redirecting to the new collection + release a dummy patch version to make it visible on Galaxy, leaving the door for potential new maintainers to pick up `community.kubevirt` and continue working on it
- Option 2:
  - We do things listed in Option 1
  - Put the `deprecated` tag on `community.kubevirt` on Galaxy
- Option 3:
  - We do things listed in Option 2 and 3
  - Archive the repo
- Should we vote on this?

I personally incline for Option 2. I'd like to highlight that `community.kubevirt` is not a part of the package any more and there haven't been any signs that it can soon be raised from the aches.
Ideas on the options?

**Comment by 0xFelix** [comment]
Hi @Andersson007, thanks for opening this.

As explained in https://github.com/ansible-collections/community.kubevirt/pull/45#issuecomment-1680573987 and https://github.com/ansible-collections/community.kubevirt/pull/45#issuecomment-1682373491 I'd vote at least for Option 2, preferably for Option 3. The `community.kubevirt` collection is unmaintained, outdated and ideally all future work would go into one collection, namingly the `kubevirt.core` collection.

**Comment by felixfontein** [comment]
How about Option 2, with an upgrade to Option 3 in say ~6 months assuming it stays dead?

**Comment by mariolenz** [comment]
I think option 3 is the best one, although the suggestion from @felixfontein to wait a couple of months until archiving the repo sounds like a good idea.

I'm not really sure if we should vote on this or not, though. I tend to not vote on this, but only slightly.

**Comment by Andersson007** [comment]
All you're saying SGTM folks, thanks! I'm also inclining not to vote as the collection is not in the package.
Let's wait for a couple of days to give others a chance to say their opinions, then close the topic and proceed with the most popular option.

**Comment by 0xFelix** [comment]
Going with Option 2 and upgrading to Option 3 in ~6 months sounds good to me!

**Comment by Andersson007** [comment]
let's proceed with Option 2 for now, then, after at least half a year since the release and deprecation, we can think of archiving the repo provided that it'll be still dead. Closing the topic.
thanks everyone for sharing your opinions!
