### ISSUE TITLE
How should Galaxy NG refer to roles

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/community-topics#272]
### Summary

Earlier this year, I complained to @jctanner that the new Galaxy NG codebase (see https://beta-galaxy.ansible.com) refers to roles as `Legacy Roles`. I think this phrasing is overly pejorative and that it'd be better to refer to them as `Standalone Roles`. James suggested that I bring it to the steering committee, but I got busy and forgot, so better late than never I guess.

Currently, the navigation sidebar looks like this:

- Collections
  - Collections
  - Namespaces
 - Legacy
   - Legacy Roles
   - Legacy Namespaces
- [...]

I purpose changing it to something like

- Collections
  - Collections
  - Namespaces
- Roles
  - Roles
  - Role Namespaces

**Comment by felixfontein** [comment]
Having `Collections` and `Standalone Roles` in the top-level menu structure in your suggestion also would look good to me:
![fake screenshot with adjusted names](https://github.com/ansible-community/community-topics/assets/5781356/ccbdd2d9-ace2-4575-8f52-028f9a5267aa)

(I used the Inspector to adjust the names.)

**Comment by mariolenz** [comment]
If the original galaxy roles aren't deprecated, I agree that `Legacy Roles` is overly pejorative. In that case, `Standalone Roles` (or just `Roles`) sounds a lot better to me.

**Comment by russoz** [comment]
Hi @gotmax23 

I tend to agree with you. Just a couple of questions though:
* Is there an official directive for everyone not to publish roles? I recall seeing something but it had more of an "advisory" tone to it. If we want to call it Legacy, I reckon we should make a incisive statement on the topic. => If my memory serves
* Regardless of that, I reckon we should have some sort of phase out approach to it, just like what we have in code: deprecate it for some time, then remove. So we let maintainers know that they should be updating them roles to collections for a while, and then later we call them "Legacy".

**Comment by felixfontein** [comment]
Standalone roles have not been deprecated to my knowledge, and will continue to work.

There have been questions in the past of making it easier to migrate from roles to collections, for example by being able to use the same name for both a role and a collection - which I think is now possible with Galaxy NG -, and it was always said that standalone roles will stay. At least that's my recollection. CC @geerlingguy since he's been one of them asking for this intensively.

**Comment by Andersson007** [comment]
"legacy" imo sounds like something to get rid off in the IT context. so i would prefer "Standalone Roles" too

**Comment by felixfontein** [comment]
There seems to be consensus that "Legacy" shouldn't be there. I guess what we should do next is collect a list of possibilities and vote on what we think would be best.

1. `Roles` (no prefix)
2. `Standalone roles`
3. `Legacy roles` (status quo should also be a choice in the vote)
4. more (serious :) ) suggestions?

**Comment by samccann** [comment]
@jonnyfiveiq fyi

**Comment by samccann** [comment]
See the linked issue ^^ 

I also clarified with the product team and there is no plan to deprecate standalone roles or the ability to upload new roles to GalaxyNG using the CLI.

**Comment by russoz** [comment]
Si, given that nothing changed in that context, I have to drop the question: Why are we trying to push --force a qualifier to that term? Why don't we just leave the term as-is? Nothing has changed, so why change the term? Back to the original text of this issue, I think we should go with:

- Collections
  - Collections
  - Namespaces
- Roles
  - Roles
  - Role Namespaces

**Comment by felixfontein** [comment]
If everyone is fine with it, I would propose to close this once https://github.com/ansible/ansible-hub-ui/pull/4196 shows up on https://beta-galaxy.ansible.com/. If you disagree, please state it here :)

**Comment by felixfontein** [comment]
As @resmo pointed out this is now active, so let's close this :) Thanks everyone!

**Comment by geerlingguy** [comment]
(And there was much rejoicing!)
