### ISSUE TITLE
ETA for Ansible Release 9.0.0 Alpha1 

### ISSUE THREAD

**Issue by anweshadas** [ansible-community/community-topics#276]
### Summary

The release of ansible-core 2.16 beta 1 is delayed.  This issue has been created to decide on the  ETA for Ansible Release 9.0.0 Alpha1. Proposal dates 

1. 2023/09/28 - ansible-core will tentatively release on 23rd (keep a day in buffer after that)
2.  2023/10/03 - keep the Tuesday release cadence alive.

**Comment by gotmax23** [comment]
Can we schedule the release for tomorrow (Wednesday)?

**Comment by felixfontein** [comment]
Since ansible-core 2.16.0b1 is now out, I would go for tomorrow or Thursday (whatever suits you best).

**Comment by felixfontein** [comment]
Kind of depends on https://github.com/ansible-community/antsibull/pull/546 and https://github.com/ansible-community/ansible-build-data/pull/300.

**Comment by anweshadas** [comment]
I will do the Ansible 9.0.0 Alpha1 Release tomorrow (28th September, Thursday). Thank you everyone for sharing your feedback.
