### ISSUE TITLE
Standardising IRC modes for spam prevention + Matrix

### ISSUE THREAD

**Issue by GregSutcliffe** [ansible-community/community-topics#28]
### Summary

The work on Matrix is progressing well. We have had productive meetings with Element, and I have a long-form writeup of all my learnings so far in draft - I have been conversing with other FOSS communities that have either already moved to Matrix or are planning to, and discussing best practices. I will share that doc as soon as it's ready.

In preparation for that, I'd like to get our IRC channel modes set correctly. We have tested out the "+qe" strategy (see https://hackmd.io/k5xHgbpUTACRGPxNLru7ug for details) and that seems to be working well, we've had no further spam in that channel.

I'd like the community's blessing to go ahead and set those modes in all the channels listed under https://docs.ansible.com/ansible/devel/community/communication.html#working-groups (which I am replicating in a Matrix "space" at the moment) so that we are all set for proper interoperability / safety on both sides.

I may not be able to make the meeting in person to discuss further, but I hope this is not especially controversial as it is just a standardisation of our authentication and spam blocking policy across the Ansible IRC namespace.

**Comment by felixfontein** [comment]
Discussion from today's meeting: we prefer to usually not have `+r` or `+q` on the channels. It's good to have insturctions for ops how to enable these when needed (i.e. active spam waves) though, which allow Matrix users to still speak.

**Comment by GregSutcliffe** [comment]
Thanks for the discussion. Where would be the best place to document the correct invocations?

**Comment by GregSutcliffe** [comment]
As an example of the process in #38, I'm going to put this issue in Final Comment Period

- Action: No change to rooms. Document for modes is at https://hackmd.io/k5xHgbpUTACRGPxNLru7ug as required
- Disposition: Accept
- FCP Ends: 14th Dec

**Comment by GregSutcliffe** [comment]
Closing this old issue. The HacKMD has the docs if we need it.
