### ISSUE TITLE
Test pinging teams from other orgs

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#280]
### Summary

Can someone from @ansible-collections/cloud please confirm here that they've been pinged? It's about ansible-community/ansible-build-data#333.

**Comment by felixfontein** [comment]
It won't work (as you can see since the team name isn't clickable).

**Comment by goneri** [comment]
@jillr?

**Comment by mariolenz** [comment]
> It won't work (as you can see since the team name isn't clickable).
