### ISSUE TITLE
Include community.library_inventory_filtering_v1 in the ansible package (no vote's needed, will get included by default on 2024-01-12 if no objections)

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#283]
### Summary

**No vote is needed**

Include `community.library_inventory_filtering_v1` in the ansible package as there two reviews and approvals.

See the [inclusion discussion](https://github.com/ansible-collections/ansible-inclusion/discussions/68).

Will get included by default on **2024-01-12** (See [WF](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#collection-inclusion-requests-workflow)).

If you have some major concerns about the collection, please raise them ASAP.

**Comment by felixfontein** [comment]
@mariolenz @Andersson007 thanks a lot for reviewing the collection and driving the inclusion process!
