### ISSUE TITLE
ansible-playbook

### ISSUE THREAD

**Issue by SpencerParker** [ansible-community/community-topics#284]
### Summary

I use Ansible playbook on the Ansible server to perform batch deployment operations and send shell operations to multiple users on multiple target servers. After the shell operation is completed, it will return a success log. One server has four users, and one of these four users did not return success. After inspection, it was found that the message log of the server already contains instructions and operations specific to that user, The specific manifestation is Python: ansible command, which indicates that the link is not a problem, but the actual phenomenon is that I did not obtain success and had a good idea

**Comment by Andersson007** [comment]
@SpencerParker hello, this repo is used for other purposes.
I would first try to ask on the [Forum](https://forum.ansible.com/) or on [Matrix](https://docs.ansible.com/ansible/devel/community/communication.html#ansible-community-on-matrix) in the `users:ansible.com` channel. Then, if community agrees it's a bug, I think https://github.com/ansible/ansible would be a proper place for reporting the issue.
