### ISSUE TITLE
Votes are now happening in the Ansible Forum!

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#285]
### Summary

We voted (see #273) to continue all discussions and votes in the [Ansible Forum](https://forum.ansible.com/)!

If you're looking for active votes: [List of all active community votes in the Ansible Forum](https://forum.ansible.com/tags/intersection/community-wg/active-vote)

If you just want to see all community topics in the Forum: [List of all community topics in the Ansible Forum](https://forum.ansible.com/tags/c/project/7/community-wg)

**Comment by mariolenz** [comment]
I think we should close this issue since it's only an announcement.

@Andersson007 @felixfontein Feel free to re-open it again if you think I've been wrong doing this.

**Comment by gotmax23** [comment]
We want it to show up at the top of the issue queue I think. It's already pinned, but it's good to have it show both in the issue queue and the pinned issues for maximum visibility.

**Comment by mariolenz** [comment]
> We want it to show up at the top of the issue queue I think. It's already pinned, but it's good to have it show both in the issue queue and the pinned issues for maximum visibility.

Sorry, I didn't realize this. Yes, in that case let's keep it open.
