### ISSUE TITLE
Smaller ansible packages (no tests/ dir?)

### ISSUE THREAD

**Issue by Daryes** [ansible-community/community-topics#29]
##### SUMMARY
Hello,
As asked, reposting this from ansible-collections/overview#177

Not to be nitpicking, but when installing the metapackage ansible 3.4.0, I was surprised by the size the docker image I built took.

To be more specific, create a virtualenv and install ansible with  `pip3 install --no-cache-dir ansible==3.4.0`
Then :
```
$ cd <venv>
$ du -sh 
484M    .

$ cd lib/python3.*/site-packages/ansible_collections
$ du -sh
400M    .

# list all "tests" directories under collections and return their disk size
$ find . -name "tests" -type d -print0 | xargs -0 du -sh --total
(...)
122M    total
```
That was at first glance. 

While I understand the need of the unit and integration tests, they can become heavy in disk space consumption.
Maybe I missed something, but is there a requirement to have them shipped in the release builds ?

##### ISSUE TYPE
- Enhancement

**Comment by tadeboro** [comment]
Links to some discussions we already had in the past:

 1. https://meetbot.fedoraproject.org/ansible-community/2021-02-10/ansible_community_meeting.2021-02-10-19.01.log.html#l-409
 2. https://meetbot.fedoraproject.org/ansible-community/2021-02-24/ansible_community_meeting.2021-02-24-19.01.log.html#l-51

**Comment by felixfontein** [comment]
We've discussed this a bit at today's meeting. The main problem is that we're still waiting for an answer from RH legal. We'll try to speed up that process.

A side-discussion started on how to make it easier to prepare more specialized (and thus smaller) environments. A related discussion for that is #31.

**Comment by dmsimard** [comment]
I've linked an additional PR to community.network for the sake of discussion.

To put things into perspective, between just community.general and community.network, we're talking about excluding over 2k files which saves 10s off of the installation duration and reduces the uncompressed size on disk from 33MB to 15.6MB.

**Comment by dmsimard** [comment]
I've been increasing the scope of testing for 5.0.0rc1 (including [packaging in fedora](https://fedoraproject.org/wiki/Changes/Ansible5)) and I must re-iterate that I find this particularly problematic.

The Fedora RPM testing coverage highlighted [thousands of errors and warnings](https://gist.githubusercontent.com/dmsimard/3db2e2dda73acf8fd7115a55d6c6e5ae/raw/2fefff5394c54363654abfe56bdae5cde6f11e36/rpm-lint.txt) of which we can ignore a sizeable chunk (ansible modules are not executable) but the remaining majority are related to tests and so, so many unnecessary files (files like ``.gitignore``, ``.swp``, ``.DS_Store``, etc.).

I cannot in good conscience continue to knowingly and willingly ship all of these files, even if only considering how this reflects in terms of quality and professionalism to the community.

What might this look like in practice ? My [current proposal in the fedora spec](https://src.fedoraproject.org/rpms/ansible/pull-request/19#comment-90445) includes the following (and it's not even exhaustive):
```
for hidden in $(find ansible_collections | grep -E ".gitignore|.github|.azure-pipelines|.swp|.orig|.DS_Store|.keep|.gitkeep|.vscode|.pytest_cache|.yamllint|.pre-commit-config.yaml|.plugin-cache.yaml|.pytest_cache|.mypy_cache|.zuul.yaml|.flake8|.circleci|.gitattributes|.ansible-lint|.travis.yml|.gitlab-ci.yml|.idea|.settings"); do
  rm -rf $hidden
  count=$((count+1))
done
for tests in $(find ansible_collections | grep -E "tests/unit|tests/integration|tests/utils|tests/sanity|tests/runner|tests/regression"); do
  rm -rf $tests
  count=$((count+1))
done

# Additional, specific directories to remove
rm -rf ansible_collections/kubernetes/core/molecule

echo "Over ${count} files and directories removed."
```

That short snippet returns ``Over 24588 files and directories removed.`` (see [build.log](https://koji.fedoraproject.org/koji/taskinfo?taskID=79218464)) and if we count the number of remaining files in the entire package, we're looking at 15526 files so these removed files make up for more than half of the package.

On another note, from a performance standpoint, it cuts the installation time in more than half on my (relatively fast) laptop:
```
# rc1
real	1m7.110s
user	0m59.975s
sys	0m9.460s

# a hypothetical rc2
real	0m30.916s
user	0m27.166s
sys	0m4.888s
```

I would like to strongly suggest that we include this cleanup as part of the build process and spin an ansible 5.0.0rc2 package.

**Comment by gundalow** [comment]
Currently `ansible-galaxy build` ignores:
1) https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/collection/__init__.py#L793-L803
2) Anything listed in a collection's galaxy.yml `build_ignore`  [example](https://github.com/ansible-collections/community.crypto/blob/main/galaxy.yml#L27-L30)

**Comment by felixfontein** [comment]
From today's discussion:
1. It's too late to change it for 5.0.0.
2. We can discuss whether such a change can make it into a 5.x.0 minor release, or has to wait for 6.0.0 (and its pre-releases).

**Comment by felixfontein** [comment]
I will look at wheel building and making sure that the extra files aren't included in the wheel (and thus in the user's install), even if they are still in the tarball. I think this is the only thing we can really do without hearing from legal.

Also for Ansible 6, there will be a larger reduce of files in community.general and community.network due to them dropping the symlinks, which currently unfortunately get duplicated by setup.py. This is a tiny reduction compared to omitting tests etc., but better than nothing :)

**Comment by felixfontein** [comment]
Here is a WIP PR for removing files from the bdist: https://github.com/ansible-community/antsibull/pull/342

**Comment by felixfontein** [comment]
In any case, if we want to do this already for 5.x.0, then we need some testing, and this should be announced in time (more than a couple of weeks in advance) so that collection authors/maintainers have some time to check whether this breaks something.

(While this shouldn't happen, you *could* have non-module plugins which depend on data, or even Python files, inside tests/, or other directories we are excluding. Or there could be other files in plugins/ we want to exclude for some reason, but which are actually needed by a plugin.)

**Comment by felixfontein** [comment]
Since this will happen for Ansible 6 (with the first 6.0.0 alpha targetted for next week) I'm going to close this.
