### ISSUE TITLE
How to add things to the agenda

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#3]
Open questions:
1. Does every agenda entry need an issue here?
2. a) Should the issue be mentioned in https://github.com/ansible/community/issues/539?
    b) Or should that issue be locked and only used for announcements / meeting minutes?
        * In that case, a list of potential topics should be posted before the meeting in the agenda?
        * Or should the meeting work with the open issues here (we can use labels to organize them better for that)?

**Comment by felixfontein** [comment]
Details of today's discussions can be found in the log (see link in https://meetbot.fedoraproject.org/ansible-community/2021-03-31/ansible_community_meeting.2021-03-31-18.00.html). We did not come to a final conclusion today, but several people favoured 2b).

**Comment by felixfontein** [comment]
A more concrete proposal for 2b):

## Proposal

1. Every agenda item is created as an issue in this repository.
2. All steering committee members can add/remove labels, and we use labels to denote priorities, area of topic, and add `next_meeting` if we think this should be discussed in the next meeting.
3. At the meeting, we look at the list of open issues, and issues with `next_meeting` get first priority.
    * Currently we assume that the list of open issues won't be too long, and that not too many will have a `next_meeting` label, so we don't need a fully defined process on how to select topics for the meeting.
    * If we find out that this assumption isn't good, we can re-evaluate/discuss in a couple of meetings.

**Comment by felixfontein** [comment]
The community meeting agreed to accept this proposal.

**Comment by felixfontein** [comment]
ansible/community#539 is locked and the rules posted there, and the `next_meeting` label already exists, so closing.

**Comment by Andersson007** [comment]
@felixfontein i think we should create a pinned issue with a summary

**Comment by felixfontein** [comment]
@Andersson007 I think it's better to add it to the README instead.

**Comment by Andersson007** [comment]
> @Andersson007 I think it's better to add it to the README instead.

Ah, forgot about README:) it's also OK
