### ISSUE TITLE
Inclusion candidates for Ansible 5

### ISSUE THREAD

**Issue by tadeboro** [ansible-community/community-topics#32]
### Summary

This issue contains high-level information about the inclusion process of each candidate. Feel free to edit as things progress.

> 2021-10-12
> **Last day** for new collections to be submitted for inclusion in Ansible-5. Collections MUST be **reviewed and approved before being included**. There is no guarantee that we will review every collection. The earlier your collection is submitted, the more likely it will be that your collection will be reviewed and the necessary feedback can be addressed in time for inclusion.
[Ansible 5.0.0 Roadmap](https://docs.ansible.com/ansible/devel/roadmap/COLLECTIONS_5.html)

---

### Already accepted collections

  * [community.dns](https://github.com/ansible-collections/ansible-inclusion/discussions/22)
  * [comunity.ciscosmb](https://github.com/ansible-collections/ansible-inclusion/discussions/26)
  * [infoblox.nios_modules](https://github.com/ansible-collections/ansible-inclusion/discussions/11)
  * [netapp.storagegrid](https://github.com/ansible-collections/ansible-inclusion/discussions/23)
  * [cloud.common](https://github.com/ansible-collections/ansible-inclusion/discussions/30)

---

### 2. [equnix.metal](https://github.com/ansible-collections/ansible-inclusion/discussions/15) - unresolved issues

  * There was some activity in the inclusion discussion, but nothing to review yet since things are not in the main branch yet. This is still true as of 2021-10-15.
  * @felixfontein [reviewed the candidate](https://github.com/ansible-collections/ansible-inclusion/discussions/15?sort=new#discussioncomment-1353727), waiting for maintainer feedback.

### 3. [vmware.vmware_rest](https://github.com/ansible-collections/ansible-inclusion/discussions/24) - unresolved issues

  * @tadeboro [reviewed the candidate](https://github.com/ansible-collections/ansible-inclusion/discussions/24#discussioncomment-1016469), no open issues (needs a new release and `cloud.common` needs to make into Ansible 5).
  * @felixfontein [reviewed the candidate](https://github.com/ansible-collections/ansible-inclusion/discussions/24#discussioncomment-1485070), waiting for maintainer feedback (there are still some unresolved issues present).

### 4. [trendmicro.deepsec](https://github.com/ansible-collections/ansible-inclusion/discussions/27) - unresolved issues

  * @tadeboro [reviewed the candidate](https://github.com/ansible-collections/ansible-inclusion/discussions/27#discussioncomment-1016085), waiting for the maintainer feedback (there are still some unresolved issues present).

### 5. [networktocode.nautobot](https://github.com/ansible-collections/ansible-inclusion/discussions/28) - needs another review

  * @tadeboro [reviewed the candidate](https://github.com/ansible-collections/ansible-inclusion/discussions/28#discussioncomment-1016257).

### 6. [cisco.ise](https://github.com/ansible-collections/ansible-inclusion/discussions/31) - needs action from reviever

  * @Andersson007 [reviewed the candidate](https://github.com/ansible-collections/ansible-inclusion/discussions/31?sort=new#discussioncomment-1337038), waiting for maintainer feedback.
  * @tadeboro [reviewed the candidate](https://github.com/ansible-collections/ansible-inclusion/discussions/31#discussioncomment-1483963).

### 7. [dellemc.unity](https://github.com/ansible-collections/ansible-inclusion/discussions/32) - unresolved issues

  * @tadeboro [reviewed the candidate](https://github.com/ansible-collections/ansible-inclusion/discussions/32#discussioncomment-1485027), waiting for maintainer feedback.

### 8. [dellemc.powerflex](https://github.com/ansible-collections/ansible-inclusion/discussions/33) - unresolved issues

  * @tadeboro [reviewed the candidate](https://github.com/ansible-collections/ansible-inclusion/discussions/33#discussioncomment-1484650), waiting for maintainer feedback.

**Comment by Andersson007** [comment]
I've just reviewed `community.dns`. +1 for inclusion.

**Comment by Andersson007** [comment]
I've just reviewd `comunity.ciscosmb`, everything spotted was fixed, +1 for inclusion

**Comment by felixfontein** [comment]
We voted on the inclusion of community.ciscosmb and community.dns in today's meeting (https://meetbot.fedoraproject.org/ansible-community/2021-09-15/ansible_community_meeting.2021-09-15-18.00.html) and accepted both for inclusion in Ansible 5.

**Comment by tadeboro** [comment]
Just a minor status update before today's meeting. Inclusion candidates that have at least two positive reviews are:

 1. infoblox.nios_modules
 2. netapp.storagegrid
 3. cloud.common

I think we can vote about their inclusion today.

I also went over all of the candidates and updated their statuses. Consult the summary at the top of the issue for more details.

**Comment by felixfontein** [comment]
Since we can incorporate collections "once they are done", I don't think we need this tracking issue anymore. @tadeboro thanks for your work on this!
