### ISSUE TITLE
Custom GitHub actions related to Ansible

### ISSUE THREAD

**Issue by briantist** [ansible-community/community-topics#40]
### Summary

I've created several custom GitHub actions in the `community.hashi_vault` collection that could potentially be useful to others:
https://github.com/ansible-collections/community.hashi_vault/tree/main/.github/actions

I'm wondering if anyone else thinks so, and whether we should look to move some/all of these, and any new ones, to repositories hosted in the `ansible-community` namespace, both to centralize development of them and to make them available to anyone.

### Summary of actions I have so far
- `pull-ansible-test-images` -- pulls the ansible test container images needed, separately from running the tests, to aid in separating the time taken (quay.io is slooooow) from the time taken to actually run the tests. Will probably eventually be supplanted by a dedicated `ansible-test` feature (but not in 2.9 probably): https://github.com/ansible/ansible/issues/75320
- `macos-docker` -- installs docker on MacOS runners
- `collection-via-git` -- installs ansible collections directly from git repositories rather than galaxy, to avoid its downtime spurts interrupting CI
- `ansible-codecov` -- runs codecov in a way that can separate out the `--group-by` features of `ansible-test` into flags so you can see categorized coverage

**Comment by felixfontein** [comment]
One idea from the meeting:

Let's have a repository for a new Python package (pip installable) with some test tools that can be used in GHA and in other CI systems (AZP, Circle CI, Zuul, and also Makefiles ☺), with possibly GHA wrappers around them. (The GHA wrappers could live in the same repo, since then they'd use the same versioning system as the tools themselves.)

This could include some existing tools as the ones in https://github.com/ansible-collections/community.internal_test_tools/tree/main/tools

**Comment by briantist** [comment]
It's not a bad idea, speaking of the actions I have so far, I think the only one where that makes sense is `ansible-codecov`;  it's already (mostly) python and it could have wide appeal for anyone who finds the flags thing interesting.

I think it's worth looking at just how small some of the others are and whether it makes much sense to port to python, have a separate release for pip and then wrap it.

Back to versioning for GHA, if all the python is in one repo, and all the actions live alongside it, we're also back to having all the actions together, in a way where they can't be released separately easily. 

So I don't know.. I'm a little on the fence about it for _all_ of them, but I do think it makes sense for some, for reusability on other platforms.

---

If we were going to do a first GHA-specific repo I'd probably go with the `collection-via-git` action, since many collections already do that, so we'd have more potential consumers to learn from. I was already doing it with a small bash snippet, the action just makes it feel more GHA native and avoid copy/pasting.

**Comment by felixfontein** [comment]
> It's not a bad idea, speaking of the actions I have so far, I think the only one where that makes sense is `ansible-codecov`; it's already (mostly) python and it could have wide appeal for anyone who finds the flags thing interesting.

Installing dependencies (especially from galaxy.yml and tests/requirements.yml, depending on context, and either with `git clone` or `ansible-galaxy collection install`) is another candidate, also since it's sufficiently complex.

> Back to versioning for GHA, if all the python is in one repo, and all the actions live alongside it, we're also back to having all the actions together, in a way where they can't be released separately easily.

That is true, but I think this isn't a big problem, since we *should* avoid breaking changes anyway. :)

**Comment by pabelanger** [comment]
I'd take a look at https://github.com/ansible/ansible-zuul-jobs this is a generic set of jobs we use in our Zuul CI, and could give some examples of how to share your actions with others.  Where https://opendev.org/zuul/zuul-jobs is the upstream repo we also pull jobs from.

I'm a big fan of just writing playbooks / roles for CI, then having each system call ansibe-playbook to do the thing you want.

**Comment by mariolenz** [comment]
@briantist Please close this issue if done, or open a new forum topic and then close the issue with a pointer to the new discussion: [Community-topics: Archiving the repo](https://forum.ansible.com/t/4990/8)

**Comment by felixfontein** [comment]
Before this is archived, let me add a reference to a related discussion on the forum: https://forum.ansible.com/t/repository-for-shared-workflows-for-collection-testing/3298
