### ISSUE TITLE
A space for welcome / offtopic chat

### ISSUE THREAD

**Issue by GregSutcliffe** [ansible-community/community-topics#42]
### Summary

Context: Offtopic chat is hugely important in building a cohesive social group, and we should be thinking clearly about how to encourage it, rather than letting it happen by accident.

Currently offtopic / chat is generally held in #community:ansible.im / #ansible-community. This has arisen organically, which is fine, but we have an opportunity to revisit this due to 2 converging things:

1) The upcoming Summit-as-part-of-Fest is likely to bring a lot of new members (even if temporarily) and it feels wrong to swamp the purpose of #community with people getting to know us. A place for new folks to get oriented, be signposted to the right place for their topic (whether the support room, a working group room, etc) or just to talk about our weekends seems right.
2) With the adoption of Matrix, we also inherit the 300+ user #ansible:matrix.org room, and that *currently* represents a fragmented community, as user support is happening there *and* in #users:ansible.im / #ansible. Forcing them all to abandon that room destroys a community that has existed for 4+ years.

Instead I propose we make #ansible:matrix.org into the "welcome" room, add an IRC bridge to #ansible-welcome, and make that our "landing page". This will return #community:ansible.im to it's intended purpose as the working group for improving the community, although I'm sure we'll still chat there too :)

**Comment by jillr** [comment]
Maybe `#ansible-general`?  Would be familiar to folks without an irc background since `#general` is a default channel in Slack and Discord.

**Comment by Andersson007** [comment]
`#ansible-hello`

**Comment by Andersson007** [comment]
`#ansible-hi`

**Comment by felixfontein** [comment]
In the community meeting, we decided for #ansible-social.

**Comment by GregSutcliffe** [comment]
I think we can close this. #social:ansible.im is ready, and in theory the room is pplumbed in to #ansible-social.

There is an issue at the moment with the bridge in that room which I am dealing with EMS about, but the *concept* of having a social room is agreed.
