### ISSUE TITLE
Deprecation of servicenow.servicenow in favor of servicenow.itsm

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/community-topics#44]
### Summary

I have noticed that we currently carry [servicenow.servicenow](https://github.com/ServiceNowITOM/servicenow-ansible) in the [Ansible community package](https://github.com/ansible-community/ansible-build-data/blob/e66cfcf5b07e5c4712139e7c57646075267379e4/5/ansible.in#L93) but it has been deprecated in favor of [servicenow.itsm](https://github.com/ansible-collections/servicenow.itsm) which is not in the package and has not yet filed for inclusion.

We should try to make sure this is addressed in time before the freeze for Ansible 5 with the appropriate redirects and deprecation messages as necessary.

**Comment by tima** [comment]
I discussed this with @dmsimard offline but briefly stated for the record...

I recommend officially deprecating servicenow.servicenow and including servicenow.itsm in Ansible 5. I would not set up a mapping from one to the other -- these are different collections with different interfaces. The mapping won't work. I'd also recommend removing servicenow.servicenow in Ansible 6.

**Comment by tima** [comment]
On second thought if adding servicenow.itsm is going to cause a hassle, let’s hold on it for 5 and reassess for 6. I’m not sure what value there is in that collection for community distribution users.

I still recommend deprecating and eventually removing the other SNOW collection.

**Comment by mariolenz** [comment]
I think we should close this issue because `servicenow.servicenow` has been removed from Ansible 7: ansible-community/ansible-build-data#156

In order to add `servicenow.itsm`, someone (the maintainers?) should create an [inclusion request](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#creating-new-policy-proposals-inclusion-requests).
