### ISSUE TITLE
Proposed release schedule for community.general (upcoming major 4.0.0 release)

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#46]
### Summary

From the Ansible Roadmap:
2021-11-08 last chance for major version bump
2021-11-09 Ansible 5.0.0 beta1 - feature freeze
2021-11-16 Ansible 5.0.0 beta2
2021-11-23 Ansible 5.0.0 rc1
2021-11-30 Ansible 5.0.0 release
2022-12-21 Ansible 5.1.0 release (proposal in #45)
2022-01-04 Ansible 5.1.0 release (current, if proposal in #45 is not accepted)

The next planned community.general release is 3.8.0 on October 12th (this is the regular three week schedule). My proposal is to make this the last 3.x.0 minor release, and do the 4.0.0 release three weeks after that, on November 2nd (and potentially the first 3.8.1 bugfix release). That would be

2021-10-12 c.g 3.8.0
2021-11-02 c.g 4.0.0 (major release!)
2021-11-02 c.g 3.8.1 (if neccessary)
2021-11-23 c.g 4.1.0
2021-11-23 c.g 3.8.2 (if neccessary)
2021-12-21 c.g 4.2.0
2021-12-21 c.g 3.8.3 (if neccessary)
...

with the regular three weeks interval. This would:
1. Have 4.0.0 released one week before the deadline (and if we need 1-2 days more, it's still in time);
2. Have 4.1.0 released so it can go into Ansible 5.0.0
3. Have 4.2.0 released so it can go into Ansible 5.1.0

**Comment by felixfontein** [comment]
CC @russoz @Ajpantuso as community.general co-maintainers

**Comment by russoz** [comment]
Hi @felixfontein , if Ansible 5.1.0 release is kept set to Jan, would we keep the date on c.g 4.2.0?

**Comment by felixfontein** [comment]
@russoz I hope it won't come to that ;) But if that happens, we need to discuss that again. Waiting five weeks instead of three sounds not so great, but maybe we could still do c.g 4.2.0 at that point, and release c.g 4.3.0 just two weeks after so it makes it into Ansible 5.1.0. Then we have minor releases at most every three weeks, and don't fall out of sync from the Ansible release schedule.

**Comment by russoz** [comment]
Other than that risk, which is not entirely in our hands, it LGTM.
