### ISSUE TITLE
Proposal to remove the python-2.6 requirement

### ISSUE THREAD

**Issue by abadger** [ansible-community/community-topics#6]
RHEL6 (which uses python-2.6 as its base python) went EOL at the end of November, 2020.  That leaves no active RHEL and no active Ubuntu LTS releases which are based on python-2.6.

https://github.com/ansible-collections/overview/pull/165

**Comment by jamescassell** [comment]
RHEL6 is tending to stick around longer than I'd have hoped... even Fedora COPR re-enabled el6 builds for this reason.  I'd like to continue the py-2.6 support for some time..

**Comment by felixfontein** [comment]
We currently mention that RHEL6 has extended support until 2024, and that Python 2.6 support is optional. I would keep it, or maybe emphasize the *extended* in extended support some more.

**Comment by abadger** [comment]
<nod> I suppose that "support" for python-2.6 is more important for ansible-core to drop since there's contracts and customer expectations around that.  Since python-2.6 support is optional for us, we could probably get away with emphasising that RHEL6 is EOL and only receiving selected updates for selected customers.

@acozine Perhaps it's more important to add something to the main documentation that says that things may or may not work on rhel6 (which is EOL) and Python-2.6 depending entirely on the whim the maintainers?

**Comment by abadger** [comment]
At today's meeting, the revised proposal (emphasising that python-2.6 support is only RHEL6 which has ended full support) was accepted and merged.
