### ISSUE TITLE
Revamping the community/contributor documentation

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-topics#60]
### Summary

We have docs in three places today for contributors:
*  ansible/ansible in the [community folder](https://github.com/ansible/ansible/tree/devel/docs/docsite/rst/community)
*  [ansible/community-docs](https://github.com/ansible/community-docs) - more collection focused
*  [ansible-collections/overview](https://github.com/ansible-collections/overview) - has deeper collection contribution details

Since only the first one is published to docs.ansible.com, we need to find a way to publish the details from the other two repositories.

### PROPOSAL

Create multiple guides:

- Generic community guide - for matrix/meetups/ etc - everything that is common across all Ansible repositories.
- ansible-core contributor guide - what is specific to ansible-core
- Ansible collections contributor guide - what is specific to ansible-collections

In the future we could extend this for projects like ansible-lint, ansible-navigator etc.

We have two implementation options that we are asking for feedback on:

1. Move all files into ansible/ansible and publish from there as separate guides.
2. Keep the source rst files in different repos, so the rst files live within the project repos, but extend `antsibull` to bring those files into the `make webdocs` commands as we do today for collection plugin docs.

In general, keeping everything in ansible/ansible is simpler, but extends the docs build in that repository well beyond what is really applicable to `ansible-core`.
Moving/keeping collection etc contributor source rst files in a separate repo is cleaner in terms of what is appropriate to each repository  and their respective branching/versioning, but complicates the `make webdocs` and associated tools like `antsibull`.

See [This document](https://hackmd.io/3Cvy2N8tTfSrUzqYZmfEHA) for complete details of the pros and cons of each approach.

**Comment by samccann** [comment]
This PR gives a start to this move - https://github.com/ansible/ansible/pull/76764 (WIP)

**Comment by samccann** [comment]
Based on community WG discussion, it was felt that having collection-based docs in a separate repo is the correct direction to go. Next steps would be deciding what repo, and discussing changes to `antsibull` to pull in select guides from a location outside of ansible/ansible repo.

**Comment by felixfontein** [comment]
I'm not sure this should have anything to do with antsibull. The build process for the Ansible docsite is controlled by code in the ansible/ansible repository. antsibull is only used to create documentation for plugins and collections. Other auto-generated parts of the Ansible docsite are generated by code in ansible/ansible. I think the code in there should be responsible for including documents from a separate repository.

**Comment by laurent-indermuehle** [comment]
To me, there are more than 3 places. I keep finding new useful documentation like this one [0] scatter all over the internet.

[0] https://github.com/redhat-cop/automation-good-practices
