### ISSUE TITLE
[Vote ended on 2022-02-01] Mention plugin type more prominently

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#61]
### Summary

As a result of the feedback collected in #57 I've adjusted ansible-community/antsibull#364 to mention the plugin time more explicitly in some less places than originally planned:

1. Mention the plugin type in the page main titles. This also mentions it in the HTML title, and makes both on-site and external search results much better. (See for example https://github.com/ansible/ansible/issues/75652)
2. Mention the plugin type in every collection's plugin index. This makes it possible to search for `file m` (or type some more letters of `module`) to find the documentation of the file module, and `file l` for the lookup on the ansible.builtin plugin index (https://ansible.fontein.de/collections/ansible/builtin/#plugin-index).

(There are two more changes: in the stub page for deprecated redirects, and in the boilerplate for collection plugins and modules, which always said 'plugin' without being more specific. I think these are not controversial at all.)

These changes improve actual usage problems (using the site search, and searching a collection's plugin index).

If you are in favor of merging this, and making the plugin type more prominent, please add a `+1` vote to this issue. If you prefer not to have this PR in this form, please add a `-1` vote. Please use comments and *not* emoticon reactions. Thanks.

I've set the 1st of February as a deadline, so we have three weeks to complete this vote.

**Comment by briantist** [comment]
+1

**Comment by tadeboro** [comment]
+1

**Comment by Andersson007** [comment]
+1

should we use a month's name instead of a number in the description? it can lead to confusion sometimes and to a need to figure out from context which number is about month and which one is about day:)

**Comment by jillr** [comment]
+1

**Comment by felixfontein** [comment]
+1 (might have been obvious, but for sake of simplicity of counting votes afterwards let's make this explicit :) )

**Comment by gundalow** [comment]
+1 
This is much clearer, thank you.

**Comment by cybette** [comment]
+1 (I like the clarity it provides)

**Comment by samccann** [comment]
+1

**Comment by markuman** [comment]
+1

**Comment by acozine** [comment]
+1

**Comment by felixfontein** [comment]
I've counted votes: 8 steering committee members votes +1, three community members voted +1, and there was no other vote. Would be glad if someone could confirm this.

**Comment by tadeboro** [comment]
My counts:

+1: briantist (SC), tadeboro (SC), Andresson007 (SC), jillr (SC), felixfontein (SC), gundalow (SC), cybette, samccann, jamescassell (SC), markuman, acozine (SC)
-1: 

Summary: +8 by steering committee members, +3 from community members.

**Comment by felixfontein** [comment]
Thanks everyone for taking part in this! I'll merge https://github.com/ansible-community/antsibull/pull/364, create a new antsibull release, and update https://github.com/ansible/ansible/pull/76759 to get this included in the devel docs ASAP!

**Comment by felixfontein** [comment]
Since this is already included in the devel docs, closing. Thanks everyone!
