### ISSUE TITLE
FEEDBACK WANTED: Crafting better changelog fragments

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-topics#64]
### Summary

Today, Ansible has minimal guidance on how a developer can craft an informative changelog fragment - https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment

Changelogs should inform the end-users about the high-level influence on their workflows UX-wise that has happened since the previous release. These fragments should be written in a common style so the autogenerated results flow well together. Perhaps choosing past tense.

The following changlog fragment types are also added to the autogenerated Ansible porting guides and should have clear instructions on how to write these:

- breaking changes
- major changes
- deprecated_features
- removed_features

**Comment by webknjaz** [comment]
Sweet, thanks for starting this topic! Are you planning to link the materials from the earlier conversations?

**Comment by samccann** [comment]
_This comment will be updated regularly based on the feedback received in this issue or other discussions._

Today, Ansible provides:

- Porting guide (target audience, end users of Ansible) - The Ansible package generates this based on changelog fragments that have been tagged appropriately. ansible-core manually creates porting guide entries.

- Changelogs (Target audience, end users AND developers) - Both Ansible package and ansible-core provide changelogs, but we don’t have a lot of guidance on what should be included in a ‘good’ changelog entry.

- git commits (target audience - other developers)- available only in git.

### Proposal for crafting better changelog fragments
Changelogs are predominantly for end users of Ansible or a collection. As such, add details about the change as if you were a user of Ansible. All changelog fragments should include a link to the issue tracker that the PR resolves. Use RST formatting as described in the [Ansible Style guide](https://docs.ansible.com/ansible/latest/dev_guide/style_guide/index.html).

_> possibly we should list out common markup instead of pointing to the whole guide. URLs and module/plugin names etc are easier to read if marked up properly for example_

> _each item below will have an example of a well-crafted fragment, once we decide on what is well-crafted :-)_

Use the following guidelines to maintain consistency across projects and collections.

#### breaking_changes
Changes that break existing playbooks or roles. This includes any change to existing behavior that forces users to update tasks. Displayed in both the changelogs and the Porting Guides. Write in present tense and clearly describe the new behavior that the end user must now follow.

#### major_changes
Major changes to Ansible itself. Generally does not include module or plugin changes. Displayed in both the changelogs and the Porting Guides. Write in present tense and describe what is new. Optionally, include a 'Previously..." sentence to help the user identify where old behavior should now change.

#### minor_changes
Minor changes to Ansible, modules, or plugins. This includes new features, new parameters added to modules, or behavior changes to existing parameters. Write in present tense. 

#### deprecated_features
Features that have been deprecated and are scheduled for removal in a future release. Displayed in both the changelogs and the Porting Guides. Use past tense and include an alternative, where available for what is being deprecated.

#### removed_features
Features that were previously deprecated and are now removed. Displayed in both the changelogs and the Porting Guides. Use past tense and include an alternative, where available for what is being deprecated.

#### security_fixes
Fixes that address CVEs or resolve security concerns. Include links to CVE information. Use present tense.

#### bugfixes
Fixes that resolve issues. Use past tense to describe the problem and present tense to describe the fix. 

#### known_issues
Known issues that are currently not fixed or will not be fixed. Use present tense and where available, use imperative tense for a workaround.

**Comment by samccann** [comment]
Prior discussion - https://hackmd.io/ZdymdeUSQNeM0hMjsn7vig which includes links to some related topics on other community opensource projects.

**Comment by samccann** [comment]
I'm still hunting down any opensource guidelines I can find so if you know of others, pop a link in the comments please!

**Comment by mariolenz** [comment]
> #### major_changes
> Major changes to Ansible itself.

Ansible or ansible-core? That is: Can a collection have major changes or not?

> Generally does not include module or plugin changes.

Generally is generally (ha!) problematic. What are the exceptions?

Maybe it would be clearer to define that changes to a single module or plugin are never major. I would see a change to a module util as major because this would (possibly) affect several modules at once. Maybe this would be a good definition, but I'm not sure.

Thoughts?

**Comment by mariolenz** [comment]
> I'm still hunting down any opensource guidelines I can find so if you know of others, pop a link in the comments please!

I can't provide any helpful opensource _guidelines_ at the moment, but I like [RfC 2119](https://www.rfc-editor.org/rfc/rfc2119.txt) which defines the key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL".

Maybe it would be a good idea to refer to this RfC and use those keywords as defined there. Then you could define for example:

> #### breaking_changes
> Changes that break existing playbooks or roles MUST be documented in `breaking_changes`. This includes any change to existing behavior that forces users to update tasks. Displayed in both the changelogs and the Porting Guides. Write in present tense and clearly describe the new behavior that the end user must now follow.

Just an idea.

**Comment by samccann** [comment]
@mariolenz agreed on your suggestions. We MUST :-) be clear on what has to be, what should be, etc. And I can add both a core and a collection example to each to help.  I believe collections have used major changes as well but it was brought up in the community WG meeting today that it is a bit unclear when to use it so we'll need to be more specific for sure.

**Comment by jillr** [comment]
samcann beat me to it.  :)  We've been using major_version in a number of collections for things that are notable at a collection level but generally not breaking.  

My best example offhand walks the line of breaking and major but as a discussion point:

In (amazon|community).aws we've used major_changes on major collection revisions to denote SDK support for that release (we have a stated SDK support policy that increments on major collection release).  This should generally not be breaking, but we do stop testing older SDK versions and cease guaranteeing support.

**Comment by Andersson007** [comment]
I would change the following a bit in the `minor_changes` description:
`.. or behavior changes to existing parameters` -> `.. or non- breaking behavior changes to existing parameters like new acceptable values` (what we have in `choices: [ ..., ... ]`).
or something with similar meaning

**Comment by mariolenz** [comment]
Is an issue the right place to discuss this? I suggest to use [discussions in ansible-collections/news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers/discussions). Or, alternatively, enable discussions in this repo.

Don't get me wrong, I'm fine with discussing better changelog fragments here. I just think that there might be better places to do it.

**Comment by webknjaz** [comment]
https://github.com/ansible/community/issues/384

**Comment by samccann** [comment]
I've updated the comment above to put in examples and the feedback so far. The formatting isn't perfect and I still need to dig up some github issues to go with each, but please review and see if you think these are good examples or not.

@mariolenz - I'm actually not sure when a community topic should be in the new news discussions. @felixfontein do you have ideas on when we should use these topics here vs the discussions in the collection news repo?

**Comment by felixfontein** [comment]
news-for-maintainers is definitely the wrong repository to discuss this; this is the right one. Whether we should use GH issues or GH discussions is probably a matter of taste. Both have advantages and disadvantages. I guess for now we should stay in this issue and discuss here.

**Comment by mariolenz** [comment]
> news-for-maintainers is definitely the wrong repository to discuss this; this is the right one.

At the moment I'm a little bit overwhelmed by the many points of contact and places to discuss things. I'm not always sure where a question belongs. Thanks for clarifying this @felixfontein!

> Whether we should use GH issues or GH discussions is probably a matter of taste. Both have advantages and disadvantages. I guess for now we should stay in this issue and discuss here.

Sure, no problem. I just wanted to raise the question if this is the right place. But it looks like it is :-)

**Comment by samccann** [comment]
Documenting some feedback from the community meeting:

- [ ] update examples to use our current fragment formatting guidelines
- [ ] Clarify breaking changes mean I MUST do something (change a playbook etc) whereas major changes mean I can CHOOSE to do something different but I don't have to.
- [ ] Clarify that Breaking changes MUST happen only in a major release. 
- [ ] use MUST/SHOULD etc as per RFC reference in prior comments.
- [ ] Remove 'new features' from the list of examples that should be a minor change.
- [ ] Clarify how a changelog could be used to announce an important upcoming EOL or breaking change in a future release. (ideally 6 months in advance, if known). These are individual fragments (typically major_change) not tied to a code change in the current release that the changelog appears, for example https://github.com/ansible-collections/community.general/blob/stable-1/CHANGELOG.rst#v1313

**Comment by samccann** [comment]
At this point, this discussion is now in the implementation phase and I'll link a PR here to the docs changes for final review.

**Comment by samccann** [comment]
Please post comments and reviews on the PR that implements this - https://github.com/ansible/ansible/pull/77040

**Comment by samccann** [comment]
Resloved by https://github.com/ansible/ansible/pull/77040  Thanks everyone!
