### ISSUE TITLE
[Vote ended on 2022-03-21] Important updates for Ansible Community Steering Committee guidelines

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#71]
### Summary

I suggest discussing and merging changes to the Steering Committee guidelines introduced in https://github.com/ansible/community-docs/pull/49 which elaborate on:
- community topic workflow (including adding the quorum)
- inclusion workflow and its simplification
- the chairperson's powers

Further actions:
- Please review the PR and (if needed) suggest changes until March 02, 2022.
- The vote starts on March 02, 2022 (someone will put a comment about it here).

**Comment by felixfontein** [comment]
While most of the changes are technical details (like how many votes needed etc.), there's one thing that everyone should be aware about: the chairperson is granted a veto right to unilaterally reject a Committee's decision. This is something everyone should be aware of.

Given this superpower of the chairperson, I'm wondering whether we need a correction mechanism in case the chairperson turns out to be crazy. Not that I hope that ever happens :) Maybe something like: a 2/3 majority of the Committee can override the chairperson's veto?

**Comment by Andersson007** [comment]
> While most of the changes are technical details (like how many votes needed etc.), there's one thing that everyone should be aware about: the chairperson is granted a veto right to unilaterally reject a Committee's decision. This is something everyone should be aware of.
> 
> Given this superpower of the chairperson, I'm wondering whether we need a correction mechanism in case the chairperson turns out to be crazy. Not that I hope that ever happens :) Maybe something like: a 2/3 majority of the Committee can override the chairperson's veto?

Sounds very sensible to me. How about 3/4, i.e. if there are 12 members in the committee, it would be 9 votes needed to overcome the veto? Anyway, in case the chairperson goes crazy, the committee can re-elect them:D

**Comment by briantist** [comment]
I had actually submitted a comment about that days ago, but I was on mobile so apparently it saved the comment but didn't post the review 🤦‍♂️just submitted now: https://github.com/ansible/community-docs/pull/49#discussion_r813467528

I was curious about the reasoning behind it.

**Comment by felixfontein** [comment]
@Andersson007 3/4 is also fine for me, 2/3 was the first number that came to my mind.

**Comment by Andersson007** [comment]
I'm opening the vote:
+1 for the update
-1 against (no updates are needed)

The vote **will end on March 21, 2022**. Please vote (feel free to suggest re-wording, we're voting on the spirit of the update)

**Comment by Andersson007** [comment]
+1

**Comment by felixfontein** [comment]
+1

**Comment by jamescassell** [comment]
+1

**Comment by markuman** [comment]
+1

**Comment by briantist** [comment]
+1

**Comment by jillr** [comment]
+1

**Comment by felixfontein** [comment]
@ansible-community/steering-committee all SC members, please take a look at this vote if you haven't already. This is a really important vote on our own voting process and the powers of our chairperson. Thanks!

**Comment by acozine** [comment]
+1. I suggested one change to the wording on the PR.

**Comment by Andersson007** [comment]
The vote has ended.
SC: +7 for mering
SC: nobody voted against.

**Comment by gundalow** [comment]
+1

**Comment by felixfontein** [comment]
I can confirm @Andersson007's count, 7 SC members voted +1 before his post, and one afterwards (and before mine). Nobody voted against, and no non-SC member voted at all.

So this rule change got approved. Thanks everyone!

**Comment by Andersson007** [comment]
Thanks everyone! Hope the inclusion process among other things will get smoother and less noisy since now!
