### ISSUE TITLE
Resignation from the Steering Committee

### ISSUE THREAD

**Issue by tadeboro** [ansible-community/community-topics#72]
### Summary

Dear all,

As some of you already know, I switched jobs at the start of 2022. One of the side-effects this change had is that I no longer use Ansible during my day job. Combined with the fact that I never used Ansible in my projects, my current Ansible usage is more or less non-existent.

Because Ansible has been moving quite fast recently, my knowledge is less and less relevant with each passing day. And since I do not see things changing anytime soon, it makes little sense for me to continue serving as a Steering Committee member.

**So I am stepping down as a Steering Committee Chair and member, effective immediately.**

Thank you all for your support, and I wish you all the best in the future.

Sincerely yours,
Tadej Borovšak

**Comment by Andersson007** [comment]
you're not replaceable, Tadej.. Thank you much for your service to the community and the project!

**Comment by samccann** [comment]
😭   Sorry to see you stepping down but as others have said, quite understandable. Know you've made an impact while you were here and we'll all miss you!

**Comment by cybette** [comment]
Thank you Tadej for your significant contributions and an allround wonderful person, we will miss you indeed!
