### ISSUE TITLE
Where to place examples in a collection

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#73]
### Summary

This came up in [#70 (comment)](https://github.com/ansible-community/community-topics/issues/70#issuecomment-1055660811).

While most examples should go into the `EXAMPLES` block in the module documentation, some collections like https://github.com/redhat-cop/tower_configuration/ have an `examples/` directory for more complex ones showing how to combine _several_ modules or roles to achieve something.

My question is: Should there be a guidance where to put examples? [Collection directories and files](https://docs.ansible.com/ansible/5/dev_guide/developing_collections_structure.html#collection-directories-and-files) could show an `examples/` directory where they should be placed. Or, since examples are a kind of documentation, should people place them into `docs/examples/`? Or would someone prefer another place?

Or do you think collections should place them where they want? For users, I think it would be beneficial to always find them in the same place, not in `samples/` in one collection, `docs/examples/` in another and somwhere else in a third.

**Comment by samccann** [comment]
+1 as well for standardizing.  My initial thought is - while there is place for documentation (and examples within documentation) it's harder I'm guessing to have CI testing validate those examples embedded in an RST file. So my off the cuff suggestion is to have an `/examples/` directory somewhere and not specifically under the existing `/docs/ ` directory.  We could probably come up with some kind of recommendations on how to put examples in a separate folder AND include them within documentation as well. 

I know someone has  gotten their integration tests from a collection into rst files with a script, but I don't know how complex that script is.

Mind you, if there is no way for CI to test out the more complex examples (multi-module etc) we're talking about here, then maybe we do want them formatted for documentation anyway....

**Comment by mariolenz** [comment]
>  So my off the cuff suggestion is to have an `/examples/` directory somewhere and not specifically under the existing `/docs/ ` directory.

I think an `/examples` directory directly in the root of a collection would be the best place. Hopefully, that's what most collections already use anyway.

> We could probably come up with some kind of recommendations on how to put examples in a separate folder AND include them within documentation as well.

We use [collection_prep](https://github.com/ansible-network/collection_prep) in [community.vmware](https://github.com/ansible-collections/community.vmware) to create the docs. Maybe it could convert the examples to RST files in `/docs/examples`. Just an idea, the main issue is to standardize the place for examples.

> Mind you, if there is no way for CI to test out the more complex examples (multi-module etc) we're talking about here, then maybe we do want them formatted for documentation anyway....

See above, maybe `collection_prep` could do this.

Just to make this clear: With examples, I mean example _playbooks_ (or at least tasks / parts of playbooks) in YAML. Examples that are already in RST or a similar format should go somewhere under `/docs` imho.

**Comment by felixfontein** [comment]
> > Mind you, if there is no way for CI to test out the more complex examples (multi-module etc) we're talking about here, then maybe we do want them formatted for documentation anyway....
> 
> See above, maybe `collection_prep` could do this.

`collection_prep` is unrelated to the Ansible docsite (https://docs.ansible.com/ansible/devel/), so it won't help for that one. Except if it could format examples in the correct place (`docs/docsite/rst/`), I guess.

**Comment by mariolenz** [comment]
> `collection_prep` is unrelated to the Ansible docsite (https://docs.ansible.com/ansible/devel/), so it won't help for that one.

Sorry, I don't know how the documentation for the Ansible docsite is created. I thought the `docs/` directory from a collection is used, but it sounds like it isn't.

> Except if it could format examples in the correct place (`docs/docsite/rst/`), I guess.

So if `collection_prep` would use the playbooks in `examples/` to create RST files in `docs/docsite/rst/examples/`, it would be easier to automatically get them into the Ansible documentation? Well, that might be worth considering.

But I guess this is another discussion. The main question here is if and how to have a standard directory for examples.

What do you think about `examples/` in the root of a collection, @felixfontein?

**Comment by briantist** [comment]
I like the idea of an `examples/` directory. I think that there should be an easy way to either opt-in or opt-out of validation of whatever is in that directory tree though.

If you have examples that are meant to pass validation, it's very useful to have that checked automatically, however you may have examples that are examples in the sense that they demonstrate functionality or possible configuration or whatever, but would not validate. I think there is value in those too, and I could see trying to edit those to pass validation could be a time sink and make the end result worse.

I also agree that getting examples into RST in an automated way is a separate discussion. there's a lot of variables to that.

It's certainly possible to manually choose when you want to include some example in a docsite RST doc, vs. putting something in examples.

What _is_ relevant for this discussion probably, is guidance on how to link from an RST doc or from plugin/module documentation, to the `examples/` directory in GitHub/source control.

For example, should we link to the default branch version (`main` for example)? I would think so, generally, but it does mean that documentation on older versions (including older stable versions) may be linking to examples that are no longer relevant.

But on the other hand, I don't know of an easy way to link from RST to the specific commit or tag that was used to generate the docs.

It's probably not terribly important.. in the case of stable branches, I suppose those could link to the HEAD of their branch?

**Comment by mariolenz** [comment]
This issue is quite stale, no new comments for two years. I think we should close it here. If the need arises to discuss this again, we should open a topic in the forum.
