### ISSUE TITLE
[Vote ended on 2022-03-16] To include community.sap collection in the Ansible package

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#74]
### Summary

community.sap and ~~nautobot~~ are ready for inclusion in the Ansible package, see the related discussions:
- ~~[nautobot discussion](https://github.com/ansible-collections/ansible-inclusion/discussions/28)~~
- [community.sap](https://github.com/ansible-collections/ansible-inclusion/discussions/39)

The first reviews by Tadej haven't been finished (I've pinged him twice and got no response) but I reviewed the collections and can confirm that all things from Tadej's reviews were fixed.

~~I suggest including them next Monday March 07, 2022 automatically because it has been reviewed twice (as described in https://github.com/ansible/community-docs/pull/51, which is not merged yet but there have been no objections about it so far) provided that there are no critical obstacles. So no vote is needed.~~

If you have any objections, please say.

UPDATED because of https://github.com/ansible-community/community-topics/issues/74#issuecomment-1056874256: ok, let's vote
UPDATED nautobot needs some fixes, so i'll create a separate topic later

**Comment by felixfontein** [comment]
So far we always voted on any inclusion (no matter how many positive reviews they had), I think we should also do that here.

**Comment by Andersson007** [comment]
> So far we always voted on any inclusion (no matter how many positive reviews they had), I think we should also do that here.

OK:) let's vote then

+1

**Comment by felixfontein** [comment]
I've adjusted the end date to 2022-03-16, so it's +14 days from now instead some weeks in the past :)

**Comment by felixfontein** [comment]
+1 on including community.sap. The nautobot collection needs some minor adjustments first IMO.

**Comment by markuman** [comment]
+1

**Comment by Andersson007** [comment]
I'll change the title and the description for community.sap only, so that we can ask the committee to vote today

**Comment by ssbarnea** [comment]
`-0` On this one, basically because I do not like the kitchensink status of community package and I do not find SAP as being generic enough to get in. What is the downside of using galaxy to install it?

**Comment by Andersson007** [comment]
> `-1` On this one, basically because I do not like the kitchen-sink status of community package and I do not find SAP as being generic enough to get in. What is the downside of using galaxy to install it?

I think it's worth discussing this more broadly in a separate topic as, imo, there's no downside of using galaxy with any new collection and whether we wanna continue to ship a kitchen-sink.
I'll create the topic soon, thanks for bringing this up!

As there's no requirement to be generic in the inclusion requirements for collections at the moment, i suggest proceeding with the inclusion of community.sap.

Who hasn't voted yet, please vote as today is a deadline

**Comment by gundalow** [comment]
+1 to inclusion
Though I agree with @ssbarnea and @Andersson007, we need to have a separate discussion about the future of the `ansible` package, and what we want from it long term.

**Comment by briantist** [comment]
+1

I also think that the question of whether to continue a kitchen-sink package is a broad and very separate question, and as it relates to "genericism" that's tricky to nail down. The inclusion criteria right now I think are fairly objective, which is a good thing; if we want to introduce subjectivity into the inclusion process, it needs to be made part of inclusion criteria and we should probably figure out how to decide the subjective items before we make maintainers jump through objective hoops that won't matter anyway.

This also brings up the question of why we vote if the inclusion criteria are objective; what's the purpose of being able to dissent _after_ a long process of meeting those criteria rather than early on in the process?

**Comment by Andersson007** [comment]
>This also brings up the question of why we vote if the inclusion criteria are objective; what's the purpose of being able to dissent after a long process of meeting those criteria rather than early on in the process?

the process suggested in https://github.com/ansible/community-docs/pull/49 will fix this:)

**Comment by jillr** [comment]
+1 to inclusion of community.sap

**Comment by Andersson007** [comment]
SC 8 for inclusion
SC 1 against

**Comment by felixfontein** [comment]
I agree, 8 SC votes for inclusion of community.sap, one SC vote against, no other votes.

**Comment by Andersson007** [comment]
Included. Thanks everyone! Thanks @rainerleber for the new collection!
