### ISSUE TITLE
Clarify bugfixes for collections includeed in Ansible

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#75]
### Summary

[Ansible Community Package Collections Requirements](https://github.com/ansible-collections/overview/blob/bbec2b158204145d7b0d42a1c3034510450e36d9/collection_requirements.rst) states:

```
Therefore, please make sure that the current major release of your collection included in 3.0.0 receives at least bugfixes as long as new 3.Y.Z releases are produced.
```

AFAIK, ansible-core [distinguishes](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-changelogs) between general, critical and security bug fixes.

The question here is: If Ansible 6 is released, would it be sufficient to fix only _security_ bugs in the collection that's part of Ansible 5? Or should it be at least _critical_ bugs fixes? Or is the requirement to fix _all_ bugs?

**Comment by felixfontein** [comment]
Once Ansible 6 is released, Ansible 5 is EOL (+- a few weeks at most), so there's no need to release older versions of the collections for Ansible 5. Also this is not a requirement, but something that would be nice to have (it does not say `must`, it says `please` :) ).

**Comment by mariolenz** [comment]
> Also this is not a requirement, but something that would be nice to have (it does not say `must`, it says `please` :) ).

Thanks for your answer @felixfontein! If it's just nice to have, I agree that we don't need a clarification on this.

We're a bit short-staffed so the priority is on version 2. But I'll try to backport a few things to version1 of our collection while Ansible 5 is still alive (ansible-collections/community.vmware#1235).

cc @goneri
