### ISSUE TITLE
[Vote ends on 2022-03-23] Which files to remove from the Ansible 6 installation

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#76]
### Summary

From Ansible 6 on, exclude the following directories and files from the installation (and thus from the wheels) for every collection included: `tests/`, `docs/`, and every file and directory starting with a period in the collection root ("dot files" like `.gitignore`, directories like `.github/`). All files will still be present in the source tarball on PyPi, they will only not be installed and not be present in wheels.

This approach can be amended (after another vote) if it turns out to cause big problems during the alpha/beta phase of Ansible 6. (For Ansible 7 or a later release, we can of course decide to do something else.)

**Comment by felixfontein** [comment]
+1

**Comment by markuman** [comment]
+1

**Comment by briantist** [comment]
+1 either way

but will this also affect `ansible-galaxy collection install`? imo it should, but maybe that has to be considered separately

**Comment by felixfontein** [comment]
@briantist no, `ansible-galaxy collection install` is completely unrelated to this and will simply install the complete collection (as it always did before). I also don't think that will change anytime soon.

**Comment by Andersson007** [comment]
+1

**Comment by russoz** [comment]
+1

**Comment by konstruktoid** [comment]
+1

**Comment by ssbarnea** [comment]
+1 In favor of stripping any files that are not explicitly part of the collection "runtime". Ideally collection archival process should take care of this but we know that the process is not perfect and that too often the archives endup containing more than needed.

**Comment by gundalow** [comment]
+1

**Comment by acozine** [comment]
+1, slimming down the package is a good idea.

**Comment by felixfontein** [comment]
Votes:
- +1 from 7 SC members (acozine Andersson007 briantist felixfontein jillr markuman ssbarnea) and 3 community members (dmsimard konstruktoid russoz)
- no other votes

**Comment by jillr** [comment]
Re-count: 
* +1 from 8 SC (gundalow, in addition to Felix's list)
* +1 from 3 community members
* no other votes

**Comment by felixfontein** [comment]
Oh, I totally missed gundalow here! Sorry!

**Comment by felixfontein** [comment]
Thanks everyone! https://github.com/ansible-community/antsibull/pull/342 is now merged, once a new version of Antsibull is released (end of this week / beginning of next) we're ready for 6.0.0a1 :-)
