### ISSUE TITLE
[Vote ends on 2022-03-23] Collections included in Ansible must not use files outside of meta/, plugins/, roles/ and playbooks/

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#77]
### Summary

(See #70 for the discussion)

Amend the collection requirements (https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst) as follows:

Collections MUST not use files outside meta/, plugins/, roles/ and playbooks/ in public plugins, roles and playbooks they contain.

("public" means that internal plugins, roles and playbooks, for example which are part of tests, only used to release the collection, etc. are not affected. Everything that can be used from other collections or user playbooks and roles, as well as playbooks that can be called by FQCN, is public.)

**Comment by felixfontein** [comment]
@ssbarnea if you want to vote on this, you have to write a comment. Reactions are ignored :)

**Comment by ssbarnea** [comment]
Ok, +1

**Comment by Andersson007** [comment]
+1

**Comment by rndmh3ro** [comment]
+1

**Comment by schurzi** [comment]
+1

**Comment by felixfontein** [comment]
+1

**Comment by markuman** [comment]
+1

**Comment by briantist** [comment]
+0

I don't know why I have an uneasy feeling about this one. I can't think of a good reason why any such content would use files outside of those paths. and I don't think anything bad is going to happen by enacting this rule... but can't bring myself to a +1 for some reason 👻 it is a mystery

**Comment by felixfontein** [comment]
@briantist this rule is somewhat a liability shift for #76. Basically it says what happens in the situation "if a collection doesn't work when installed from the Ansible package". With this new rule, it's the collection's fault and they have to fix it. Without this rule, it's our problem (a packaging problem) and we have to figure out which files it needs and have to modify our packaging process so that these files are kept for that specific collection.

**Comment by russoz** [comment]
+1

**Comment by konstruktoid** [comment]
+1

**Comment by gundalow** [comment]
+1
Do we need to review and tidy up existing collections
Where should we detect and error/warn if this happens?

**Comment by felixfontein** [comment]
I'm not aware of any collection that violates this. I'm also not sure how we can actually detect this (except by manual review, or by looking for user error reports when removing files breaks something.

**Comment by dmsimard** [comment]
+1

**Comment by jillr** [comment]
+1

**Comment by acozine** [comment]
+1 let's make this a rule and do our best to avoid lame-duck grandfathered corner cases we have to get rid of later. We can add "check these directories" to the new-collection checklist until/unless we figure out a way to automate checking.

**Comment by felixfontein** [comment]
Votes:
- +1 from 7 SC members (acozine Andersson007 felixfontein gundalow jillr markuman ssbarnea) and 5 community members (dmsimard konstruktoid rndmh3ro russoz schurzi)
- +0 from 1 SC member (briantist)
- no other votes

**Comment by acozine** [comment]
Confirmed: 
7 Steering Committee members voted +1
1 Steering Committee member voted +/-0
5 Community members voted +1

**Comment by felixfontein** [comment]
https://github.com/ansible-collections/overview/pull/199 has been merged. Thanks everyone!
