### ISSUE TITLE
Removing unsupported, inactive or otherwise unmaintained collections from the community package

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/community-topics#79]
### Summary

As part of the [Ansible 6.0.0 roadmap](https://github.com/ansible-community/community-topics/issues/56), I would like to consider removing unsupported, inactive or otherwise unmaintained collections from the community package.

The following are known to be superseded by supported or otherwise maintained variants:
- [community.azure](https://github.com/ansible-collections/community.azure) -> [azure.azcollection](https://github.com/ansible-collections/azure)
- [community.google](https://github.com/ansible-collections/community.google) -> [google.cloud](https://github.com/ansible-collections/google.cloud) (note: google.cloud's last release, 1.0.2, was 2019-09-11)
- [servicenow.servicenow](https://github.com/ServiceNowITOM/servicenow-ansible) -> [servicenow.itsm](https://github.com/ansible-collections/servicenow.itsm)
- [community.kubernetes](https://github.com/ansible-collections/community.kubernetes) -> [kubernetes.core](https://github.com/ansible-collections/kubernetes.core)

In addition to the above, the following collections have not had a new release tagged since ansible 4.0.0:
- [cisco.nso](https://github.com/CiscoDevNet/ansible-nso) (1.0.3, 2020-10-26)
- [community.fortios](https://github.com/ansible-collections/community.fortios) (1.0.0, 2021-01-14)
- [community.kubevirt](https://github.com/ansible-collections/community.kubevirt) (1.0.0, 2020-11-25)
  - Note: depends on community.kubernetes which should be removed in favor of kubernetes.core
- [community.skydive](https://github.com/ansible-collections/skydive) (1.0.0, 2020-08-18)
- [cyberark.conjur](https://github.com/cyberark/ansible-conjur-collection) (1.1.0, 2020-05-11)
- [dellemc.os10](https://github.com/ansible-collections/dellemc.os10) (1.1.1, 2020-07-21) (1.2.0 release pending?)
- [dellemc.os6](https://github.com/ansible-collections/dellemc.os6) (1.0.7, 2020-08-03)
- [dellemc.os9](https://github.com/ansible-collections/dellemc.os9) (1.0.4, 2020-08-03)
- [frr.frr](https://github.com/ansible-collections/frr.frr) (1.0.4-dev1, 2020-02-27)
- [ibm.qradar](https://github.com/ansible-collections/ibm.qradar) (1.0.3, 2019-09-05)
- [mellanox.onyx](https://github.com/ansible-collections/mellanox.onyx) (1.0.0, 2020-06-30)
- [ngine_io.exoscale](https://github.com/ngine-io/ansible-collection-exoscale) (1.0.0, 2020-06-16)
- [ngine_io.vultr](https://github.com/ngine-io/ansible-collection-vultr) (1.1.0, 2020-04-12)
- [splunk.es](https://github.com/ansible-collections/splunk.es) (1.0.2, 2020-06-16)

The removed collections could still be installed manually from galaxy if need be and they would be welcome back into the package if there is traction and interest via the normal inclusion process.

**Comment by gundalow** [comment]
Whatever we end up doing, we should over-communicate well in advance any removals

- Reddit
- Twitter
- Bullhorn
- Can we add something to the Collection docs on docs.ansible.com

**Comment by jillr** [comment]
kubernetes.core 1.0.0 is the exact same code as community.kubernetes 1.0.0.  It *should* be a seamless replacement for community.kubevirt.

**Comment by felixfontein** [comment]
After the discussion at today's meeting, I've created a WIP PR with two processes we can adjust and tweak and hopefully vote on soon: https://github.com/ansible-collections/overview/pull/201

These have been modelled on community.kubevirt and community.google, and might also apply to some more collections listed here. The aim wasn't to cover everything, but to have a first start we can finalize before adding more cases :)

**Comment by felixfontein** [comment]
community.kubevirt is currently broken because it depends on community.kubernetes < 2.0.0 while we include community.kubernetes >= 2.0.0. Folks have been working on getting it to work with >= 2.0.0 (resp. kubernetes.core >= 2.0.0 directly), but that effort stagnated half a year ago.

**Comment by felixfontein** [comment]
I just found another case we should think of: collections which screw something up, and fail to fix it: cisco.ucs has been including tarballs of previous releases in their release tarball. We reported that back to them almost a year ago (https://github.com/CiscoDevNet/ansible-ucs/issues/25), and I just noticed that they still do that. In fact their release tarball is growing exponentially from release to release since every new tarball includes all previous tarballs directly, and all tarballs since 1.5.0 also contain the tarballs before them recursively.

I tried to ping them again. But if they don't fix this, we should really remove them. Let's discuss this next week or so.

**Comment by felixfontein** [comment]
I started votes for community.kubevirt and community.kubernetes in #92 resp. #93.

**Comment by Andersson007** [comment]
fyi Dell folks were notified about pending release 1.2.0 of `dellemc.os10` a couple of months ago.
there were some movement in the email thread but no action has been done.
I've reminded them a couple of times but it hasn't helped.
So imo dellemc.os10 should be returned to the removal candidates

**Comment by felixfontein** [comment]
community.kubevirt (https://github.com/ansible-community/ansible-build-data/pull/115) and community.kubernetes (https://github.com/ansible-community/ansible-build-data/pull/116) are gone.

**Comment by felixfontein** [comment]
community.azure 2.0.0 has been released as an empty shell. It will be included in Ansible 7, and I guess we can completely remove it from Ansible 8 or 9.

**Comment by gotmax23** [comment]
The policy change was approved. The process of identifying collections that should be removed continues in https://github.com/ansible-community/community-topics/issues/128.
