### ISSUE TITLE
[Discussion until 2023-03-21] Finalize format for extra links file in a collection

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#80]
### Summary

In the docs meeting we have been for long discussing a way to specify extra links and information for collections to display on the docsite. The original discussion issue (in the antsibull repo) is here: https://github.com/ansible-community/antsibull/issues/340

We have a working implementation (https://github.com/ansible-community/antsibull/pull/355) and plan to merge it next week, so we can soon use this. For how it looks, see https://ansible.fontein.de/collections/community/dns/ (collection overview page) and https://ansible.fontein.de/collections/community/dns/hetzner_dns_record_module.html#authors (module page). The links come from https://github.com/ansible-collections/community.dns/pull/76/files and https://github.com/ansible-collections/community.dns/blob/main/galaxy.yml. Another example is https://ansible.fontein.de/collections/ansible/builtin/, the information shown there is hard-coded.

The data is read from docs/docsite/links.yml, and it has the following format:
```.yaml
---
# This will make sure that plugin and module documentation gets Edit on GitHub links
# that allow users to directly create a PR for this plugin or module in GitHub's UI.
# Remove if the collection repository is not on GitHub, or if you do not want this
# functionality for your collection.
edit_on_github:
  repository: ansible-collections/community.dns
  branch: main
  path_prefix: ''

# Here you can add arbitrary extra links. Please keep the number of links down to a
# minimum! Also please keep the description short, since this will be the text put on
# a button.
# 
# Also note that some links are automatically added from information in galaxy.yml.
# The following are automatically added:
#   1. A link to the issue tracker (if `issues` is specified);
#   2. A link to the homepage (if `homepage` is specified and does not equal the
#      `documentation` or `repository` link);
#   3. A link to the collection's repository (if `repository` is specified).
extra_links:
  - description: Submit a bug report
    url: https://github.com/ansible-collections/community.dns/issues/new?assignees=&labels=&template=bug_report.md
  - description: Request a feature
    url: https://github.com/ansible-collections/community.dns/issues/new?assignees=&labels=&template=feature_request.md

# Specify communication channels for your collection. We suggest to not specify more
# than one place for communication per communication tool to avoid confusion.
communication:
  matrix_rooms:
    - topic: General usage and support questions
      room: '#users:ansible.im'
  irc_channels:
    - topic: General usage and support questions
      network: Libera
      channel: '#ansible'
  mailing_lists:
    - topic: Ansible Project List
      url: https://groups.google.com/g/ansible-project
      # You can also add a `subscribe` field with an URI that allows to subscribe
      # to the mailing list. For lists on https://groups.google.com/ a link is
      # automatically generated.
```
In this discussion we want to ask for feedback on this format from everyone who didn't already heard about this feature.

Further information can be added in the future, but what we cannot do is easily change the format of existing things (without breaking early adopters once this has been merged). So please focus on that :)

**Comment by samccann** [comment]
Not really a format comment, but we should emphasize the `description` field for the extra links should be short as it drives the width of the buttons on the webpage.

**Comment by felixfontein** [comment]
How about changing the comment above `extra_links` as follows:
```
# Here you can add arbitrary extra links. Please keep the number of links down to a
# minimum! Also please keep the description short, since this will be the text put on
# a button.
# 
# Also note that some links are automatically added from information in galaxy.yml.
# The following are automatically added:
#   1. A link to the issue tracker (if `issues` is specified);
#   2. A link to the homepage (if `homepage` is specified and does not equal the
#      `documentation` or `repository` link);
#   3. A link to the collection's repository (if `repository` is specified).
```

**Comment by samccann** [comment]
sounds good to me!

**Comment by GregSutcliffe** [comment]
LGTM :+1:

**Comment by IronTooch** [comment]
Looks awesome, I'd definitely support it!

**Comment by felixfontein** [comment]
Thanks everyone! I've merged the PR, this will start showing up in the devel docs once a new version of antsibull is released (I expect one this week).
