### ISSUE TITLE
[Default inclusion date 2022-08-02] ibm.spectrum_virtualize collection inclusion

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#85]
### Summary

Inclusion discussion: https://github.com/ansible-collections/ansible-inclusion/discussions/35

I reviewed the collection and all things from my review have been fixed.

Could anyone from the SC review the collection once more?

**Comment by Shilpi-J** [comment]
@Andersson007 When can we expect feedback on this? Is something to be done from our side?

**Comment by Andersson007** [comment]
@Shilpi-J the collection requires the second review from SC. Not everyone is subscribed to this repo unfortunately, so I'll mention all.

**Comment by Andersson007** [comment]
@ansible-community/steering-committee could anyone else please review the collection for inclusion?

**Comment by Andersson007** [comment]
the second (non-steering committee) review has been done, could anyone from SC approve the review, i.e. put +1 in a comment under https://github.com/ansible-collections/ansible-inclusion/discussions/35#discussioncomment-2945827

**Comment by Andersson007** [comment]
The second non-SC review has been approved by SC, so the requirements are satisfied.
The collection will automatically be considered included in the package 02 August 2022.
If anyone has any objections, please tell us about them before 02 August 2022.

**Comment by Andersson007** [comment]
Felix merged https://github.com/ansible-community/ansible-build-data/pull/148, thanks everyone!
