### ISSUE TITLE
https://endoflife.date/ansible

### ISSUE THREAD

**Issue by gundalow** [ansible-community/community-topics#87]
### Summary

I've seen https://endoflife.date/ansible mentioned again in Chat, so makes me think folks are using it

Data from https://github.com/endoflife-date/endoflife.date/blob/master/products/ansible.md

1. Does this need to be split into two, `ansible` and `ansible-core`
  * If two pages, we should link to each other
  * If split, consider `timelineImage: true`
3. Docs links should go to `/devel/`
4. version command is for ansible-core, not `ansible`
5. Update our release procedures to update these files
6. General review of wording, link to Matrix

**Comment by mariolenz** [comment]
Thanks for bringing this up @gundalow!

> I've seen https://endoflife.date/ansible mentioned again in Chat, so makes me think folks are using it
> 
> Data from https://github.com/endoflife-date/endoflife.date/blob/master/products/ansible.md
> 
> 1. Does this need to be split into two, `ansible` and `ansible-core`

I'd say: Yes, of course. `ansible` is different from `ansible-core`.

> * If two pages, we should link to each other

Why? People using `ansible` X.Y.Z shouldn't care about the EOL of the underlying `ansible` version. And people using `ansible-core` and install the collections they need via galaxy shouldn't care about `ansible`. It wouldn't hurt, though, but I don't think this would be necessary.

> 3. Docs links should go to `/devel/`

Yes.

> 4. version command is for ansible-core, not `ansible`

Is there a way to get the ansible version? Well, you could use pip (I think it also shows Python packages not installed via pip but with yum or apt or whatever) but there's no other way, is there?

> 5. Update our release procedures to update these files

Good idea!

> 6. General review of wording

Might be a good idea to make this part of the release procedures, too.

**Comment by gundalow** [comment]
WIP PR https://github.com/endoflife-date/endoflife.date/pull/1047

**Comment by felixfontein** [comment]
+1 on splitting it up, and +1 for linking from ansible to ansilbe-core (the other direction isn't really necessary as @mariolenz pointed out, but that one might be of interest)

> Is there a way to get the ansible version? Well, you could use pip (I think it also shows Python packages not installed via pip but with yum or apt or whatever) but there's no other way, is there?

There isn't, and that's really not good. Right now you have to use package manager you used to install it to figure out the version, or run a bit of Python code:
```.sh
python3 -c 'from ansible_collections.ansible_release import ansible_version; print(ansible_version)'
```

I think it would be worth integrating a small CLI program which prints this version, but the hard part is figuring out how to name it... Everything with prefix `ansible` is kind of reserved for the core team, and if we want to use something like `ansible-version` we should better ask for permission / coordinate that.

**Comment by gundalow** [comment]
WIP 
* https://deploy-preview-1047--endoflife-date.netlify.app/ansible-core
* https://deploy-preview-1047--endoflife-date.netlify.app/ansible
* Task List https://github.com/endoflife-date/endoflife.date/pull/1047

**Comment by mariolenz** [comment]
> I think it would be worth integrating a small CLI program which prints this version, but the hard part is figuring out how to name it... Everything with prefix `ansible` is kind of reserved for the core team, and if we want to use something like `ansible-version` we should better ask for permission / coordinate that.

I've opened #89 to discuss this since it's a bit off-topic here.

**Comment by mariolenz** [comment]
Hi all!

> * https://deploy-preview-1047--endoflife-date.netlify.app/ansible-core
> * https://deploy-preview-1047--endoflife-date.netlify.app/ansible
> * Task List [[ansible] Split ansible into "ansible" and "ansible-core" endoflife-date/endoflife.date#1047](https://github.com/endoflife-date/endoflife.date/pull/1047)

There have already been some changes. Feel free to review and comment :-)

**Comment by mariolenz** [comment]
@gundalow Do you think we can close this? It looks like `endoflife` has been updated:

- https://endoflife.date/ansible
- https://endoflife.date/ansible-core

**Comment by felixfontein** [comment]
We should make sure that it is kept updated; for Ansible we have https://github.com/ansible-community/ansible-build-data/issues/167, no idea who will do the update for ansible-core.

**Comment by mariolenz** [comment]
> no idea who will do the update for ansible-core.

FYI, I've just I've opened ansible/ansible#79190 to make the core team aware of this.

**Comment by mariolenz** [comment]
@gundalow @felixfontein FYI ansible-core [will not update endoflife.date](https://github.com/ansible/ansible/issues/79190#issuecomment-1315706813).

**Comment by mariolenz** [comment]
Both https://endoflife.date/ansible-core and https://endoflife.date/ansible look OK to me ATM.

If there's more to discuss, I suggest open a topic in the [forum](https://forum.ansible.com).
