### ISSUE TITLE
[Vote ended on 2022-04-27] Describe how collections can be removed from the Ansible package

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#90]
### Summary

Proposal: merge and adopt the procedures defined in https://github.com/ansible-collections/overview/pull/201

Please vote here (and not in the PR). The vote will close on 2022-04-27.

**Comment by felixfontein** [comment]
+1

**Comment by mariolenz** [comment]
+1

**Comment by Andersson007** [comment]
+1

**Comment by russoz** [comment]
+1

**Comment by briantist** [comment]
+1

**Comment by acozine** [comment]
+1

**Comment by cybette** [comment]
+1

**Comment by wombelix** [comment]
+1

**Comment by Andersson007** [comment]
i confirm the [count by felixfontein](https://github.com/ansible-community/community-topics/issues/90#issuecomment-1111327236)

**Comment by felixfontein** [comment]
Great, thanks everyone!
