### ISSUE TITLE
Collection specific Developer Guide in ansible

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#91]
### Summary

I wanted to update the [Developer Guide](https://docs.ansible.com/ansible/5/dev_guide/platforms/vmware_guidelines.html) for `community.vmware` which still exists in [ansible itself](https://github.com/ansible/ansible/blob/494f9327734b3ef9d2b4e4f2a32d1d4c363cd400/docs/docsite/rst/dev_guide/platforms/vmware_guidelines.rst) (see ansible/ansible#77585).

I was asked if I could move this to the collection. This makes sense to me and I'll try to do it, although I might need some help there and ideally a working example. Anyway, I've seen there is content specific to other collections, too.

Should we address this? That is, identify the collection specific content still in ansible and open issues in the collection repositories to move it?

Thoughts?

_edit:_

- [x] [Guidelines for Ansible Amazon AWS module development](https://github.com/ansible/ansible/blob/2cc74b04c49338b48af070ddd811b25b5d801c12/docs/docsite/rst/dev_guide/platforms/aws_guidelines.rst)
- [x] [OpenStack Ansible Modules](https://github.com/ansible/ansible/blob/2cc74b04c49338b48af070ddd811b25b5d801c12/docs/docsite/rst/dev_guide/platforms/openstack_guidelines.rst)
- [x] [oVirt Ansible Modules](https://github.com/ansible/ansible/blob/2cc74b04c49338b48af070ddd811b25b5d801c12/docs/docsite/rst/dev_guide/platforms/ovirt_dev_guide.rst)
- [x] [Guidelines for VMware module development](https://github.com/ansible/ansible/blob/2cc74b04c49338b48af070ddd811b25b5d801c12/docs/docsite/rst/dev_guide/platforms/vmware_guidelines.rst)
- [x] [Guidelines for VMware REST module development](https://github.com/ansible/ansible/blob/2cc74b04c49338b48af070ddd811b25b5d801c12/docs/docsite/rst/dev_guide/platforms/vmware_rest_guidelines.rst)
- [ ] [Developing Cisco ACI modules](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/developing_modules_general_aci.rst)
- [x] [Windows module development walkthroug](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/developing_modules_general_windows.rst)

**Comment by felixfontein** [comment]
Which parts do you think should be moved to the generic documenation?

**Comment by Andersson007** [comment]
At the first glance, sounds sensible to me in general - collection specific dev guides should, imo, live in corresponding collections.
Let's maybe split this logically into 2 questions:
1. Should dev guides specific to a certain collection (or maybe saying more general all docs specific to a certain collection, not only dev) live in that collection? Sub-questions:
  a) Should the docs be available for readers as they are? If yes, how easy it would be to implement?
  b) Or they should appear somewhere within docs for the collection? (so the path for readers will change)
2. Provided that the answer to question 1 is positive, which files should be moved and to where.

What do you, folks, think?

**Comment by mariolenz** [comment]
fyi: ansible-collections/community.vmware#1294

**Comment by mariolenz** [comment]
>     1. Should dev guides specific to a certain collection (or maybe saying more general all docs specific to a certain collection, not only dev) live in that collection? Sub-questions:
>        a) Should the docs be available for readers as they are? If yes, how easy it would be to implement?
>        b) Or they should appear somewhere within docs for the collection? (so the path for readers will change)

I don't think it makes much sense to still have collection specific stuff (including docs) in https://github.com/ansible/ansible. And it makes more sense to have the collection specific documentation all in one place. So 1b) if you ask me.

For example, all docs specific to `community.vmware` should apear under [community.vmware](https://docs.ansible.com/ansible/devel/collections/community/vmware/). 

>     2. Provided that the answer to question 1 is positive, which files should be moved and to where.

I don't know where there is collection specific documentation scattered around the place, but I found at least some Developer Guides in [docs/docsite/rst/dev_guide/platforms/](https://github.com/ansible/ansible/tree/devel/docs/docsite/rst/dev_guide/platforms) that look collection specific.

**Comment by Andersson007** [comment]
I'm personally OK with moving guides living in [docs/docsite/rst/dev_guide/platforms](https://github.com/ansible/ansible/tree/devel/docs/docsite/rst/dev_guide/platforms) to corresponding collections:
1. If there are volunteers
2. who'll move them to the collections and
3. who'll make them appearing under corresponding subdirs of https://docs.ansible.com/ansible/devel/collections/community

**Comment by samccann** [comment]
amazon.aws is in the process of moving their dev guide to the collection - https://github.com/ansible-collections/amazon.aws/pull/787. Once it shows up in a release, we can stub it out on ansiblle ansible, so not marking it done yet in the checklist above.

**Comment by samccann** [comment]
openstack module dev guide has already been stubbed out and moved (though not to the collection, but that is their choice I guess). Marking that done.

**Comment by samccann** [comment]
ovirt has its own dev guide now as well so stubbed out the old one with a pointer. Marking it done.

(samccann swoops in and does plucks all the low-lying fruit on this one!)

**Comment by samccann** [comment]
Opened an issue for Cisco ACI guide and windows module dev guide migrations.

**Comment by mariolenz** [comment]
I've opened a PR to move the `vmware.vmware_rest` dev guide to the collection: ansible-collections/vmware.vmware_rest#330

**Comment by mariolenz** [comment]
As @felixfontein [pointed out](https://github.com/ansible/ansible/pull/77723#issuecomment-1132495586), this documentation even shows up in [ansible-core](https://docs.ansible.com/ansible-core/2.13/dev_guide/index.html).

I think this is wrong. At the end of the day, I think it would be better to remove this stuff and live with broken links. What do you think?

**Comment by samccann** [comment]
I can remove them from core I think. Let me experiment a bit with that one.

**Comment by samccann** [comment]
They should be removed from core on the next nightly build.

**Comment by mariolenz** [comment]
I think I'll close this topic. We're more or less done, apart from the Cisco ACI stuff. I've opened CiscoDevNet/ansible-aci#298 but it's still not merged, they seem to ignore it.

@samccann My advise is to simply remove the Cisco ACI documentation from the ansible-core dev guide, even if there's no alternative dev guide in the Cisco ACI collection you could link to. If Cisco doesn't care, why should you? At the end of the day, it's their problem...

**Comment by felixfontein** [comment]
> @samccann My advise is to simply remove the Cisco ACI documentation from the ansible-core dev guide, even if there's no alternative dev guide in the Cisco ACI collection you could link to. If Cisco doesn't care, why should you? At the end of the day, it's their problem...

:+1: to that. I've added another ping to the PR, maybe it helps, but i not, we should really just continue with removing that guide.
