### ISSUE TITLE
[Vote ended on 2022-05-01] Removal of broken collection community.kubevirt from Ansible 6

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#92]
### Summary

community.kubevirt depends on community.kubernetes < 2.0.0. Since Ansible 5, community.kubernetes 2.x.y is included, which effectively breaks the community.kubevirt collection. There has been some initial work on making community.kubevirt work with community.kubernetes >= 2.0.0 resp. kubernetes.core >= 2.0.0 (https://github.com/ansible-collections/community.kubevirt/pull/25 and https://github.com/ansible-collections/community.kubevirt/pull/34), but that work was never completed.

We haven't finished voting on procedures on how to remove content from Ansible (see #90), but we discussed this multiple times already and the consensus was to still remove this one. Therefore, I propose:

> Remove community.kubevirt from Ansible 6. Allow to re-add it during the Ansible 6 release cycle once it has been modified to work with the kubernetes.core version included in Ansible 6 by then.

I've set the deadline to in one week, since on May 3rd the second Ansible 6 alpha will be released.

CC @ansible-community/steering-committee

**Comment by felixfontein** [comment]
+1

**Comment by felixfontein** [comment]
(I announced this vote in the collection's repository in https://github.com/ansible-collections/community.kubevirt/issues/43.)

**Comment by ssbarnea** [comment]
+1 and also proposing switching to discussions native polls for these, as it makes voting easier.

**Comment by mariolenz** [comment]
+1

**Comment by briantist** [comment]
+1

> also proposing switching to discussions native polls for these, as it makes voting easier.

and seconding this, not only because it's easier to vote, but I want to stop getting notifications for `+1` votes, without unsubscribing from the issue (in case there are other comments that are relevant).

**Comment by jillr** [comment]
+1

**Comment by Andersson007** [comment]
+1

**Comment by tima** [comment]
Unfortunate but +1

**Comment by acozine** [comment]
+1

**Comment by russoz** [comment]
+1

**Comment by markuman** [comment]
+1

**Comment by mariolenz** [comment]
It looks like everyone agrees on this, so I've created PR ansible-community/ansible-build-data#115 to remove `community.kubevirt`.

**Comment by felixfontein** [comment]
Counting votes:

+1: 9 x steering committee (felixfontein, ssbarnea, mariolenz, briantist, jillr, Andersson007, acozine, russoz, markuman), 1 x community (tima)
-1: zero

So this has been passed. Once someone else from SC can confirm these numbers this has proposal been accepted.

**Comment by mariolenz** [comment]
> +1: 9 x steering committee (felixfontein, ssbarnea, mariolenz, briantist, jillr, Andersson007, acozine, russoz, markuman), 1 x community (tima)
> -1: zero
> 
> So this has been passed. Once someone else from SC can confirm these numbers this has proposal been accepted.

Yep, I confirm. Looks like 9 (10) votes for the removal of `community.kubevirt` and none against it.

**Comment by felixfontein** [comment]
Implemented in https://github.com/ansible-community/ansible-build-data/pull/115.
