### ISSUE TITLE
[Vote ended on 2022-08-03] What to do on Ansible collection dependency violations?

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#94]
### Summary

Right now it's impossible to build an Execution Environment for Ansible 5.6.0 (https://github.com/ansible-community/images/pull/22) since it contains two collections that are incompatible:
1. kubernetes.core 2.3.0, and
2. community.okd 2.1.0 (requires kubernetes.core >= 2.1.0, < 2.3.0).

I created an issue for this in community.okd (https://github.com/openshift/community.okd/issues/148). Also I've completed Toshio's PR for a dependency checker for the Ansible build (https://github.com/ansible-community/antsibull/pull/416), so in the future we'll notice such problems a lot earlier.

But what should we do about such problems? I see two choices if we don't want to ship something broken:
1. Either manually (or automatically) adjust collection versions during the Ansible build to make sure that there are no conflicts: in the above example, kubernetes.core would have to be kept at version 2.2.x until community.okd is updated.
2. Alternatively remove the offending collection (in the above example, community.okd) from the current build of Ansible.
3. The third choice is not doing anything, which means that we ship something that's theoretically broken and that cannot be turned correctly into an EE.

I personally favor 1, since 2 would be a breaking change. On the other hand, 1 means that kubernetes.core maintainers and the collection's users have to suffer (no newer version included) because the community.okd maintainers are not doing their job. Choice 3 isn't something I would consider at all.

What do you think? Right now (since it's already broken) we cannot apply 1 when building Ansible 5.7.0. I hope that the community.okd maintainers fix this problem ASAP (hopefully by Tuesday, when Ansible 5.8.0 is released).

**Comment by felixfontein** [comment]
(For community.okd I created PRs to fix the immediate issue: https://github.com/openshift/community.okd/pull/149 https://github.com/openshift/community.okd/pull/150 This discussion is mostly about what to do once it breaks again, or some other collection dependency breaks.)

**Comment by mariolenz** [comment]
I think 1 is the best option, although we should try and do it automatically. Can't we use the dependencies from galaxy.yml for this? https://github.com/ansible-community/antsibull/pull/416 looks promising.

> On the other hand, 1 means that kubernetes.core maintainers and the collection's users have to suffer (no newer version included) because the community.okd maintainers are not doing their job.

I think we should add this as a reason for removal. It's OK to stick to an older version of a collection for some time for dependency reasons. But if, in this example, community.okd doesn't release a version that works with the current kubernetes.core version we should consider it as broken and remove it.

**Comment by felixfontein** [comment]
Yes, the information from galaxy.yml / MANIFEST.json needs to be used for this. Doing this automatically is more compliated and needs a resolving mechanism (probably using resolvelib, similar what `ansible-galaxy collection install` is doing). That's not impossible to implement, but before that happened we'll have to do it manually anyway :)

> I think we should add this as a reason for removal. It's OK to stick to an older version of a collection for some time for dependency reasons. But if, in this example, community.okd doesn't release a version that works with the current kubernetes.core version we should consider it as broken and remove it.

I agree. So limit the kubernetes.core version (in this example) for the current major release cycle (Ansible X.y.0), and if this isn't fixed soon enough announce that this will cause removal of community.okd in Ansible (X+1).0.0. And if it isn't fixed by the time of Ansible (X+1).0.0's feature freeze, actually remove community.okd from Ansible (X+1).0.0. At that point the kubernetes.core version is no longer restricted by community.okd.

Combining 1 with this would be a good way to a) avoid immediate breaking changes, while b) preventing long-time restrictions of collections by collections depending on them.

**Comment by mariolenz** [comment]
> Yes, the information from galaxy.yml / MANIFEST.json needs to be used for this. Doing this automatically is more compliated and needs a resolving mechanism (probably using resolvelib, similar what `ansible-galaxy collection install` is doing). That's not impossible to implement, but before that happened we'll have to do it manually anyway :)

I hope we never run into a problem where one collection depends on a collection <X, and another depends on the same collections >X. Dependency hell :-/

> So limit the kubernetes.core version (in this example) for the current major release cycle (Ansible X.y.0), and if this isn't fixed soon enough announce that this will cause removal of community.okd in Ansible (X+1).0.0. And if it isn't fixed by the time of Ansible (X+1).0.0's feature freeze, actually remove community.okd from Ansible (X+1).0.0. At that point the kubernetes.core version is no longer restricted by community.okd.

In this case, yes. Bur I'm not sure if we should generally wait on a new Ansible major release. Let's say we run into an issue like this in Ansible 6.1. We should give people some time to fix it, but not necessarily until Ansible 7.
 
> Combining 1 with this would be a good way to a) avoid immediate breaking changes, while b) preventing long-time restrictions of collections by collections depending on them.

Yes, I think it's a good compromise.

**Comment by felixfontein** [comment]
> I hope we never run into a problem where one collection depends on a collection <X, and another depends on the same collections >X. Dependency hell :-/

True! But: we should always have the case that the collections included in the previous release fit together, so in the worse case all collections involved in this problem simply stay at their current version. This only doesn't work right now since we already had a 'broken' release (5.6.0).

Maybe it also makes sense to use both 1 and 2: use 1 for new minor releases, and 2 for new major releases. Otherwise we might have to delay inclusion of a new major release for half a year just because something depending on that collection was too slow in bumping its dependency.

> In this case, yes. Bur I'm not sure if we should generally wait on a new Ansible major release. Let's say we run into an issue like this in Ansible 6.1. We should give people some time to fix it, but not necessarily until Ansible 7.

That would be very unfortunate, but I'm not sure what else to do if we want to avoid breaking changes.

**Comment by briantist** [comment]
+1 to adding to removal criteria. 

The complications around the various ways that dependencies can break, and when, may mean that we never have a policy that clearly covers every scenario, so I think we should look to cover simple cases explicitly, and accept that some will have to be taken on a case-by-case basis and decided.

Similarly that means any automation we have should be open-ended as well (always report problems, but only make fixes in situations where there is a clear unambiguous resolution).

**Comment by Andersson007** [comment]
> +1 to adding to removal criteria.
> 
> The complications around the various ways that dependencies can break, and when, may mean that we never have a policy that clearly covers every scenario, so I think we should look to cover simple cases explicitly, and accept that some will have to be taken on a case-by-case basis and decided.
> 
> Similarly that means any automation we have should be open-ended as well (always report problems, but only make fixes in situations where there is a clear unambiguous resolution).

+1

**Comment by felixfontein** [comment]
CC @dmsimard since this will probably result in extra work for you :)

**Comment by Andersson007** [comment]
i would think more broadly.
@felixfontein you mentioned in the last meeting `we probably should extend the requirements so that collections with dependencies do more testing against newer versions of their dependencies`, imo worth implementing.

Maybe something else that will point out to possible future issues related to dependencies (maybe we should tell them that they should avoid dependencies whenever possible even considering code duplication in some cases, e.g. if it's not big? Not sure what is less painful, replicating patches or urgently fix incompatibility like in c.kubevirt. In any case, maintainers should monitor what happen in their collection dependency collections)

**Comment by felixfontein** [comment]
Proposal for a vote:

1. The dependencies between collections included in Ansible must be valid. If a dependency is violated, the involved collections must be be pinned so that all dependencies are valid again.
2. If a collection has a too strict dependency for a longer time, and forces another collection to be hold back, that collection will be removed from the next major Ansible release. What "longer time" means depends on when the next Ansible major release happens. If a dependent collection prevents a new major version of a collection to be included in the next major Ansible release, the dependent collection will be removed from that major release.
3. We strongly suggest that collections also test against the `main` branches of their dependencies to ensure that incompatibilities with future releases of these are detected as early as possible and can be resolved in time to avoid such problems. Collections depending on other collections must understand that they bear the risk of being removed when they do not ensure compatibility with the latest releases of their dependencies.

**Comment by felixfontein** [comment]
I should have added:

4. Collections included in Ansible must not depend on other collections except if they satisfy one of the following cases:
    1) They have a loose dependency on one (or more) major versions of other collections included in Ansible, for example `ansible.netcommon: >=1.0.0`, or `ansible.netcommon: >=2.0.0, <3.0.0`. In case the collection depended on releases a new major version outside of this version range to be included in the next major Ansible release, the dependent collection will be removed from the next major Ansible release. The cut-off date for this is feature freeze.
    2) They are explicitly being allowed to do by the Steering Committee.

Also some explicit examples:

Example:
1. community.foo 1.2.0 has a dependency on community.bar >= 1.0.0, < 1.3.0.
   * Now community.bar creates a new release 1.3.0. When community.foo doesn't create a new release with a relaxed dependency, we have to include community.bar 1.2.x in the next Ansible release despite 1.3.0 being available.
   * If community.foo does not relax its dependency on community.bar for some time, community.foo will be removed from the next Ansible major release.
   * Unfortunately community.bar has to stay at 1.2.x until either community.bar is removed (in the next major release), or loosens its requirements.
2. community.foonetwork depends on ansible.netcommon >= 2.0.0, <3.0.0. 
   * ansible.netcommon 4.0.0 is released during this major Ansible release cycle.
   * community.foonetwork either releases a new version before feature freeze of the next major Ansible release that allows depending on all ansible.netcommon 4.x.y releases, or it will be removed from the next major Ansible release.

**Comment by felixfontein** [comment]
Some thoughts that went into this:
1. We don't want to forbid dependencies like community.aws depending on amazon.aws and community.okd depending on kubernetes.core, but we also don't want complicated rules that cover these. These dependencies will be covered by the "explicitly approved by SC" clause.
2. Dependencies are important! For example, we'd like to build an Execution Environment for Ansible (the community release), and that only works if all collections with the versions included in Ansible can be installed together by `ansible-galaxy collection install`. That one will barf if there is a dependency violation.

**Comment by felixfontein** [comment]
If there is no fundamental critique to that proposal, I'll create a PR for the collection requirements document in a few days based on this. Then we can start nailing down details, and eventually vote on it :)

**Comment by Andersson007** [comment]
>the involved collections must be be pinned so that all dependencies are valid again.

I'm not sure i fully understand what `pinned` implies. Could you please elaborate a bit more on that?

>They have a loose dependency on one (or more) major versions of other collections included in Ansible,

I'm not an expert in dependencies, not sure i understand this paragraph. Can we change/simplify it a bit?

The examples are very clear, thanks.

I would also put at least p.2 of https://github.com/ansible-community/community-topics/issues/94#issuecomment-1117714961 in our guidelines as an example of practical negative consequences.

**Comment by felixfontein** [comment]
I created a PR here: https://github.com/ansible-collections/overview/pull/205

Please add suggestions / comments / ... there from now on :)

**Comment by ssbarnea** [comment]
Maybe an enforcement of SemVer would partially lower the problems: forbidding capping to minor versions and checking that users do not bump the major version unless they introduce breaking changes.

**Comment by felixfontein** [comment]
If nobody has any suggestions for the PR (https://github.com/ansible-collections/overview/pull/205), I'll create a vote for it tomorrow.

**Comment by felixfontein** [comment]
Right now, we have another dependency violation: community.mongodb 1.4.x depends on community.general < 5.0.0, while both c.mongodb 1.4.1 and c.general 5.3.0 are included in Ansible 6.1.0 (https://github.com/ansible-collections/community.mongodb/issues/482, https://github.com/ansible-community/ansible-build-data/issues/147).

**Comment by ssbarnea** [comment]
Did I read right, we shipped a community edition that with conflicting collections? How was possible to built that?

**Comment by felixfontein** [comment]
It's pretty easy to build, because right now this is only a warning, and not an error, so it can be ignored. I was hoping this wouldn't happen, but without an official decision to not allow this we cannot really prevent it.

**Comment by russoz** [comment]
It feels like shooting the messenger. In addition to more rules in the documentation I reckon we should add code:
* to ansible-galaxy to allow version specifiers like `foo.bar ~= 1.2.0` with the same (or similar) semantics as its Python counterpart
* to have some sort of linter, or auditing tool that will be run against all the collections included (or to be included) in the `ansible` package, validating whether the dependencies abide to the rules

**Comment by felixfontein** [comment]
> * to have some sort of linter, or auditing tool that will be run against all the collections included (or to be included) in the `ansible` package, validating whether the dependencies abide to the rules

I guess the first step once this is accepted is turning the current warning during the `ansible` package build process to an error. 

Hmm, I was just about to say that we would have some advance warning of upcoming `ansible` build errors due to the nightly builds in ansible-build-data (https://github.com/ansible-community/ansible-build-data/actions/workflows/antsibull-build.yml) - but then I saw that there is no `cron:` in https://github.com/ansible-community/ansible-build-data/blob/main/.github/workflows/antsibull-build.yml. I guess that's something we should change.

But yeah, some better linting for at least some of the requirements we have would be awesome.  Contributions welcome, so to say :-)

**Comment by felixfontein** [comment]
I counted votes: 8 x +1 from SC (felixfontein Andersson007 briantist mariolenz acozine russoz cidrblock jamescassell), 1 x +1 from community (watsonb)

**Comment by Andersson007** [comment]
I confirm the [count](https://github.com/ansible-community/community-topics/issues/94#issuecomment-1203636843) by @felixfontein

**Comment by ssbarnea** [comment]
IMHO: do not ship if broken, likely that future version of galaxy and ansible will even prevent you from installing conflicting collections. Think about how pip evolved over time.

We will soon add a check in linter and molecule for these conflicts, making much easier to spot and resolve.

We will also flag ceiling as a potential future issue, so people will be advised to use it only when they already know that newer dependency would break, and not as a "might break" measure.

**Comment by felixfontein** [comment]
Proposal has been merged.

**Comment by felixfontein** [comment]
The hard fail in antsibull is implemented in https://github.com/ansible-community/antsibull/pull/440.

**Comment by felixfontein** [comment]
Closing since this is done.
