### ISSUE TITLE
Stepping down from the Steering Commitee

### ISSUE THREAD

**Issue by jillr** [ansible-community/community-topics#95]
### Summary

Hi Everyone,

I am stepping down from the steering committee effective April 30th, 2022.  I'm not leaving Red Hat or Ansible, however my work inside of Red Hat right now is such that I find I don't have the time necessary to give the community the attention it deserves.  Rather than be perpetually inattentive to the work that we're doing I would prefer to participate as a member of the community.

I'll continue to participate in meetings and discussion topics as I'm able to, I just won't be a voting member of the Committee.

Cheers,
Jill

**Comment by briantist** [comment]
Couldn't have said it better than Felix!

**Comment by bluikko** [comment]
Really heartbroken to see this issue. But perhaps it will give you time to concentrate more on the critical issue of language and diversity.
