### ISSUE TITLE
Also include community.sap_libs, and eventually drop community.sap, from Ansible

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#98]
### Summary

See https://github.com/ansible-collections/ansible-inclusion/discussions/39#discussioncomment-2668159 - community.sap has basically been renamed to community.sap_libs. This isn't unprecedented, see community.kubernetes → kubernetes.core (adding it to Ansible was decided in some meeting, maybe someone can quickly find the logs, but the deprecation and eventual removal of community.kubernetes was tracked here: https://github.com/ansible-community/community-topics/issues/22).

We should probably set up a procedure how to do this, as it isn't completely unlikely that this will happen more often in the future.

**Comment by Andersson007** [comment]
setting up a procedure SGTM

**Comment by felixfontein** [comment]
I created a proposal for such a process here: https://github.com/ansible-community/ansible-build-data/pull/121

**Comment by felixfontein** [comment]
I created the first PR for renaming (adding the new collection, announcing that the old one will be replaced by deprecated redirects in Ansible 7.0.0) here: https://github.com/ansible-community/ansible-build-data/pull/126

**Comment by felixfontein** [comment]
@rainerleber it might make sense to create a new release of community.sap that has all modules deprecated, so that users will find out about the collection's deprecation. That will allow us to remove community.sap from Ansible eventually without surprising users.

**Comment by rainerleber** [comment]
@felixfontein ok i will do that in the next days :-)

**Comment by felixfontein** [comment]
@rainerleber if you need reviews for PRs for that, feel free to ping me!

**Comment by mariolenz** [comment]
AFAIK `community.sap_libs` has been added some time ago, and `community.sap` has been removed from 10.0.0a1.

If there's anything more to discuss about this, I suggest to open a topic in the [forum](https://forum.ansible.com).
