### ISSUE TITLE
[Default inclusion date 11th May 2022] vmware.vmware_rest collection inclusion

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#99]
### Summary

Inclusion discussion https://github.com/ansible-collections/ansible-inclusion/discussions/24

The collection has got two approvals by SC members. Thanks @tadeboro and @felixfontein!

- According to the [Community collection inclusion workflow](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#collection-inclusion-requests-workflow), I'm going to set up a date (+1 week) when the inclusion decision will be considered made.
- This time period can be used to raise concerns.
- If no objections are raised up to the established date, the inclusion request is considered successfully resolved.

The default date of inclusion will be **11th of May 2022** if no critical concerns will be raised.

**Comment by felixfontein** [comment]
+1

(Tadej isn't a SC member anymore, but stlil was when approving this collection, so I don't think that should be a problem here.)

**Comment by felixfontein** [comment]
Closing since that PR has been merged. Thanks everyone!
